/**
 * Terms of Service Page - SmartSpec Pro
 * Legal terms and conditions for using the platform
 */

import { motion } from 'framer-motion';
import { Link } from 'wouter';
import { ArrowLeft, FileText, Shield, AlertTriangle, Scale, Clock } from 'lucide-react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    icon: FileText,
    content: `By accessing or using SmartSpec Pro ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, you may not access the Service.

These Terms apply to all visitors, users, and others who access or use the Service. By using the Service, you represent that you are at least 18 years of age and have the legal capacity to enter into these Terms.`
  },
  {
    id: 'description',
    title: '2. Description of Service',
    icon: Shield,
    content: `SmartSpec Pro is an AI-powered code generation platform that provides:

• **Code Generation**: Automated generation of production-ready code from natural language descriptions
• **AI Models Access**: Access to multiple AI models for various development tasks
• **Template Library**: Pre-built templates and components for rapid development
• **Collaboration Tools**: Team collaboration features for shared projects
• **API Access**: Programmatic access to our services through APIs

We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time without prior notice.`
  },
  {
    id: 'accounts',
    title: '3. User Accounts',
    icon: Shield,
    content: `**Account Creation**: You must provide accurate, complete, and current information when creating an account. You are responsible for maintaining the confidentiality of your account credentials.

**Account Security**: You are responsible for all activities that occur under your account. Notify us immediately of any unauthorized use or security breach.

**Account Termination**: We reserve the right to terminate or suspend your account at any time for violations of these Terms or for any other reason at our sole discretion.`
  },
  {
    id: 'usage',
    title: '4. Acceptable Use',
    icon: AlertTriangle,
    content: `You agree NOT to use the Service to:

• Generate malicious code, malware, or code intended to harm systems or users
• Violate any applicable laws or regulations
• Infringe upon intellectual property rights of others
• Generate content that is illegal, harmful, threatening, abusive, or discriminatory
• Attempt to gain unauthorized access to our systems or other users' accounts
• Interfere with or disrupt the Service or servers
• Use automated systems to access the Service without permission
• Resell or redistribute the Service without authorization

We reserve the right to investigate and take appropriate action against anyone who violates these provisions.`
  },
  {
    id: 'intellectual-property',
    title: '5. Intellectual Property',
    icon: Scale,
    content: `**Our Content**: The Service and its original content, features, and functionality are owned by SmartSpec Pro and are protected by international copyright, trademark, and other intellectual property laws.

**Your Content**: You retain ownership of any code, content, or materials you create using the Service. By using the Service, you grant us a non-exclusive license to use, store, and process your content solely for providing the Service.

**Generated Code**: Code generated by the Service is provided for your use. You are responsible for ensuring that generated code complies with applicable licenses and does not infringe on third-party rights.

**Feedback**: Any feedback, suggestions, or ideas you provide about the Service may be used by us without any obligation to you.`
  },
  {
    id: 'payment',
    title: '6. Payment Terms',
    icon: FileText,
    content: `**Subscription Plans**: We offer various subscription plans with different features and pricing. Plan details are available on our pricing page.

**Billing**: Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law.

**Credits**: Some features may require credits. Unused credits may expire according to your plan terms.

**Price Changes**: We reserve the right to modify pricing with 30 days' notice. Continued use after price changes constitutes acceptance of new pricing.

**Taxes**: You are responsible for any applicable taxes on your subscription.`
  },
  {
    id: 'disclaimer',
    title: '7. Disclaimer of Warranties',
    icon: AlertTriangle,
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.

We do not warrant that:
• The Service will be uninterrupted, secure, or error-free
• Results obtained from the Service will be accurate or reliable
• Generated code will be free of bugs or suitable for any particular purpose
• Any errors in the Service will be corrected

You use the Service at your own risk. We recommend reviewing and testing all generated code before use in production environments.`
  },
  {
    id: 'limitation',
    title: '8. Limitation of Liability',
    icon: Scale,
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, SMARTSPEC PRO SHALL NOT BE LIABLE FOR:

• Any indirect, incidental, special, consequential, or punitive damages
• Loss of profits, data, use, goodwill, or other intangible losses
• Damages resulting from unauthorized access to or use of our servers
• Damages resulting from any bugs, viruses, or similar issues transmitted through the Service
• Any damages exceeding the amount you paid us in the 12 months preceding the claim

Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above may not apply to you.`
  },
  {
    id: 'indemnification',
    title: '9. Indemnification',
    icon: Shield,
    content: `You agree to defend, indemnify, and hold harmless SmartSpec Pro and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including attorneys' fees) arising from:

• Your use of the Service
• Your violation of these Terms
• Your violation of any third-party rights
• Any content you submit or generate through the Service`
  },
  {
    id: 'changes',
    title: '10. Changes to Terms',
    icon: Clock,
    content: `We reserve the right to modify these Terms at any time. We will provide notice of significant changes by:

• Posting the updated Terms on this page
• Updating the "Last Updated" date
• Sending an email notification for material changes

Your continued use of the Service after changes constitutes acceptance of the modified Terms. If you do not agree to the new Terms, you must stop using the Service.`
  },
  {
    id: 'governing-law',
    title: '11. Governing Law',
    icon: Scale,
    content: `These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which SmartSpec Pro operates, without regard to conflict of law principles.

Any disputes arising from these Terms or the Service shall be resolved through binding arbitration in accordance with applicable arbitration rules, except where prohibited by law.`
  },
  {
    id: 'contact',
    title: '12. Contact Information',
    icon: FileText,
    content: `If you have any questions about these Terms, please contact us:

**Email**: legal@smartspec.pro
**Address**: SmartSpec Pro Legal Department
**Support**: https://smartspec.pro/contact

We aim to respond to all inquiries within 5 business days.`
  }
];

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-purple-50/30 to-pink-50/20">
      <Navbar />
      
      <main className="pt-24 pb-20">
        <div className="container max-w-4xl">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-12"
          >
            <Link href="/" className="inline-flex items-center gap-2 text-gray-600 hover:text-purple-600 mb-6 transition-colors">
              <ArrowLeft className="w-4 h-4" />
              Back to Home
            </Link>
            
            <div className="flex items-center gap-4 mb-4">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                <FileText className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-3xl md:text-4xl font-bold text-gray-900">
                  Terms of Service
                </h1>
                <p className="text-gray-500">Last Updated: January 3, 2025</p>
              </div>
            </div>
            
            <p className="text-lg text-gray-600">
              Please read these terms carefully before using SmartSpec Pro. By using our service, 
              you agree to be bound by these terms and conditions.
            </p>
          </motion.div>

          {/* Table of Contents */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 border border-gray-100 mb-8"
          >
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Table of Contents</h2>
            <div className="grid md:grid-cols-2 gap-2">
              {sections.map((section, index) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="text-gray-600 hover:text-purple-600 transition-colors text-sm py-1"
                >
                  {section.title}
                </a>
              ))}
            </div>
          </motion.div>

          {/* Content Sections */}
          <div className="space-y-8">
            {sections.map((section, index) => (
              <motion.section
                key={section.id}
                id={section.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 + index * 0.05 }}
                className="bg-white/80 backdrop-blur-sm rounded-2xl p-6 md:p-8 border border-gray-100"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center">
                    <section.icon className="w-5 h-5 text-purple-600" />
                  </div>
                  <h2 className="text-xl font-semibold text-gray-900">{section.title}</h2>
                </div>
                <div className="prose prose-gray max-w-none">
                  {section.content.split('\n\n').map((paragraph, pIndex) => (
                    <p key={pIndex} className="text-gray-600 whitespace-pre-line mb-4 last:mb-0">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </motion.section>
            ))}
          </div>

          {/* Footer Note */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.8 }}
            className="mt-12 text-center"
          >
            <p className="text-gray-500 text-sm">
              By using SmartSpec Pro, you acknowledge that you have read, understood, and agree to these Terms of Service.
            </p>
            <div className="flex justify-center gap-4 mt-4">
              <Link href="/privacy" className="text-purple-600 hover:text-purple-700 font-medium">
                Privacy Policy
              </Link>
              <span className="text-gray-300">|</span>
              <Link href="/contact" className="text-purple-600 hover:text-purple-700 font-medium">
                Contact Us
              </Link>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
