import { SpecParser } from '../../src/parser/spec-parser';
import { readFileSync } from 'fs';
import { join } from 'path';

describe('SpecParser', () => {
  let parser: SpecParser;

  beforeEach(() => {
    parser = new SpecParser();
  });

  describe('parse', () => {
    it('should parse todo.md spec correctly', async () => {
      // Read todo.md
      const todoSpec = readFileSync(
        join(__dirname, '../../examples/api-specs/todo.md'),
        'utf-8'
      );

      // Parse
      const ast = await parser.parse(todoSpec);

      // Assertions
      expect(ast.name).toBe('Todo App');
      expect(ast.entities).toHaveLength(2);
      expect(ast.endpoints).toHaveLength(5);
    });

    it('should parse entities correctly', async () => {
      const todoSpec = readFileSync(
        join(__dirname, '../../examples/api-specs/todo.md'),
        'utf-8'
      );

      const ast = await parser.parse(todoSpec);

      // Check Todo entity
      const todoEntity = ast.entities.find(e => e.name === 'Todo');
      expect(todoEntity).toBeDefined();
      expect(todoEntity!.fields).toHaveLength(7);

      // Check fields
      const titleField = todoEntity!.fields.find(f => f.name === 'title');
      expect(titleField).toBeDefined();
      expect(titleField!.type).toBe('string');
      expect(titleField!.constraints).toContainEqual({ type: 'required' });
      expect(titleField!.constraints).toContainEqual({ type: 'max', value: 200 });
    });

    it('should parse endpoints correctly', async () => {
      const todoSpec = readFileSync(
        join(__dirname, '../../examples/api-specs/todo.md'),
        'utf-8'
      );

      const ast = await parser.parse(todoSpec);

      // Check GET /api/todos
      const getEndpoint = ast.endpoints.find(
        e => e.method === 'GET' && e.path === '/api/todos'
      );
      expect(getEndpoint).toBeDefined();
      expect(getEndpoint!.requiresAuth).toBe(true);
      expect(getEndpoint!.parameters.length).toBeGreaterThan(0);

      // Check POST /api/todos
      const postEndpoint = ast.endpoints.find(
        e => e.method === 'POST' && e.path === '/api/todos'
      );
      expect(postEndpoint).toBeDefined();
      expect(postEndpoint!.requiresAuth).toBe(true);
      expect(postEndpoint!.requestBody).toBeDefined();
    });

    it('should parse business rules', async () => {
      const todoSpec = readFileSync(
        join(__dirname, '../../examples/api-specs/todo.md'),
        'utf-8'
      );

      const ast = await parser.parse(todoSpec);

      expect(ast.businessRules.length).toBeGreaterThan(0);
    });

    it('should parse rate limit', async () => {
      const todoSpec = readFileSync(
        join(__dirname, '../../examples/api-specs/todo.md'),
        'utf-8'
      );

      const ast = await parser.parse(todoSpec);

      expect(ast.rateLimit).toBeDefined();
      expect(ast.rateLimit!.requests).toBe(100);
    });
  });

  describe('field parsing', () => {
    it('should parse UUID fields', async () => {
      const spec = `
# Test API

## Entities

### User

**Fields:**
- \`id\`: string (UUID, auto-generated, primary key)
`;

      const ast = await parser.parse(spec);
      const field = ast.entities[0].fields[0];

      expect(field.name).toBe('id');
      expect(field.type).toBe('uuid');
      expect(field.isPrimaryKey).toBe(true);
      expect(field.isAutoGenerated).toBe(true);
    });

    it('should parse foreign keys', async () => {
      const spec = `
# Test API

## Entities

### Todo

**Fields:**
- \`userId\`: string (UUID, foreign key to User, required)
`;

      const ast = await parser.parse(spec);
      const field = ast.entities[0].fields[0];

      expect(field.name).toBe('userId');
      expect(field.isForeignKey).toBe(true);
      expect(field.foreignKeyTo).toBe('User');
    });

    it('should parse constraints', async () => {
      const spec = `
# Test API

## Entities

### Todo

**Fields:**
- \`title\`: string (required, max 200 chars)
- \`completed\`: boolean (default: false)
`;

      const ast = await parser.parse(spec);
      
      const titleField = ast.entities[0].fields.find(f => f.name === 'title');
      expect(titleField!.constraints).toContainEqual({ type: 'required' });
      expect(titleField!.constraints).toContainEqual({ type: 'max', value: 200 });

      const completedField = ast.entities[0].fields.find(f => f.name === 'completed');
      expect(completedField!.constraints).toContainEqual({ type: 'default', value: false });
    });
  });

  describe('endpoint parsing', () => {
    it('should parse HTTP methods correctly', async () => {
      const spec = `
# Test API

## Endpoints

### GET /api/todos

**Description:** Get all todos

### POST /api/todos

**Description:** Create todo

### PUT /api/todos/:id

**Description:** Update todo

### DELETE /api/todos/:id

**Description:** Delete todo
`;

      const ast = await parser.parse(spec);

      expect(ast.endpoints).toHaveLength(4);
      expect(ast.endpoints[0].method).toBe('GET');
      expect(ast.endpoints[1].method).toBe('POST');
      expect(ast.endpoints[2].method).toBe('PUT');
      expect(ast.endpoints[3].method).toBe('DELETE');
    });

    it('should parse authentication requirement', async () => {
      const spec = `
# Test API

## Endpoints

### GET /api/todos

**Authentication:** Required (JWT)

### GET /api/public

**Authentication:** Not required
`;

      const ast = await parser.parse(spec);

      expect(ast.endpoints[0].requiresAuth).toBe(true);
      expect(ast.endpoints[1].requiresAuth).toBe(false);
    });

    it('should parse query parameters', async () => {
      const spec = `
# Test API

## Endpoints

### GET /api/todos

**Query Parameters:**
- completed: boolean (optional)
- limit: integer (optional, default: 20)
`;

      const ast = await parser.parse(spec);
      const endpoint = ast.endpoints[0];

      expect(endpoint.parameters).toHaveLength(2);
      expect(endpoint.parameters[0].name).toBe('completed');
      expect(endpoint.parameters[0].location).toBe('query');
      expect(endpoint.parameters[0].required).toBe(false);
    });

    it('should parse errors', async () => {
      const spec = `
# Test API

## Endpoints

### GET /api/todos/:id

**Errors:**
- 401: Unauthorized
- 404: Not Found
`;

      const ast = await parser.parse(spec);
      const endpoint = ast.endpoints[0];

      expect(endpoint.errors).toHaveLength(2);
      expect(endpoint.errors[0].statusCode).toBe(401);
      expect(endpoint.errors[0].code).toBe('UNAUTHORIZED');
      expect(endpoint.errors[1].statusCode).toBe(404);
      expect(endpoint.errors[1].code).toBe('NOT_FOUND');
    });
  });
});
