#!/usr/bin/env python3
"""
Validate Generate Spec - SmartSpec Workflow Validator

Validates technical specifications generated by generate_spec workflow to ensure:
- Complete technical details
- Architecture diagrams present
- API definitions complete
- Data models defined
- Naming conventions followed
- Cross-references valid

Auto-fixes common issues when possible.
"""

import json
import sys
import re
from pathlib import Path
from typing import Dict, List, Tuple, Any, Optional

class GenerateSpecValidator:
    """Validator for generate_spec workflow output"""
    
    # Required sections in a technical spec
    REQUIRED_SECTIONS = [
        "overview",
        "architecture",
        "api",
        "data_models",
        "implementation",
        "testing"
    ]
    
    # Optional but recommended sections
    RECOMMENDED_SECTIONS = [
        "security",
        "performance",
        "deployment",
        "monitoring",
        "documentation"
    ]
    
    def __init__(self, spec_file: Path, repo_root: Optional[Path] = None):
        """
        Initialize validator
        
        Args:
            spec_file: Path to spec file
            repo_root: Repository root for validating paths
        """
        self.spec_file = Path(spec_file)
        self.repo_root = Path(repo_root) if repo_root else self.spec_file.parent
        self.issues = []
        self.fixes_applied = []
        self.spec_data = None
        
    def load_spec(self) -> bool:
        """Load spec file"""
        try:
            if self.spec_file.suffix == '.json':
                with open(self.spec_file, 'r', encoding='utf-8') as f:
                    self.spec_data = json.load(f)
            elif self.spec_file.suffix == '.md':
                self.spec_data = self._parse_markdown()
            else:
                self.issues.append({
                    'type': 'error',
                    'message': f'Unsupported file type: {self.spec_file.suffix}',
                    'fixable': False
                })
                return False
            return True
        except Exception as e:
            self.issues.append({
                'type': 'error',
                'message': f'Failed to load spec: {str(e)}',
                'fixable': False
            })
            return False
    
    def _parse_markdown(self) -> Dict[str, Any]:
        """Parse markdown spec into structured data"""
        with open(self.spec_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        spec = {}
        current_section = None
        current_content = []
        
        for line in content.split('\n'):
            if line.startswith('## '):
                if current_section:
                    spec[current_section] = '\n'.join(current_content).strip()
                current_section = line[3:].strip().lower().replace(' ', '_')
                current_content = []
            elif current_section:
                current_content.append(line)
        
        if current_section:
            spec[current_section] = '\n'.join(current_content).strip()
        
        return spec
    
    def validate_structure(self) -> None:
        """Validate spec structure"""
        if not isinstance(self.spec_data, dict):
            self.issues.append({
                'type': 'error',
                'message': 'Spec must be a dictionary/object',
                'fixable': False
            })
            return
        
        # Check required sections
        for section in self.REQUIRED_SECTIONS:
            if section not in self.spec_data:
                self.issues.append({
                    'type': 'error',
                    'section': section,
                    'message': f'Missing required section: {section}',
                    'fixable': True,
                    'fix': 'add_section'
                })
            elif not self.spec_data[section] or not str(self.spec_data[section]).strip():
                self.issues.append({
                    'type': 'warning',
                    'section': section,
                    'message': f'Section "{section}" is empty',
                    'fixable': True,
                    'fix': 'add_placeholder'
                })
        
        # Check recommended sections
        for section in self.RECOMMENDED_SECTIONS:
            if section not in self.spec_data:
                self.issues.append({
                    'type': 'info',
                    'section': section,
                    'message': f'Recommended section missing: {section}',
                    'fixable': True,
                    'fix': 'add_section'
                })
    
    def validate_architecture(self) -> None:
        """Validate architecture section"""
        if 'architecture' not in self.spec_data:
            return
        
        arch = str(self.spec_data['architecture'])
        
        # Check for diagram references
        diagram_patterns = [
            r'!\[.*\]\(.*\.(png|jpg|svg|mmd|puml)\)',
            r'```mermaid',
            r'```plantuml',
        ]
        
        has_diagram = any(re.search(pattern, arch) for pattern in diagram_patterns)
        
        if not has_diagram:
            self.issues.append({
                'type': 'warning',
                'section': 'architecture',
                'message': 'No architecture diagram found',
                'fixable': False
            })
        
        # Check for key architecture concepts
        key_concepts = ['component', 'service', 'layer', 'module', 'interface']
        found_concepts = [c for c in key_concepts if c in arch.lower()]
        
        if len(found_concepts) < 2:
            self.issues.append({
                'type': 'warning',
                'section': 'architecture',
                'message': f'Architecture description may be incomplete (found: {", ".join(found_concepts)})',
                'fixable': False
            })
    
    def validate_api(self) -> None:
        """Validate API section"""
        if 'api' not in self.spec_data:
            return
        
        api = str(self.spec_data['api'])
        
        # Check for API endpoints
        endpoint_pattern = r'(GET|POST|PUT|DELETE|PATCH)\s+(/[^\s]+)'
        endpoints = re.findall(endpoint_pattern, api)
        
        if not endpoints:
            self.issues.append({
                'type': 'warning',
                'section': 'api',
                'message': 'No API endpoints found',
                'fixable': False
            })
        else:
            # Check for request/response definitions
            has_request = 'request' in api.lower()
            has_response = 'response' in api.lower()
            
            if not has_request:
                self.issues.append({
                    'type': 'info',
                    'section': 'api',
                    'message': 'API request definitions not found',
                    'fixable': False
                })
            
            if not has_response:
                self.issues.append({
                    'type': 'info',
                    'section': 'api',
                    'message': 'API response definitions not found',
                    'fixable': False
                })
    
    def validate_data_models(self) -> None:
        """Validate data models section"""
        if 'data_models' not in self.spec_data:
            return
        
        models = str(self.spec_data['data_models'])
        
        # Check for model definitions
        model_patterns = [
            r'class\s+\w+',
            r'interface\s+\w+',
            r'type\s+\w+',
            r'model\s+\w+',
        ]
        
        has_models = any(re.search(pattern, models, re.IGNORECASE) for pattern in model_patterns)
        
        if not has_models:
            self.issues.append({
                'type': 'warning',
                'section': 'data_models',
                'message': 'No data model definitions found',
                'fixable': False
            })
        
        # Check for field definitions
        field_pattern = r'(\w+):\s*(\w+)'
        fields = re.findall(field_pattern, models)
        
        if len(fields) < 3:
            self.issues.append({
                'type': 'info',
                'section': 'data_models',
                'message': f'Only {len(fields)} fields found (recommend 3+ per model)',
                'fixable': False
            })
    
    def validate_naming(self) -> None:
        """Validate naming conventions"""
        path_pattern = r'`([^`]+\.(ts|js|py|java|go|rs|md|json|yaml|yml))`'
        
        for section, content in self.spec_data.items():
            if not isinstance(content, str):
                continue
            
            paths = re.findall(path_pattern, content)
            for path, ext in paths:
                filename = Path(path).name
                stem = filename.rsplit('.', 1)[0]
                
                if not self._is_kebab_case(stem):
                    self.issues.append({
                        'type': 'warning',
                        'section': section,
                        'path': path,
                        'message': f'File path not in kebab-case: {path}',
                        'fixable': True,
                        'fix': 'convert_kebab_case'
                    })
    
    def _is_kebab_case(self, name: str) -> bool:
        """Check if name is in kebab-case"""
        return bool(re.match(r'^[a-z0-9]+(-[a-z0-9]+)*(\.[a-z0-9]+)*$', name))
    
    def auto_fix(self) -> None:
        """Apply automatic fixes"""
        for issue in self.issues:
            if not issue.get('fixable'):
                continue
            
            fix_type = issue.get('fix')
            
            if fix_type == 'add_section':
                section = issue.get('section')
                if section and section not in self.spec_data:
                    self.spec_data[section] = f'[TODO: Add {section} section]'
                    self.fixes_applied.append(f'Added section: {section}')
            
            elif fix_type == 'add_placeholder':
                section = issue.get('section')
                if section and not str(self.spec_data.get(section, '')).strip():
                    self.spec_data[section] = f'[TODO: Complete {section} section]'
                    self.fixes_applied.append(f'Added placeholder for: {section}')
    
    def save_spec(self) -> None:
        """Save fixed spec"""
        if self.spec_file.suffix == '.json':
            with open(self.spec_file, 'w', encoding='utf-8') as f:
                json.dump(self.spec_data, f, indent=2, ensure_ascii=False)
        elif self.spec_file.suffix == '.md':
            self._save_markdown()
    
    def _save_markdown(self) -> None:
        """Save spec as markdown"""
        lines = ['# Technical Specification\n']
        
        for section in self.REQUIRED_SECTIONS + self.RECOMMENDED_SECTIONS:
            if section in self.spec_data:
                title = section.replace('_', ' ').title()
                lines.append(f'## {title}\n')
                lines.append(f'{self.spec_data[section]}\n')
        
        for section, content in self.spec_data.items():
            if section not in self.REQUIRED_SECTIONS + self.RECOMMENDED_SECTIONS:
                title = section.replace('_', ' ').title()
                lines.append(f'## {title}\n')
                lines.append(f'{content}\n')
        
        with open(self.spec_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    def generate_report(self) -> str:
        """Generate validation report"""
        lines = ['# Generate Spec Validation Report\n', f'**File:** `{self.spec_file}`\n']
        
        errors = [i for i in self.issues if i['type'] == 'error']
        warnings = [i for i in self.issues if i['type'] == 'warning']
        infos = [i for i in self.issues if i['type'] == 'info']
        
        lines.append(f'## Summary\n')
        lines.append(f'- **Errors:** {len(errors)}')
        lines.append(f'- **Warnings:** {len(warnings)}')
        lines.append(f'- **Info:** {len(infos)}')
        lines.append(f'- **Fixes Applied:** {len(self.fixes_applied)}\n')
        
        if errors:
            lines.append(f'## Errors\n')
            for issue in errors:
                lines.append(f'- {issue["message"]}')
            lines.append('')
        
        if warnings:
            lines.append(f'## Warnings\n')
            for issue in warnings:
                lines.append(f'- {issue["message"]}')
            lines.append('')
        
        if infos:
            lines.append(f'## Recommendations\n')
            for issue in infos:
                lines.append(f'- {issue["message"]}')
            lines.append('')
        
        if self.fixes_applied:
            lines.append(f'## Fixes Applied\n')
            for fix in self.fixes_applied:
                lines.append(f'- {fix}')
            lines.append('')
        
        return '\n'.join(lines)
    
    def validate(self, apply_fixes: bool = False) -> Tuple[bool, str]:
        """Run full validation"""
        if not self.load_spec():
            return False, self.generate_report()
        
        self.validate_structure()
        self.validate_architecture()
        self.validate_api()
        self.validate_data_models()
        self.validate_naming()
        
        if apply_fixes:
            self.auto_fix()
            if self.fixes_applied:
                self.save_spec()
        
        report = self.generate_report()
        errors = [i for i in self.issues if i['type'] == 'error']
        success = len(errors) == 0
        
        return success, report


def main():
    """CLI interface"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Validate generate_spec workflow output')
    parser.add_argument('spec_file', help='Path to spec file')
    parser.add_argument('--repo-root', help='Repository root directory')
    parser.add_argument('--apply', action='store_true', help='Apply automatic fixes')
    parser.add_argument('--output', help='Output report file')
    
    args = parser.parse_args()
    
    validator = GenerateSpecValidator(args.spec_file, args.repo_root)
    success, report = validator.validate(apply_fixes=args.apply)
    
    print(report)
    
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(report)
    
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
