#!/bin/bash

# SmartSpecPro Setup Script
# Run this once to set up the development environment

set -e

# ============================================
# Colors
# ============================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================
# Helper Functions
# ============================================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "  ${GREEN}✓${NC} $1 found"
        return 0
    else
        echo -e "  ${RED}✗${NC} $1 not found"
        return 1
    fi
}

# ============================================
# Main Setup
# ============================================

echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                SmartSpecPro Setup Script                      ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ============================================
# Step 1: Check Prerequisites
# ============================================

log_step "Checking prerequisites..."
echo ""

MISSING_DEPS=0

# Required
echo "Required:"
check_command docker || MISSING_DEPS=1
check_command git || MISSING_DEPS=1

# Check Docker Compose
if docker compose version &> /dev/null 2>&1; then
    echo -e "  ${GREEN}✓${NC} docker compose found"
elif command -v docker-compose &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} docker-compose found"
else
    echo -e "  ${RED}✗${NC} docker compose not found"
    MISSING_DEPS=1
fi

echo ""
echo "Optional (for desktop app development):"
check_command node || log_warn "Node.js not found - needed for desktop app"
check_command pnpm || log_warn "pnpm not found - needed for desktop app"
check_command cargo || log_warn "Rust/Cargo not found - needed for desktop app"

echo ""

if [ $MISSING_DEPS -eq 1 ]; then
    log_error "Missing required dependencies. Please install them first."
    echo ""
    echo "Installation guides:"
    echo "  Docker:  https://docs.docker.com/get-docker/"
    echo "  Git:     https://git-scm.com/downloads"
    exit 1
fi

log_info "All required dependencies found!"

# ============================================
# Step 2: Check Docker is running
# ============================================

log_step "Checking Docker daemon..."

if ! docker info &> /dev/null; then
    log_error "Docker daemon is not running. Please start Docker."
    exit 1
fi

log_info "Docker is running."

# ============================================
# Step 3: Create .env file
# ============================================

log_step "Setting up environment configuration..."

if [ -f ".env" ]; then
    log_warn ".env file already exists."
    echo -n "Overwrite? (y/N): "
    read -r answer
    if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
        log_info "Keeping existing .env file."
    else
        cp .env.example .env 2>/dev/null || create_env_file
        log_info "Created new .env file."
    fi
else
    if [ -f ".env.example" ]; then
        cp .env.example .env
        log_info "Created .env from .env.example"
    else
        # Create minimal .env
        cat > .env << 'EOF'
# SmartSpecPro Environment Configuration
# Generated by setup.sh

# Database
DATABASE_URL=postgresql://smartspec:smartspec_dev@localhost:5432/smartspec
REDIS_URL=redis://localhost:6379

# Security (CHANGE IN PRODUCTION!)
JWT_SECRET=dev_jwt_secret_change_in_production
SMARTSPEC_PROXY_TOKEN=dev_token_12345

# LLM Providers (add your API keys)
OPENROUTER_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Debug
DEBUG=true
LOG_LEVEL=DEBUG
EOF
        log_info "Created minimal .env file."
    fi
fi

# ============================================
# Step 4: Create necessary directories
# ============================================

log_step "Creating necessary directories..."

mkdir -p scripts
mkdir -p logs
mkdir -p desktop-app/sandbox-images/workspace

log_info "Directories created."

# ============================================
# Step 5: Create init-db.sql if not exists
# ============================================

log_step "Setting up database initialization script..."

if [ ! -f "scripts/init-db.sql" ]; then
    cat > scripts/init-db.sql << 'EOF'
-- SmartSpecPro Database Initialization
-- This script runs when PostgreSQL container starts for the first time

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Log initialization
DO $$
BEGIN
    RAISE NOTICE 'SmartSpecPro database initialized successfully';
END $$;
EOF
    log_info "Created scripts/init-db.sql"
else
    log_info "scripts/init-db.sql already exists."
fi

# ============================================
# Step 6: Make scripts executable
# ============================================

log_step "Making scripts executable..."

chmod +x dev.sh 2>/dev/null || true
chmod +x setup.sh 2>/dev/null || true
chmod +x desktop-app/build.sh 2>/dev/null || true
chmod +x desktop-app/sandbox-images/build.sh 2>/dev/null || true
chmod +x desktop-app/sandbox-images/*.sh 2>/dev/null || true

log_info "Scripts are now executable."

# ============================================
# Step 7: Pull Docker images
# ============================================

log_step "Pulling required Docker images..."

docker pull postgres:15-alpine
docker pull redis:7-alpine
docker pull nginx:alpine

log_info "Docker images pulled."

# ============================================
# Step 8: Build services (optional)
# ============================================

echo ""
echo -n "Build Docker services now? This may take a few minutes. (y/N): "
read -r answer

if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
    log_step "Building Docker services..."
    ./dev.sh build
    log_info "Build complete."
else
    log_info "Skipping build. Run './dev.sh build' later to build services."
fi

# ============================================
# Step 9: Desktop app setup (optional)
# ============================================

if command -v node &> /dev/null && command -v pnpm &> /dev/null; then
    echo ""
    echo -n "Set up desktop app dependencies? (y/N): "
    read -r answer
    
    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
        log_step "Installing desktop app dependencies..."
        
        cd desktop-app
        pnpm install
        cd ..
        
        log_info "Desktop app dependencies installed."
    fi
fi

# ============================================
# Complete
# ============================================

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    Setup Complete!                            ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next steps:"
echo ""
echo "  1. Configure API keys in .env file:"
echo "     - OPENROUTER_API_KEY"
echo "     - OPENAI_API_KEY (optional)"
echo "     - ANTHROPIC_API_KEY (optional)"
echo ""
echo "  2. Start the development environment:"
echo "     ${CYAN}./dev.sh start${NC}"
echo ""
echo "  3. Access services:"
echo "     - SmartSpec Web:    http://localhost:3000"
echo "     - Python Backend:   http://localhost:8000"
echo "     - API Docs:         http://localhost:8000/docs"
echo ""
echo "  4. (Optional) Start desktop app:"
echo "     ${CYAN}./dev.sh desktop${NC}"
echo ""
echo "  5. (Optional) Build sandbox images:"
echo "     ${CYAN}./dev.sh sandbox build${NC}"
echo ""
echo "For more commands, run: ${CYAN}./dev.sh help${NC}"
echo ""
