#!/usr/bin/env python3
"""Generate R1.2 illustrative closed JSON Schemas and positive fixtures; no production state."""
import json
from pathlib import Path
R=Path(__file__).resolve().parent; C=R/'contracts'; F=R/'fixtures'
def j(name, body, fixture):
    body={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'https://smartaihub.app/schemas/proposed/sah.'+name.replace('-','.')+'.v1.json',**body}
    (C/(name+'.schema.json')).write_text(json.dumps(body,ensure_ascii=False,indent=2)+'\n')
    (F/(name+'.example.json')).write_text(json.dumps(fixture,ensure_ascii=False,indent=2)+'\n')
def s(minlen=1,maxlen=255): return {'type':'string','minLength':minlen,'maxLength':maxlen}
def arr(item,maxn=60): return {'type':'array','maxItems':maxn,'uniqueItems':True,'items':item}
def obj(required,props): return {'type':'object','additionalProperties':False,'required':required,'properties':props}
def enum(*values): return {'enum':list(values)}
fx=['READ_ONLY','CREATE_DERIVATIVE','MUTATE_DOMAIN','EXTERNAL_EGRESS','RUN_UNTRUSTED_CODE','RELEASE']
sha={'type':'string','pattern':'^sha256:[0-9a-f]{64}$'}; ts={'type':'string','format':'date-time'}
SAMPLE_SHA='sha256:'+'a'*64
j('effect-budget',{'title':'EffectBudgetV1 — display/read-only subset, NOT an execution grant',**obj(['schemaVersion','serverBindingRef','capabilityRefs','allowedEffectClasses','allowedInputRefs','allowedOutputKinds','approvedExternalDestinations','approvedRegionRefs','maxResultAssets','expiresAt'],{
'schemaVersion':{'const':'sah.effect-budget.v1'},'serverBindingRef':s(), 'capabilityRefs':arr(s()), 'allowedEffectClasses':arr(enum(*fx)),'allowedInputRefs':arr(s()),'allowedOutputKinds':arr(s()),'approvedExternalDestinations':arr(s(1,256)),'approvedRegionRefs':arr(s(1,64)),'maxResultAssets':{'type':'integer','minimum':0,'maximum':1000},'maxSpendMinor':{'type':'integer','minimum':0},'currency':{'type':'string','pattern':'^[A-Z]{3}$'},'explicitProhibitions':arr(enum(*fx)), 'sourceDigest':sha,'expiresAt':ts})}, {'schemaVersion':'sah.effect-budget.v1','serverBindingRef':'example:owner-issued-binding-REQUIRES-RUNTIME','capabilityRefs':['example:canonical-depth-capability'],'allowedEffectClasses':['CREATE_DERIVATIVE'],'explicitProhibitions':['EXTERNAL_EGRESS','RELEASE'],'allowedInputRefs':['example:source-001'],'allowedOutputKinds':['depth_sequence'],'approvedExternalDestinations':[],'approvedRegionRefs':[],'maxResultAssets':2,'maxSpendMinor':0,'currency':'THB','sourceDigest':SAMPLE_SHA,'expiresAt':'2026-09-28T01:00:00Z'})

j('admission-checklist',{'title':'AdmissionChecklistV1 — non-authoritative owner-decision projection',**obj(['schemaVersion','candidateDigest','scopeFingerprint','capabilityRef','capabilityContractRevision','offerRevision','sourceAssetRevision','sourceDigest','policyEpochRef','allowedEffectClasses','disposition','checkedAt','expiresAt'],{
'schemaVersion':{'const':'sah.admission-checklist.v1'},'candidateDigest':sha,'scopeFingerprint':s(),'capabilityRef':s(),'capabilityContractRevision':s(),'offerRevision':s(),'sourceAssetRevision':s(),'sourceDigest':sha,'skillReleaseRef':s(),'skillSourceRef':s(),'skillDigest':sha,'policyEpochRef':s(),'quoteRef':s(),'egressApprovalRef':s(),'approvalReceiptRefs':arr(s()),'canonicalActionBindingRef':s(),'allowedEffectClasses':arr(enum(*fx)),'disposition':enum('PREVIEW_ONLY','READY_TO_OWNER_RECHECK','STALE_REAUTHORIZE','DENIED'),'reasonCodes':arr(s()),'checkedAt':ts,'expiresAt':ts})}, {'schemaVersion':'sah.admission-checklist.v1','candidateDigest':SAMPLE_SHA,'scopeFingerprint':'example:current-auth-scope','capabilityRef':'example:canonical-depth-capability','capabilityContractRevision':'example:contract-v1','offerRevision':'example:runner-v1','sourceAssetRevision':'example:source-rev-001','sourceDigest':SAMPLE_SHA,'policyEpochRef':'example:policy-001','approvalReceiptRefs':[],'allowedEffectClasses':['CREATE_DERIVATIVE'],'disposition':'PREVIEW_ONLY','reasonCodes':['RUNTIME_OWNER_CHECK_REQUIRED'],'checkedAt':'2026-09-28T00:00:00Z','expiresAt':'2026-09-28T00:05:00Z'})

j('step-review-checkpoint',{'title':'StepReviewCheckpointV1 — references canonical approval; does not approve by itself',**obj(['schemaVersion','checkpointRef','stageRef','projectRef','sourceRevisionRef','sourceDigest','reviewedArtifactRevisionRef','reviewedArtifactDigest','pendingStepRefs','quoteAndEgressDigest','reviewerScopeFingerprint','policyEpochRef','disposition','expiresAt'],{
'schemaVersion':{'const':'sah.step-review-checkpoint.v1'},'checkpointRef':s(),'stageRef':s(),'projectRef':s(),'sourceRevisionRef':s(),'sourceDigest':sha,'reviewedArtifactRevisionRef':s(),'reviewedArtifactDigest':sha,'skillReleaseDigest':sha,'pendingStepRefs':arr(s()),'quoteAndEgressDigest':sha,'reviewerScopeFingerprint':s(),'policyEpochRef':s(),'canonicalApprovalReceiptRef':s(),'disposition':enum('PENDING','APPROVED_BY_OWNER','REJECTED_BY_OWNER','STALE_REVIEW_REQUIRED','EXPIRED'),'reviewedAt':ts,'expiresAt':ts})},{'schemaVersion':'sah.step-review-checkpoint.v1','checkpointRef':'example:review-001','stageRef':'example:mask-preview','projectRef':'example:project-001','sourceRevisionRef':'example:source-001','sourceDigest':SAMPLE_SHA,'reviewedArtifactRevisionRef':'example:mask-001','reviewedArtifactDigest':SAMPLE_SHA,'pendingStepRefs':['example:generate-scene'],'quoteAndEgressDigest':SAMPLE_SHA,'reviewerScopeFingerprint':'example:scoped-reviewer','policyEpochRef':'example:policy-001','disposition':'PENDING','expiresAt':'2026-09-28T02:00:00Z'})

j('delegation-scope',{'title':'DelegatedCapabilityScopeV1 — projection of canonical attenuated grant',**obj(['schemaVersion','delegationBindingRef','actorAudienceRef','parentScopeRef','allowedCapabilityRefs','allowedAssetRefs','allowedEffectClasses','approvedDestinationRefs','approvedRegionRefs','maxSpendMinor','subdelegationPermitted','remainingDepth','expiresAt'],{
'schemaVersion':{'const':'sah.delegation-scope.v1'},'delegationBindingRef':s(),'actorAudienceRef':s(),'parentScopeRef':s(),'allowedCapabilityRefs':arr(s()),'allowedAssetRefs':arr(s()),'allowedEffectClasses':arr(enum(*fx)),'approvedDestinationRefs':arr(s()),'approvedRegionRefs':arr(s()),'maxSpendMinor':{'type':'integer','minimum':0},'subdelegationPermitted':{'type':'boolean'},'remainingDepth':{'type':'integer','minimum':0,'maximum':8},'policyEpochRef':s(),'expiresAt':ts})},{'schemaVersion':'sah.delegation-scope.v1','delegationBindingRef':'example:canonical-delegation-001','actorAudienceRef':'example:agent-A','parentScopeRef':'example:user-project-scope','allowedCapabilityRefs':['example:canonical-depth-capability'],'allowedAssetRefs':['example:source-001'],'allowedEffectClasses':['READ_ONLY','CREATE_DERIVATIVE'],'approvedDestinationRefs':[],'approvedRegionRefs':[],'maxSpendMinor':0,'subdelegationPermitted':False,'remainingDepth':0,'policyEpochRef':'example:policy-001','expiresAt':'2026-09-28T01:00:00Z'})

public_card=obj(['displayCapabilityId','ownerProductLabel','title','summary','inputKinds','outputKinds','effectClasses','availability','reasonCodes','skillDisplayLabels','allowedActions'],{'displayCapabilityId':s(1,128),'ownerProductLabel':s(1,120),'title':obj(['en','th'],{'en':s(1,150),'th':s(1,150)}),'summary':obj(['en','th'],{'en':s(1,600),'th':s(1,600)}),'inputKinds':arr(s(1,64)),'outputKinds':arr(s(1,64)),'effectClasses':arr(enum(*fx)),'availability':enum('READY','CONDITIONAL','OFFLINE','BLOCKED','NOT_IMPLEMENTED','UNKNOWN'),'reasonCodes':arr(s(1,60)),'skillDisplayLabels':arr(s(1,100)),'allowedActions':arr(enum('DESCRIBE','REQUEST_PREVIEW','REQUEST_INVOKE'))})
j('capability-public-result',{'title':'PublicCapabilityCatalogV1 — strict human/Agent allowlisted response',**obj(['schemaVersion','catalogGeneration','resultType','cards'],{'schemaVersion':{'const':'sah.capability.public-result.v1'},'catalogGeneration':s(1,80),'resultType':enum('COMPLETE','PARTIAL'),'cards':{'type':'array','maxItems':50,'items':public_card},'nextCursor':s(),'searchNoticeCodes':arr(s(1,60))})},{'schemaVersion':'sah.capability.public-result.v1','catalogGeneration':'example:catalog-001','resultType':'COMPLETE','cards':[{'displayCapabilityId':'public:depth-001','ownerProductLabel':'Film Studio','title':{'en':'Extract Depth','th':'สร้าง Depth Map'},'summary':{'en':'Generate a depth pass for an authorized clip.','th':'สร้าง Depth Map สำหรับคลิปที่ได้รับอนุญาต'},'inputKinds':['video_asset'],'outputKinds':['depth_sequence'],'effectClasses':['CREATE_DERIVATIVE'],'availability':'CONDITIONAL','reasonCodes':['RUNTIME_QUALIFICATION_REQUIRED'],'skillDisplayLabels':[],'allowedActions':['DESCRIBE']}],'searchNoticeCodes':[]})

rat=obj(['num','den'],{'num':{'type':'integer','minimum':1,'maximum':1000000000},'den':{'type':'integer','minimum':1,'maximum':1000000000}})
clock=obj(['sourceTimebase','rateMode','ptsManifestRef','ptsDigest'],{'sourceTimebase':rat,'nominalFps':rat,'rateMode':enum('CONSTANT','VARIABLE','UNKNOWN'),'ptsManifestRef':s(),'ptsDigest':sha,'frameCount':{'type':'integer','minimum':1},'clockTransformRef':s(),'audioSyncEvidenceRef':s()})
color=obj(['primaries','transfer','workingSpace','bitDepth'],{'primaries':s(1,60),'transfer':s(1,60),'workingSpace':s(1,80),'bitDepth':{'type':'integer','minimum':1,'maximum':64},'range':enum('FULL','LIMITED','UNKNOWN'),'transformRef':s()})
j('film-media-pass',{'title':'FilmMediaPassV1 — proposed interchange metadata for derived passes',**obj(['schemaVersion','projectRef','sourceAssetRef','sourceRevisionRef','sourceDigest','passAssetRef','passAssetDigest','passKind','measurementClass','clock','color','provenanceClass','createdByCapabilityRef'],{
'schemaVersion':{'const':'sah.film.media-pass.v1'},'projectRef':s(),'sourceAssetRef':s(),'sourceRevisionRef':s(),'sourceDigest':sha,'passAssetRef':s(),'passAssetDigest':sha,'passKind':enum('DEPTH','NORMAL','ALPHA','COLOR','OPTICAL_FLOW','HDR_DERIVATIVE','FRAME_SEQUENCE'),'measurementClass':enum('MEASURED','ESTIMATED','GENERATED','TRANSCODED'),'clock':clock,'color':color,'depth':obj(['scaleClass','coordinateSpace'],{'scaleClass':enum('RELATIVE','METRIC_CALIBRATED'),'coordinateSpace':s(),'calibrationRef':s()}),'normal':obj(['coordinateSpace','axisConvention'],{'coordinateSpace':enum('CAMERA','WORLD','TANGENT'),'axisConvention':s(),'calibrationRef':s()}),'alpha':obj(['representation','premultiplied','channelRange'],{'representation':enum('STRAIGHT','PREMULTIPLIED'),'premultiplied':{'type':'boolean'},'channelRange':enum('FULL','LIMITED')}),'provenanceClass':enum('CAMERA_SOURCE_DERIVATIVE','MODEL_ESTIMATE','SYNTHETIC_INFERENCE','TRANSCODED_DERIVATIVE'),'createdByCapabilityRef':s(),'protectedRegionPolicyRef':s(),'qualityEvidenceRefs':arr(s()),'retimeTransformRef':s()}),'allOf':[{'if':{'properties':{'passKind':{'const':'DEPTH'}},'required':['passKind']},'then':{'required':['depth']}},{'if':{'properties':{'passKind':{'const':'NORMAL'}},'required':['passKind']},'then':{'required':['normal']}},{'if':{'properties':{'passKind':{'const':'ALPHA'}},'required':['passKind']},'then':{'required':['alpha']}},{'if':{'properties':{'passKind':{'const':'HDR_DERIVATIVE'}},'required':['passKind']},'then':{'properties':{'provenanceClass':{'const':'SYNTHETIC_INFERENCE'}}}}]},{'schemaVersion':'sah.film.media-pass.v1','projectRef':'example:project-001','sourceAssetRef':'example:source-clip-001','sourceRevisionRef':'example:source-rev-001','sourceDigest':SAMPLE_SHA,'passAssetRef':'example:depth-sequence-001','passAssetDigest':SAMPLE_SHA,'passKind':'DEPTH','measurementClass':'ESTIMATED','clock':{'sourceTimebase':{'num':1,'den':90000},'nominalFps':{'num':24000,'den':1001},'rateMode':'VARIABLE','ptsManifestRef':'example:pts-sequence-001','ptsDigest':SAMPLE_SHA,'frameCount':120},'color':{'primaries':'bt709','transfer':'bt709','workingSpace':'scene-linear','bitDepth':16,'range':'FULL'},'depth':{'scaleClass':'RELATIVE','coordinateSpace':'CAMERA'},'provenanceClass':'MODEL_ESTIMATE','createdByCapabilityRef':'example:canonical-depth-capability','qualityEvidenceRefs':[]})
# Encode critical cross-field requirements when representable in JSON Schema.
def harden(name, rules):
    p=C/(name+'.schema.json'); s=json.loads(p.read_text()); 
    if rules: s.setdefault('allOf',[]).extend(rules)
    if name=='capability-public-result':s['$id']='https://smartaihub.app/schemas/proposed/sah.capability.public-result.v1.json'
    p.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n')
harden('admission-checklist',[{'if':{'properties':{'disposition':{'const':'READY_TO_OWNER_RECHECK'}},'required':['disposition']},'then':{'required':['canonicalActionBindingRef']}}])
harden('step-review-checkpoint',[{'if':{'properties':{'disposition':{'const':'APPROVED_BY_OWNER'}},'required':['disposition']},'then':{'required':['canonicalApprovalReceiptRef']}}])
harden('film-media-pass',[
    {'if':{'properties':{'passKind':{'const':'ALPHA'},'alpha':{'properties':{'representation':{'const':'STRAIGHT'}},'required':['representation']}},'required':['passKind','alpha']},'then':{'properties':{'alpha':{'properties':{'premultiplied':{'const':False}}}}}},
    {'if':{'properties':{'passKind':{'const':'ALPHA'},'alpha':{'properties':{'representation':{'const':'PREMULTIPLIED'}},'required':['representation']}},'required':['passKind','alpha']},'then':{'properties':{'alpha':{'properties':{'premultiplied':{'const':True}}}}}}
])
harden('capability-public-result',[])
print('generated and cross-field-hardened six R1.2 schemas and fixtures')
