/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/gothic/gothicTheme.ts
 * Command: astryx theme build client/src/themes/gothic/gothicTheme.ts
 * Generated: 2026-07-04T02:32:49.863Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Card' {
  interface XDSCardVariantMap {
    'blue': true;
    'cyan': true;
    'gray': true;
    'green': true;
    'orange': true;
    'pink': true;
    'purple': true;
    'red': true;
    'teal': true;
    'yellow': true;
  }
}
