/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/gothic/gothicTheme.ts
 * Command: astryx theme build client/src/themes/gothic/gothicTheme.ts
 * Generated: 2026-07-04T02:32:49.859Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const gothicIconRegistry: IconRegistry;
export declare const gothicTheme: DefinedTheme;
