/**
 * Feature 135 — Hermes Grok media worker (section 07): DEV-ONLY in-web-process
 * drainer. Mirrors `inlineRenderWorker.ts`'s tick-loop shape (guard-against-
 * double-start `setTimeout` scheduling, `unref()`), behind system-settings
 * flag `web_process_hermes_worker_enabled` (default OFF, read through
 * `hermesWorkerSettings.ts`).
 *
 * PRODUCTION NEVER USES THIS FILE — the shared Hermes worker runs as its own
 * systemd unit (`docker/systemd/smartspec-hermes-worker.service`,
 * `server/hermesWorker/main.ts`), never inside the web process (spec §8.1).
 * This drainer exists purely so a developer can exercise the Hermes media
 * job flow locally without running (or pairing) a separate worker process —
 * it reuses `server/hermesWorker/jobHandlers.ts`'s `createJobHandlers`
 * behind a direct-DB claim shim instead of the HTTP control-plane client.
 *
 * Artifact persistence caveat: the direct-DB shim's `completeArtifact`
 * records a `worker_artifacts` row for job-flow/dev-testing purposes but
 * does NOT durably persist the generated bytes to the storage backend (that
 * requires the real HTTP init-upload/presigned-PUT round trip the actual
 * systemd worker performs) — acceptable for a dev-only, default-OFF tool.
 */
import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { randomBytes } from "node:crypto";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";

import { debugError, debugLog } from "../_core/logger";
import { db } from "../db";
import { workerArtifacts, workerJobEvents, workerJobs, type WorkerJob } from "../../drizzle/schema";
import {
  HERMES_CONNECTION_AUTH_JOB_TYPE,
  HERMES_CONNECTION_DISCONNECT_JOB_TYPE,
  HERMES_CONNECTION_PROBE_JOB_TYPE,
  HERMES_MEDIA_IMAGE_JOB_TYPE,
  HERMES_MEDIA_VIDEO_JOB_TYPE,
} from "../../shared/workerRuntime";
import { getHermesWorkerSettings } from "./hermesWorkerSettings";
import { mintHermesMediaReferenceUrls } from "./hermesMediaAdapter";
import { createPerConnectionHomeStrategy } from "../hermesWorker/hermesInstallation";
import { hermesFfprobe } from "../hermesWorker/ffprobeRunner";
import { createJobHandlers, type JobHandlers } from "../hermesWorker/jobHandlers";
import { createWorkspaceManager } from "../hermesWorker/workspace";
import type { HermesClaimedJob, HermesControlPlaneClient } from "../hermesWorker/controlPlaneClient";

const POLL_INTERVAL_MS = 3_000;
const DEV_LEASE_TTL_MS = 10 * 60_000;

const HERMES_ALL_JOB_TYPES = [
  HERMES_MEDIA_IMAGE_JOB_TYPE,
  HERMES_MEDIA_VIDEO_JOB_TYPE,
  HERMES_CONNECTION_AUTH_JOB_TYPE,
  HERMES_CONNECTION_PROBE_JOB_TYPE,
  HERMES_CONNECTION_DISCONNECT_JOB_TYPE,
] as const;

function isHermesMediaJobType(jobType: string): boolean {
  return jobType === HERMES_MEDIA_IMAGE_JOB_TYPE || jobType === HERMES_MEDIA_VIDEO_JOB_TYPE;
}

/** Minimal subset of `db` this module needs — lets tests inject a fake
 *  without pulling in the whole Drizzle surface (mirrors `inlineRenderWorker.ts`). */
export type HermesDevDrainerDb = Pick<typeof db, "select" | "update" | "insert">;

export interface HermesDevDrainerRepo {
  claimNextJob(): Promise<WorkerJob | null>;
  insertJobEvent(jobId: string, eventType: string, payloadJson: Record<string, unknown>): Promise<void>;
  updateJobTerminal(jobId: string, status: "completed" | "failed", failureReason?: string): Promise<void>;
  insertArtifact(jobId: string, artifact: { artifactType: string; storageRef: string; metadataJson: Record<string, unknown> }): Promise<void>;
  mintReferenceUrls(params: {
    tenantId: string;
    requestedByUserId: number | null;
    references: Array<{ assetId: string }>;
  }): Promise<Array<{ assetId: string; url: string; expiresAt: string }>>;
}

export function createDefaultHermesDevDrainerRepo(dbLike: HermesDevDrainerDb = db): HermesDevDrainerRepo {
  return {
    async claimNextJob() {
      const [candidate] = await dbLike
        .select()
        .from(workerJobs)
        .where(and(eq(workerJobs.status, "queued"), inArray(workerJobs.jobType, [...HERMES_ALL_JOB_TYPES])))
        .orderBy(desc(workerJobs.priority), asc(workerJobs.createdAt))
        .limit(1);
      if (!candidate) return null;

      const leaseOwnerToken = randomBytes(12).toString("hex");
      const claimed = await dbLike
        .update(workerJobs)
        .set({ status: "claimed", leaseOwnerToken, leaseExpiresAt: new Date(Date.now() + DEV_LEASE_TTL_MS) })
        .where(and(eq(workerJobs.id, candidate.id), eq(workerJobs.status, "queued")))
        .returning();
      return (claimed[0] as WorkerJob | undefined) ?? null;
    },
    async insertJobEvent(jobId, eventType, payloadJson) {
      await dbLike.insert(workerJobEvents).values({ workerJobId: jobId, eventType, payloadJson });
    },
    async updateJobTerminal(jobId, status, failureReason) {
      await dbLike
        .update(workerJobs)
        .set({ status, finishedAt: new Date(), ...(failureReason ? { failureReason } : {}) })
        .where(eq(workerJobs.id, jobId));
    },
    async insertArtifact(jobId, artifact) {
      await dbLike.insert(workerArtifacts).values({ workerJobId: jobId, ...artifact });
    },
    async mintReferenceUrls(params) {
      const requestedByUserId = params.requestedByUserId;
      if (params.references.length === 0 || requestedByUserId == null) return [];
      return mintHermesMediaReferenceUrls({ ...params, requestedByUserId });
    },
  };
}

export function createDirectDbControlPlaneClient(repo: HermesDevDrainerRepo): HermesControlPlaneClient {
  return {
    async register() {
      throw new Error("register() is not used by the Hermes dev drainer's direct-DB shim");
    },
    async heartbeat() {},
    async claim() {
      const row = await repo.claimNextJob();
      if (!row) return { job: null, queueDepth: 0 };
      let referenceUrls: HermesClaimedJob["referenceUrls"];
      if (isHermesMediaJobType(row.jobType)) {
        const references = ((row.inputJson as Record<string, unknown> | null)?.references as Array<{ assetId: string }> | undefined) ?? [];
        referenceUrls = await repo.mintReferenceUrls({
          tenantId: row.tenantId,
          requestedByUserId: row.requestedByUserId,
          references,
        });
      }
      const job: HermesClaimedJob = {
        id: row.id,
        jobType: row.jobType,
        tenantId: row.tenantId,
        inputJson: (row.inputJson as Record<string, unknown>) ?? {},
        instructionsJson: (row.instructionsJson as Record<string, unknown>) ?? {},
        capabilityRequirementsJson: (row.capabilityRequirementsJson as Record<string, unknown>) ?? {},
        retryPolicyJson: (row.retryPolicyJson as Record<string, unknown> | null) ?? null,
        timeoutSeconds: row.timeoutSeconds ?? null,
        leaseOwnerToken: row.leaseOwnerToken ?? "",
        leaseExpiresAt: row.leaseExpiresAt ? new Date(row.leaseExpiresAt).toISOString() : null,
        assignmentAttempt: null,
        referenceUrls,
      };
      return { job, queueDepth: 0 };
    },
    async postEvent(jobId, event) {
      await repo.insertJobEvent(jobId, event.eventType, event.payloadJson ?? {});
      if (event.eventType === "job.completed") {
        await repo.updateJobTerminal(jobId, "completed");
      } else if (event.eventType === "job.failed") {
        const failureReason = String((event.payloadJson as Record<string, unknown> | undefined)?.failureReason ?? "hermes dev drainer job failed");
        await repo.updateJobTerminal(jobId, "failed", failureReason);
      }
      return { accepted: true, replayed: false, job: {} };
    },
    async initArtifact(jobId, payload) {
      return { key: payload.fileName, method: "inline", storageRef: `dev-inline://${jobId}/${payload.fileName}` };
    },
    async completeArtifact(jobId, payload) {
      await repo.insertArtifact(jobId, {
        artifactType: payload.artifactType,
        storageRef: payload.storageRef,
        metadataJson: {
          checksumSha256: payload.checksumSha256,
          sizeBytes: payload.sizeBytes,
          contentType: payload.contentType ?? null,
          devDrainerNote: "bytes not durably persisted — dev-only claim shim",
        },
      });
      return { created: true, artifact: { storageRef: payload.storageRef } };
    },
    async refreshReferenceUrls() {
      return [];
    },
  };
}

let sharedHandlers: JobHandlers | null = null;

function getDefaultHandlers(): JobHandlers {
  if (sharedHandlers) return sharedHandlers;
  const repo = createDefaultHermesDevDrainerRepo();
  const client = createDirectDbControlPlaneClient(repo);
  const devRoot = path.join(os.tmpdir(), "smartspec-hermes-worker-dev");
  const strategy = createPerConnectionHomeStrategy({ root: path.join(devRoot, "profiles") });
  const workspaceManager = createWorkspaceManager({ root: path.join(devRoot, "jobs") });
  const hermesBinaryPath = process.env.HERMES_BINARY_PATH || "hermes";
  sharedHandlers = createJobHandlers({
    client,
    strategy,
    workspaceManager,
    spawnImpl: (argv, opts) => spawn(hermesBinaryPath, argv, { cwd: opts.cwd, env: opts.env }) as any,
    // Same wiring requirement as `hermesWorker/main.ts` — without a real
    // prober every video output fails closed at validation.
    ffprobeImpl: (filePath) => hermesFfprobe(filePath),
    logger: {
      info: (msg: string) => debugLog("hermesWorkerDevDrainer", msg),
      warn: (msg: string) => debugLog("hermesWorkerDevDrainer", `WARN: ${msg}`),
      error: (msg: string) => debugError("hermesWorkerDevDrainer", msg),
    },
    config: {
      globalMaxConcurrent: Number(process.env.HERMES_MAX_CONCURRENT_JOBS) || 2,
      invocationTemplate: "print_mode",
      enableFileToolset: false,
      profileRoot: path.join(devRoot, "profiles"),
    },
  });
  return sharedHandlers;
}

export interface HermesWorkerDevDrainerTickDeps {
  repo?: HermesDevDrainerRepo;
  getEnabled?: () => Promise<boolean>;
  handle?: (job: HermesClaimedJob) => Promise<void>;
}

/**
 * One drain pass: if the flag is OFF, no-op. If ON, claims (at most) one
 * queued Hermes job and delegates it to `jobHandlers`. Pure business logic,
 * fully dependency-injectable — exported for direct unit testing (no
 * timers, no real DB, no real Hermes CLI involved).
 */
export async function runHermesWorkerDevDrainerTick(deps: HermesWorkerDevDrainerTickDeps = {}): Promise<void> {
  const getEnabled = deps.getEnabled ?? (async () => (await getHermesWorkerSettings()).webProcessWorkerEnabled);
  const enabled = await getEnabled();
  if (!enabled) return;

  const repo = deps.repo ?? createDefaultHermesDevDrainerRepo();
  const handle = deps.handle ?? getDefaultHandlers().handle;
  const client = createDirectDbControlPlaneClient(repo);

  try {
    const claimed = await client.claim({});
    if (!claimed.job) return;
    await handle(claimed.job);
  } catch (error) {
    debugError("hermesWorkerDevDrainer", "Failed to drain a Hermes job", error);
  }
}

let workerTimer: NodeJS.Timeout | null = null;
let stopped = true;

function scheduleNextTick(delayMs: number): void {
  workerTimer = setTimeout(() => {
    workerTimer = null;
    void runHermesWorkerDevDrainerTick()
      .catch((error) => {
        debugError("hermesWorkerDevDrainer", "Unexpected error in Hermes dev drainer tick", error);
      })
      .finally(() => {
        if (!stopped) scheduleNextTick(POLL_INTERVAL_MS);
      });
  }, Math.max(0, delayMs));
  workerTimer.unref?.();
}

/** Starts the interval drainer (idempotent — a second call while already
 *  running is a no-op). DEV-ONLY — never called by the production systemd
 *  worker path. */
export function startHermesWorkerDevDrainer(): void {
  if (workerTimer) return;
  stopped = false;
  scheduleNextTick(0);
}

/** Stops scheduling NEW ticks. Any tick already in flight is allowed to
 *  finish naturally. */
export function stopHermesWorkerDevDrainer(): void {
  stopped = true;
  if (workerTimer) {
    clearTimeout(workerTimer);
    workerTimer = null;
  }
}
