import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

function resolveFfprobeBinary(): string {
  const candidates = [
    process.env.FFPROBE_PATH,
    "/usr/bin/ffprobe",
    "/usr/local/bin/ffprobe",
    join(homedir(), ".local/bin/ffprobe"),
  ].filter((value): value is string => Boolean(value && value.trim()));

  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate;
  }
  return "ffprobe";
}

function probeFileDurationSeconds(
  filePath: string
): Promise<number | undefined> {
  return new Promise(resolve => {
    const child = spawn(
      resolveFfprobeBinary(),
      [
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        filePath,
      ],
      { stdio: ["ignore", "pipe", "ignore"] }
    );
    let output = "";
    const timeout = setTimeout(() => {
      child.kill("SIGKILL");
      resolve(undefined);
    }, 10_000);
    child.stdout?.on("data", chunk => {
      output += chunk.toString();
    });
    child.on("error", () => {
      clearTimeout(timeout);
      resolve(undefined);
    });
    child.on("close", () => {
      clearTimeout(timeout);
      const durationSeconds = Number(output.trim());
      resolve(
        Number.isFinite(durationSeconds) && durationSeconds > 0
          ? durationSeconds
          : undefined
      );
    });
  });
}

/**
 * Probes the generated bytes instead of trusting a provider's optional
 * duration metadata. This is best-effort because ffprobe is not guaranteed on
 * the web process; callers must retain their provider/codec fallback.
 */
export async function probeAudioDurationMs(
  audioBuffer: Buffer,
  contentType: string
): Promise<number | undefined> {
  const extension = contentType.includes("wav") ? "wav" : "mp3";
  const directory = await mkdtemp(
    join(process.env.TMPDIR || "/tmp", "ssp-video-audio-")
  );
  const filePath = join(directory, `audio.${extension}`);
  try {
    await writeFile(filePath, audioBuffer);
    const durationSeconds = await probeFileDurationSeconds(filePath);
    return durationSeconds === undefined
      ? undefined
      : Math.max(1, Math.round(durationSeconds * 1000));
  } catch {
    return undefined;
  } finally {
    await rm(directory, { recursive: true, force: true }).catch(
      () => undefined
    );
  }
}
