/**
 * Seed MCP-backed media models for user-connected provider accounts.
 * Run with: npx tsx scripts/seed-media-models-mcp-providers.ts
 */

import postgres from "postgres";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const DATABASE_URL =
  process.env.DATABASE_URL ||
  "postgresql://smartspec:smartspec123@localhost:5432/smartspec";

export type McpMediaModelSeed = {
  modelId: string;
  name: string;
  description: string;
  modelType: "image" | "video";
  provider: "magnific" | "higgsfield";
  providerModelId: string;
  toolName: string;
  argumentShape: string;
  aliases: string[];
  creditCost: number;
  aspectRatios: string[];
  durations?: number[];
  sizes?: string[];
  defaultParams?: Record<string, unknown>;
  referenceImageLimit?: number;
  nativeAudioDialogue?: boolean;
  supportsNativeAudio?: boolean;
  priority: number;
  sortOrder: number;
};

const IMAGE_ASPECT_RATIOS = ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"];
const GOOGLE_IMAGE_ASPECT_RATIOS = [
  "1:1",
  "3:2",
  "2:3",
  "4:3",
  "3:4",
  "4:5",
  "5:4",
  "9:16",
  "16:9",
  "21:9",
];
const VIDEO_ASPECT_RATIOS = ["16:9", "9:16", "1:1"];

const DEPRECATED_HIGGSFIELD_MCP_MODELS: Array<{
  modelId: string;
  replacementModelId?: string;
  reason: string;
}> = [
  {
    modelId: "higgsfield/recraft-v4-1",
    replacementModelId: "higgsfield/recraft_v4_1",
    reason: "replaced_by_higgsfield_catalog_id",
  },
  {
    modelId: "higgsfield/seedance_2_0_fast",
    replacementModelId: "higgsfield/seedance_2_0_mini",
    reason: "unknown_higgsfield_mcp_model",
  },
  {
    modelId: "higgsfield/kling3_0_motion_control",
    replacementModelId: "higgsfield/kling3_0",
    reason: "unknown_higgsfield_mcp_model",
  },
  {
    modelId: "higgsfield/happy-horse",
    replacementModelId: "higgsfield/wan2_7",
    reason: "unknown_higgsfield_mcp_model",
  },
];

const HIGGSFIELD_CATALOG_MEDIA_MODELS: McpMediaModelSeed[] = [
  {
    modelId: "higgsfield/nano_banana_2",
    name: "Nano Banana 2 (Higgsfield MCP)",
    description:
      "Fast, next-gen high-quality images through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "nano_banana_2",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield nano banana 2",
      "nano_banana_2",
      "nano banana 2",
      "higgsfield fast",
      "higgsfield high-quality",
      "higgsfield photorealistic",
      "higgsfield versatile",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k" },
    priority: 16,
    sortOrder: 216,
  },
  {
    modelId: "higgsfield/nano_banana_pro",
    name: "Nano Banana Pro (Higgsfield MCP)",
    description:
      "Ultimate quality, text and diagrams through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "nano_banana_pro",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield nano banana pro",
      "nano_banana_pro",
      "nano banana pro",
      "higgsfield quality",
      "higgsfield text-rendering",
      "higgsfield diagrams",
      "higgsfield photorealistic",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k" },
    priority: 17,
    sortOrder: 217,
  },
  {
    modelId: "higgsfield/soul_2",
    name: "Higgsfield Soul 2.0 (Higgsfield MCP)",
    description:
      "Realistic UGC, fashion editorial and character generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "soul_2",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield higgsfield soul 2.0",
      "soul_2",
      "higgsfield soul 2.0",
      "higgsfield ugc",
      "higgsfield fashion",
      "higgsfield editorial",
      "higgsfield realistic",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"],
    defaultParams: { quality: "2k" },
    priority: 18,
    sortOrder: 218,
  },
  {
    modelId: "higgsfield/soul_cinematic",
    name: "Soul Cinema (Higgsfield MCP)",
    description:
      "Cinema-grade stills and concept art through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "soul_cinematic",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield soul cinema",
      "soul_cinematic",
      "soul cinema",
      "higgsfield cinematic",
      "higgsfield dramatic",
      "higgsfield concept-art",
      "higgsfield lighting",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3", "21:9"],
    defaultParams: { quality: "2k" },
    priority: 19,
    sortOrder: 219,
  },
  {
    modelId: "higgsfield/seedream_v5_lite",
    name: "Seedream 5.0 lite (Higgsfield MCP)",
    description:
      "Visual reasoning, instruction-based editing through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "seedream_v5_lite",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield seedream 5.0 lite",
      "seedream_v5_lite",
      "seedream 5.0 lite",
      "higgsfield editing",
      "higgsfield instruction",
      "higgsfield reasoning",
      "higgsfield versatile",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    defaultParams: { quality: "basic" },
    priority: 20,
    sortOrder: 220,
  },
  {
    modelId: "higgsfield/seedream_v5_pro",
    name: "Seedream 5.0 Pro (Higgsfield MCP)",
    description:
      "Deep-thinking image generation, instruction-precise editing, and native text rendering through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "seedream_v5_pro",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield seedream 5.0 pro",
      "seedream_v5_pro",
      "seedream 5.0 pro",
      "higgsfield reasoning",
      "higgsfield text-rendering",
      "higgsfield editing",
      "higgsfield infographics",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    priority: 46,
    sortOrder: 246,
  },
  {
    modelId: "higgsfield/gpt_image_2",
    name: "GPT Image 2 (Higgsfield MCP)",
    description:
      "Next-gen GPT Image model with 1k/2k/4k resolution and low/medium/high quality tiers through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "gpt_image_2",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield gpt image 2",
      "gpt_image_2",
      "gpt image 2",
      "higgsfield text-rendering",
      "higgsfield editing",
      "higgsfield typography",
      "higgsfield photorealistic",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16", "3:2", "2:3"],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k", quality: "low" },
    priority: 21,
    sortOrder: 221,
  },
  {
    modelId: "higgsfield/cinematic_studio_2_5",
    name: "Cinema Studio Image 2.5 (Higgsfield MCP)",
    description:
      "Cinematic stills, up to 4K resolution through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "cinematic_studio_2_5",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield cinema studio image 2.5",
      "cinematic_studio_2_5",
      "cinema studio image 2.5",
      "higgsfield cinematic",
      "higgsfield 4k",
      "higgsfield high-resolution",
      "higgsfield dramatic",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "16:9",
      "9:16",
      "21:9",
    ],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k" },
    priority: 22,
    sortOrder: 222,
  },
  {
    modelId: "higgsfield/marketing_studio_image",
    name: "Marketing Studio Image (Higgsfield MCP)",
    description:
      "One-click product image ads for social campaigns through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "marketing_studio_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield marketing studio image",
      "marketing_studio_image",
      "marketing studio image",
      "higgsfield marketing",
      "higgsfield ads",
      "higgsfield product",
      "higgsfield social-media",
    ],
    creditCost: 0,
    aspectRatios: [
      "auto",
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k" },
    priority: 23,
    sortOrder: 223,
  },
  {
    modelId: "higgsfield/ms_image",
    name: "DTC Ads (Higgsfield MCP)",
    description:
      "DTC ad image generation with brand-kit-aware prompts, avatars, products, and curated ad formats through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "ms_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield dtc ads",
      "ms_image",
      "dtc ads",
      "higgsfield marketing",
      "higgsfield ads",
      "higgsfield product",
      "higgsfield brand-kit",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:2",
      "2:3",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "21:9",
      "27:16",
      "16:27",
      "9:8",
      "8:9",
      "4:9",
      "9:4",
      "auto",
    ],
    sizes: ["1k", "2k", "4k"],
    defaultParams: { resolution: "1k", quality: "low", batch_size: 1 },
    priority: 24,
    sortOrder: 224,
  },
  {
    modelId: "higgsfield/image_auto",
    name: "Auto (Higgsfield MCP)",
    description:
      "Auto-selects the best image model based on prompt intent through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "image_auto",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield auto",
      "image_auto",
      "auto",
      "higgsfield smart",
      "higgsfield routing",
      "higgsfield editing",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    priority: 25,
    sortOrder: 225,
  },
  {
    modelId: "higgsfield/autosprite",
    name: "AutoSprite Animation (Higgsfield MCP)",
    description:
      "Animate a character image into a game-ready sprite sheet PNG with optional atlas and audio metadata through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "autosprite",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield autosprite animation",
      "autosprite",
      "autosprite animation",
      "higgsfield sprite",
      "higgsfield spritesheet",
      "higgsfield animation",
      "higgsfield game",
    ],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: {
      kind: "idle",
      video_tier: "turbo",
      frame_count: 25,
      frame_size: 256,
      remove_bg: "default",
      with_sound: false,
      is_humanoid: true,
    },
    priority: 26,
    sortOrder: 226,
  },
  {
    modelId: "higgsfield/soul_cast",
    name: "Soul Cast (Higgsfield MCP)",
    description:
      "Consistent cinematic character identity through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "soul_cast",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield soul cast",
      "soul_cast",
      "soul cast",
      "higgsfield character",
      "higgsfield identity",
      "higgsfield consistent",
      "higgsfield cinematic",
    ],
    creditCost: 0,
    aspectRatios: ["16:9"],
    defaultParams: { budget: 50 },
    priority: 27,
    sortOrder: 227,
  },
  {
    modelId: "higgsfield/soul_location",
    name: "Soul Location (Higgsfield MCP)",
    description:
      "Environment and location generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "soul_location",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield soul location",
      "soul_location",
      "soul location",
      "higgsfield environment",
      "higgsfield location",
      "higgsfield background",
      "higgsfield scene",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "21:9",
      "9:21",
    ],
    priority: 28,
    sortOrder: 228,
  },
  {
    modelId: "higgsfield/soul_v2",
    name: "Higgsfield Soul 2.0 (Higgsfield MCP)",
    description:
      "Realistic UGC, fashion editorial and character generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "soul_v2",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield higgsfield soul 2.0",
      "soul_v2",
      "higgsfield soul 2.0",
      "higgsfield ugc",
      "higgsfield fashion",
      "higgsfield editorial",
      "higgsfield realistic",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4", "3:2", "2:3"],
    defaultParams: { quality: "2k" },
    priority: 29,
    sortOrder: 229,
  },
  {
    modelId: "higgsfield/z_image",
    name: "Z Image (Higgsfield MCP)",
    description:
      "Super fast, stylized text-to-image through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "z_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield z image",
      "z_image",
      "z image",
      "higgsfield fast",
      "higgsfield budget",
      "higgsfield stylized",
      "higgsfield quick",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    priority: 30,
    sortOrder: 230,
  },
  {
    modelId: "higgsfield/nano_banana",
    name: "Nano Banana (Higgsfield MCP)",
    description:
      "Realistic images, budget-friendly through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "nano_banana",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield nano banana",
      "nano_banana",
      "nano banana",
      "higgsfield budget",
      "higgsfield realistic",
      "higgsfield affordable",
      "higgsfield text-to-image",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    priority: 31,
    sortOrder: 231,
  },
  {
    modelId: "higgsfield/nano_banana_2_shots",
    name: "Nano Banana Pro (Higgsfield MCP)",
    description:
      "Nano Banana Pro image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "nano_banana_2_shots",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield nano banana pro",
      "nano_banana_2_shots",
      "nano banana pro",
    ],
    creditCost: 0,
    aspectRatios: [
      "auto",
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    priority: 32,
    sortOrder: 232,
  },
  {
    modelId: "higgsfield/nano_banana_2_lite",
    name: "Nano Banana 2 Lite (Higgsfield MCP)",
    description:
      "Lite next-gen high-quality images through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "nano_banana_2_lite",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield nano banana 2 lite",
      "nano_banana_2_lite",
      "nano banana 2 lite",
      "higgsfield fast",
      "higgsfield high-quality",
      "higgsfield photorealistic",
      "higgsfield versatile",
    ],
    creditCost: 0,
    aspectRatios: [
      "auto",
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    sizes: ["1k"],
    defaultParams: { resolution: "1k", thinking: "HIGH" },
    priority: 33,
    sortOrder: 233,
  },
  {
    modelId: "higgsfield/seedream_v4_5",
    name: "Seedream 4.5 (Higgsfield MCP)",
    description:
      "4K output, precise control, transformations through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "seedream_v4_5",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield seedream 4.5",
      "seedream_v4_5",
      "seedream 4.5",
      "higgsfield 4k",
      "higgsfield high-resolution",
      "higgsfield precise",
      "higgsfield transformations",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "16:9", "3:2", "21:9", "3:4", "9:16", "2:3"],
    defaultParams: { quality: "basic" },
    priority: 34,
    sortOrder: 234,
  },
  {
    modelId: "higgsfield/flux_2",
    name: "FLUX.2 (Higgsfield MCP)",
    description:
      "Multiple model variants (pro, flex, max), precise prompt adherence through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "flux_2",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield flux.2",
      "flux_2",
      "flux.2",
      "higgsfield precise",
      "higgsfield prompt-adherence",
      "higgsfield creative",
      "higgsfield versatile",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    sizes: ["1k", "2k"],
    defaultParams: { resolution: "1k", variant: "pro" },
    priority: 35,
    sortOrder: 235,
  },
  {
    modelId: "higgsfield/flux_kontext",
    name: "Flux Kontext (Higgsfield MCP)",
    description:
      "Context-aware editing and style transfer through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "flux_kontext",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield flux kontext",
      "flux_kontext",
      "flux kontext",
      "higgsfield editing",
      "higgsfield style-transfer",
      "higgsfield context-aware",
      "higgsfield typography",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    priority: 36,
    sortOrder: 236,
  },
  {
    modelId: "higgsfield/kling_omni_image",
    name: "Kling O1 Image (Higgsfield MCP)",
    description:
      "Versatile photorealistic generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "kling_omni_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield kling o1 image",
      "kling_omni_image",
      "kling o1 image",
      "higgsfield photorealistic",
      "higgsfield versatile",
      "higgsfield wide-aspect-ratio",
      "higgsfield realistic",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "auto",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "3:2",
      "2:3",
      "21:9",
    ],
    sizes: ["1k", "2k"],
    defaultParams: { resolution: "1k" },
    priority: 37,
    sortOrder: 237,
  },
  {
    modelId: "higgsfield/openai_hazel",
    name: "OpenAI Hazel (Higgsfield MCP)",
    description:
      "Powerful editing, best text rendering through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "openai_hazel",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield openai hazel",
      "openai_hazel",
      "openai hazel",
      "higgsfield text-rendering",
      "higgsfield editing",
      "higgsfield typography",
      "higgsfield logos",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "3:2", "2:3", "auto"],
    defaultParams: { quality: "medium" },
    priority: 38,
    sortOrder: 238,
  },
  {
    modelId: "higgsfield/grok_image",
    name: "Grok Image (Higgsfield MCP)",
    description:
      "Expressive, high-contrast generation and editing through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "grok_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield grok image",
      "grok_image",
      "grok image",
      "higgsfield expressive",
      "higgsfield high-contrast",
      "higgsfield editing",
      "higgsfield creative",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "auto",
      "1:2",
      "2:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
    ],
    sizes: ["1k", "2k"],
    defaultParams: { resolution: "1k", mode: "std" },
    priority: 39,
    sortOrder: 239,
  },
  {
    modelId: "higgsfield/recraft_v4_1",
    name: "Recraft V4.1 (Higgsfield MCP)",
    description:
      "V4.1 image generation with selectable model_type for standard exploration, vector logos/icons, utility product shots/mockups, and utility_vector brand assets through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "recraft_v4_1",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield recraft v4.1",
      "recraft_v4_1",
      "recraft v4.1",
      "higgsfield photorealistic",
      "higgsfield illustration",
      "higgsfield typography",
      "higgsfield logos",
    ],
    creditCost: 0,
    aspectRatios: [
      "1:1",
      "3:4",
      "4:3",
      "4:5",
      "5:4",
      "3:2",
      "2:3",
      "16:9",
      "9:16",
    ],
    sizes: ["1k", "2k"],
    defaultParams: { resolution: "1k", model_type: "standard" },
    priority: 40,
    sortOrder: 240,
  },
  {
    modelId: "higgsfield/image_background_remover",
    name: "Image Background Remover (Higgsfield MCP)",
    description:
      "Image Background Remover image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "image_background_remover",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield image background remover",
      "image_background_remover",
      "image background remover",
    ],
    creditCost: 0,
    aspectRatios: [],
    priority: 41,
    sortOrder: 241,
  },
  {
    modelId: "higgsfield/outpaint",
    name: "Outpaint (Higgsfield MCP)",
    description:
      "Outpaint image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "outpaint",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: ["higgsfield outpaint", "outpaint"],
    creditCost: 0,
    aspectRatios: [
      "auto",
      "1:1",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "4:5",
      "5:4",
      "9:16",
      "16:9",
      "21:9",
    ],
    priority: 42,
    sortOrder: 242,
  },
  {
    modelId: "higgsfield/topaz_image",
    name: "Topaz (Higgsfield MCP)",
    description:
      "Topaz image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "topaz_image",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: ["higgsfield topaz", "topaz_image", "topaz"],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: {
      face_enhancement: false,
      face_enhancement_creativity: 0,
      face_enhancement_strength: 0,
      variant: "Standard V2",
      sharpen: 0,
      denoise: 0,
    },
    priority: 43,
    sortOrder: 243,
  },
  {
    modelId: "higgsfield/topaz_image_generative",
    name: "Topaz (Higgsfield MCP)",
    description:
      "Topaz image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "topaz_image_generative",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: ["higgsfield topaz", "topaz_image_generative", "topaz"],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: {
      variant: "Redefine",
      autoprompt: true,
      creativity: 1,
      texture: 1,
      sharpen: 0,
      denoise: 0,
      face_enhancement: false,
      face_enhancement_creativity: 0,
      face_enhancement_strength: 0,
    },
    priority: 44,
    sortOrder: 244,
  },
  {
    modelId: "higgsfield/bytedance_image_upscale",
    name: "Bytedance Image Upscale (Higgsfield MCP)",
    description:
      "Bytedance Image Upscale image generation through Higgsfield MCP provider-account credits.",
    modelType: "image",
    provider: "higgsfield",
    providerModelId: "bytedance_image_upscale",
    toolName: "generate_image",
    argumentShape: "higgsfield.generate_image",
    aliases: [
      "higgsfield bytedance image upscale",
      "bytedance_image_upscale",
      "bytedance image upscale",
    ],
    creditCost: 0,
    aspectRatios: [],
    sizes: ["2k", "4k"],
    defaultParams: { resolution: "4k" },
    priority: 45,
    sortOrder: 245,
  },
  {
    modelId: "higgsfield/cinematic_studio_3_0",
    name: "Cinema Studio Video 3.0 (Higgsfield MCP)",
    description:
      "Most advanced cinema-grade model through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "cinematic_studio_3_0",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield cinema studio video 3.0",
      "cinematic_studio_3_0",
      "cinema studio video 3.0",
      "higgsfield cinematic",
      "higgsfield premium",
      "higgsfield advanced",
      "higgsfield sota",
    ],
    creditCost: 0,
    aspectRatios: ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    sizes: ["480p", "720p", "1080p", "4k"],
    defaultParams: { resolution: "720p", genre: "auto", generate_audio: false },
    priority: 60,
    sortOrder: 260,
  },
  {
    modelId: "higgsfield/cinematic_studio_video",
    name: "Cinema Studio Video (Higgsfield MCP)",
    description:
      "Solid cinematic, dramatic compositions through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "cinematic_studio_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield cinema studio video",
      "cinematic_studio_video",
      "cinema studio video",
      "higgsfield cinematic",
      "higgsfield dramatic",
      "higgsfield compositions",
      "higgsfield sound",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    defaultParams: { slow_motion: false, sound: true },
    priority: 61,
    sortOrder: 261,
  },
  {
    modelId: "higgsfield/cinematic_studio_video_v2",
    name: "Cinema Studio Video (Higgsfield MCP)",
    description:
      "Refined cinematic camera and color, genre control through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "cinematic_studio_video_v2",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield cinema studio video",
      "cinematic_studio_video_v2",
      "cinema studio video",
      "higgsfield cinematic",
      "higgsfield camera",
      "higgsfield color",
      "higgsfield genre",
    ],
    creditCost: 0,
    aspectRatios: ["1:1", "4:3", "3:4", "16:9", "9:16"],
    defaultParams: {
      genre: "auto",
      mode: "std",
      sound: "on",
      speedramp: "auto",
      multi_shots: false,
      multi_shot_mode: "custom",
      cfg_scale: 0.5,
    },
    priority: 62,
    sortOrder: 262,
  },
  {
    modelId: "higgsfield/marketing_studio_video",
    name: "Marketing Studio (Higgsfield MCP)",
    description:
      "One-click product ads, TikTok/Reels ready through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "marketing_studio_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield marketing studio",
      "marketing_studio_video",
      "marketing studio",
      "higgsfield marketing",
      "higgsfield ugc",
      "higgsfield ads",
      "higgsfield tiktok",
    ],
    creditCost: 0,
    aspectRatios: ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    sizes: ["480p", "720p", "1080p"],
    defaultParams: { resolution: "720p", generate_audio: true },
    priority: 63,
    sortOrder: 263,
  },
  {
    modelId: "higgsfield/clipify",
    name: "Personal Clipper (Higgsfield MCP)",
    description:
      "Turn one YouTube video into ready-to-share clips with subtitles through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "clipify",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield personal clipper",
      "clipify",
      "personal clipper",
      "higgsfield youtube",
      "higgsfield clips",
      "higgsfield shorts",
      "higgsfield reels",
    ],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: {
      clips_num: 10,
      clip_aspect: "9:16",
      subtitle_highlight_hex: "#FFE84D",
      subtitle_position: "bottom",
      subtitle_font: "notosans",
      subtitle_case: "as-is",
      track_face_crop: true,
      max_height: 1080,
      segment_seconds: 10,
    },
    priority: 64,
    sortOrder: 264,
  },
  {
    modelId: "higgsfield/higgsfield_preset",
    name: "Higgsfield Preset (Higgsfield MCP)",
    description:
      "Preset-routed image-to-video generation using presets from presets_show through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "higgsfield_preset",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield higgsfield preset",
      "higgsfield_preset",
      "higgsfield preset",
      "higgsfield image-to-video",
      "higgsfield viral",
      "higgsfield template",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    priority: 65,
    sortOrder: 265,
  },
  {
    modelId: "higgsfield/grok_video_v15",
    name: "Grok Video 1.5 (Higgsfield MCP)",
    description:
      "Image-to-video preview model that animates one start image into cinematic video with native audio direction through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "grok_video_v15",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield grok video 1.5",
      "grok_video_v15",
      "grok video 1.5",
      "higgsfield audio",
      "higgsfield cinematic",
      "higgsfield image-to-video",
      "higgsfield start-frame",
    ],
    creditCost: 0,
    aspectRatios: [],
    sizes: ["480p", "720p"],
    defaultParams: { resolution: "720p", duration: 5 },
    nativeAudioDialogue: true,
    supportsNativeAudio: true,
    priority: 66,
    sortOrder: 266,
  },
  {
    modelId: "higgsfield/video_background_remover",
    name: "Video Background Remover (Higgsfield MCP)",
    description:
      "Video Background Remover video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "video_background_remover",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield video background remover",
      "video_background_remover",
      "video background remover",
    ],
    creditCost: 0,
    aspectRatios: [],
    priority: 67,
    sortOrder: 267,
  },
  {
    modelId: "higgsfield/minimax_hailuo",
    name: "Minimax Hailuo (Higgsfield MCP)",
    description:
      "Natural physics, facial emotion, multiple variants through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "minimax_hailuo",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield minimax hailuo",
      "minimax_hailuo",
      "minimax hailuo",
      "higgsfield physics",
      "higgsfield emotion",
      "higgsfield facial",
      "higgsfield realistic",
    ],
    creditCost: 0,
    aspectRatios: [],
    durations: [6, 10],
    sizes: ["512", "768", "1080"],
    defaultParams: { variant: "minimax-2.3", duration: 6, resolution: "768" },
    priority: 68,
    sortOrder: 268,
  },
  {
    modelId: "higgsfield/wan2_6",
    name: "Wan 2.6 Video (Higgsfield MCP)",
    description:
      "Open-weight, stylized, experimental creative through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "wan2_6",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield wan 2.6 video",
      "wan2_6",
      "wan 2.6 video",
      "higgsfield stylized",
      "higgsfield experimental",
      "higgsfield creative",
      "higgsfield open-weight",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    durations: [5, 10, 15],
    defaultParams: { quality: "720p", duration: 5 },
    priority: 69,
    sortOrder: 269,
  },
  {
    modelId: "higgsfield/seedance1_5",
    name: "Seedance 1.5 Pro (Higgsfield MCP)",
    description:
      "Reliable motion, improved quality through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "seedance1_5",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield seedance 1.5 pro",
      "seedance1_5",
      "seedance 1.5 pro",
      "higgsfield reliable",
      "higgsfield motion",
      "higgsfield quality",
      "higgsfield versatile",
    ],
    creditCost: 0,
    aspectRatios: ["auto", "16:9", "9:16", "4:3", "3:4", "1:1", "21:9"],
    durations: [4, 8, 12],
    sizes: ["480p", "720p", "1080p"],
    defaultParams: { duration: 4, resolution: "720p", generate_audio: true },
    priority: 70,
    sortOrder: 270,
  },
  {
    modelId: "higgsfield/seedance_2_0",
    name: "Seedance 2.0 (Higgsfield MCP)",
    description:
      "Reference-driven video with image/video/audio reference inputs, consistent identity, multi-SKU; optional generate_audio for native audio through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "seedance_2_0",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield seedance 2.0",
      "seedance_2_0",
      "seedance 2.0",
      "higgsfield reference",
      "higgsfield identity",
      "higgsfield consistent",
      "higgsfield product",
    ],
    creditCost: 0,
    aspectRatios: ["auto", "16:9", "9:16", "4:3", "3:4", "1:1", "21:9"],
    sizes: ["480p", "720p", "1080p", "4k"],
    defaultParams: {
      duration: 5,
      resolution: "720p",
      mode: "std",
      bitrate_mode: "standard",
      genre: "auto",
      generate_audio: true,
    },
    priority: 71,
    sortOrder: 271,
  },
  {
    modelId: "higgsfield/seedance_2_0_mini",
    name: "Seedance 2.0 Mini (Higgsfield MCP)",
    description:
      "Fast budget Seedance 2.0 variant with image/video/audio reference inputs and native audio through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "seedance_2_0_mini",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield seedance 2.0 mini",
      "seedance_2_0_mini",
      "seedance 2.0 mini",
      "higgsfield fast",
      "higgsfield budget",
      "higgsfield reference",
      "higgsfield identity",
    ],
    creditCost: 0,
    aspectRatios: ["auto", "16:9", "9:16", "4:3", "3:4", "1:1", "21:9"],
    sizes: ["480p", "720p"],
    defaultParams: {
      duration: 5,
      resolution: "720p",
      bitrate_mode: "standard",
      genre: "auto",
      generate_audio: true,
    },
    priority: 72,
    sortOrder: 272,
  },
  {
    modelId: "higgsfield/topaz_video",
    name: "Topaz (Higgsfield MCP)",
    description:
      "Topaz video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "topaz_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: ["higgsfield topaz", "topaz_video", "topaz"],
    creditCost: 0,
    aspectRatios: ["auto", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    sizes: ["1080p", "2160p"],
    defaultParams: { resolution: "1080p", frame_rate: 30, input_video_size: 0 },
    priority: 73,
    sortOrder: 273,
  },
  {
    modelId: "higgsfield/bytedance_video_upscale",
    name: "Bytedance Video Upscale (Higgsfield MCP)",
    description:
      "Bytedance Video Upscale video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "bytedance_video_upscale",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield bytedance video upscale",
      "bytedance_video_upscale",
      "bytedance video upscale",
    ],
    creditCost: 0,
    aspectRatios: [],
    sizes: ["1080p", "2k", "4k"],
    defaultParams: {
      fps: 24,
      resolution: "2k",
      preset: "common",
      model_version: "standard",
    },
    priority: 74,
    sortOrder: 274,
  },
  {
    modelId: "higgsfield/explainer_video",
    name: "Explainer Video (Higgsfield MCP)",
    description:
      "Explainer Video video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "explainer_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield explainer video",
      "explainer_video",
      "explainer video",
    ],
    creditCost: 0,
    aspectRatios: [],
    priority: 75,
    sortOrder: 275,
  },
  {
    modelId: "higgsfield/video_upscale",
    name: "Video Upscale (Higgsfield MCP)",
    description:
      "Video Upscale video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "video_upscale",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: ["higgsfield video upscale", "video_upscale", "video upscale"],
    creditCost: 0,
    aspectRatios: [],
    priority: 76,
    sortOrder: 276,
  },
  {
    modelId: "higgsfield/video_deflicker",
    name: "Video Deflicker (Higgsfield MCP)",
    description:
      "Video Deflicker video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "video_deflicker",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield video deflicker",
      "video_deflicker",
      "video deflicker",
    ],
    creditCost: 0,
    aspectRatios: [],
    priority: 77,
    sortOrder: 277,
  },
  {
    modelId: "higgsfield/kling2_6",
    name: "Kling 2.6 Video (Higgsfield MCP)",
    description:
      "Cinematic motion, advanced physics through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "kling2_6",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield kling 2.6 video",
      "kling2_6",
      "kling 2.6 video",
      "higgsfield cinematic",
      "higgsfield motion",
      "higgsfield physics",
      "higgsfield advanced",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    durations: [5, 10],
    defaultParams: { duration: 5, sound: true },
    priority: 78,
    sortOrder: 278,
  },
  {
    modelId: "higgsfield/kling3_0",
    name: "Kling v3.0 (Higgsfield MCP)",
    description:
      "Multi-shot, audio sync, motion transfer through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "kling3_0",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield kling v3.0",
      "kling3_0",
      "kling v3.0",
      "higgsfield multi-shot",
      "higgsfield audio",
      "higgsfield motion-transfer",
      "higgsfield cinematic",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    defaultParams: { duration: 5, mode: "std", sound: "on" },
    priority: 79,
    sortOrder: 279,
  },
  {
    modelId: "higgsfield/kling3_0_turbo",
    name: "Kling 3.0 Turbo (Higgsfield MCP)",
    description:
      "Fast text-to-video and single start-frame animation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "kling3_0_turbo",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield kling 3.0 turbo",
      "kling3_0_turbo",
      "kling 3.0 turbo",
      "higgsfield fast",
      "higgsfield turbo",
      "higgsfield text-to-video",
      "higgsfield image-to-video",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    sizes: ["720p", "1080p"],
    defaultParams: { resolution: "720p", duration: 5 },
    priority: 80,
    sortOrder: 280,
  },
  {
    modelId: "higgsfield/grok_video",
    name: "Grok Video (Higgsfield MCP)",
    description:
      "Text and image-to-video, audio support through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "grok_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield grok video",
      "grok_video",
      "grok video",
      "higgsfield audio",
      "higgsfield versatile",
      "higgsfield text-to-video",
      "higgsfield image-to-video",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1"],
    defaultParams: { duration: 5 },
    nativeAudioDialogue: true,
    supportsNativeAudio: true,
    priority: 81,
    sortOrder: 281,
  },
  {
    modelId: "higgsfield/gemini_omni",
    name: "Gemini Omni Flash (Higgsfield MCP)",
    description:
      "Reference-driven video with native audio and image/video reference inputs through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "gemini_omni",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield gemini omni flash",
      "gemini_omni",
      "gemini omni flash",
      "higgsfield audio",
      "higgsfield reference",
      "higgsfield image-to-video",
      "higgsfield video-to-video",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16"],
    sizes: ["720p"],
    defaultParams: { duration: 8, resolution: "720p" },
    priority: 82,
    sortOrder: 282,
  },
  {
    modelId: "higgsfield/wan2_7",
    name: "Wan 2.7 (Higgsfield MCP)",
    description:
      "Synchronized audio, character-consistent video through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "wan2_7",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield wan 2.7",
      "wan2_7",
      "wan 2.7",
      "higgsfield audio",
      "higgsfield character",
      "higgsfield consistent",
      "higgsfield sync",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
    sizes: ["720p", "1080p"],
    defaultParams: { duration: 5, resolution: "720p" },
    priority: 83,
    sortOrder: 283,
  },
  {
    modelId: "higgsfield/veo3",
    name: "Google Veo 3 (Higgsfield MCP)",
    description:
      "Reliable cinematic, broad creative range through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "veo3",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield google veo 3",
      "veo3",
      "google veo 3",
      "higgsfield cinematic",
      "higgsfield reliable",
      "higgsfield creative",
      "higgsfield audio",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16"],
    defaultParams: { variant: "veo-3-fast" },
    priority: 84,
    sortOrder: 284,
  },
  {
    modelId: "higgsfield/veo3_1",
    name: "Google Veo 3.1 (Higgsfield MCP)",
    description:
      "Ultra-realistic, top-tier cinematic quality through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "veo3_1",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield google veo 3.1",
      "veo3_1",
      "google veo 3.1",
      "higgsfield ultra-realistic",
      "higgsfield cinematic",
      "higgsfield top-tier",
      "higgsfield quality",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16"],
    durations: [4, 6, 8],
    defaultParams: { duration: 8, quality: "basic", variant: "veo-3-1-fast" },
    priority: 85,
    sortOrder: 285,
  },
  {
    modelId: "higgsfield/veo3_1_lite",
    name: "Google Veo 3.1 Lite (Higgsfield MCP)",
    description:
      "Fast, affordable, budget batch clips through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "veo3_1_lite",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield google veo 3.1 lite",
      "veo3_1_lite",
      "google veo 3.1 lite",
      "higgsfield fast",
      "higgsfield budget",
      "higgsfield affordable",
      "higgsfield batch",
    ],
    creditCost: 0,
    aspectRatios: ["16:9", "9:16", "auto"],
    durations: [4, 6, 8],
    defaultParams: { duration: 8, generate_audio: false },
    priority: 86,
    sortOrder: 286,
  },
  {
    modelId: "higgsfield/sam_3_video",
    name: "Remove Background (Higgsfield MCP)",
    description:
      "Remove Background video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "sam_3_video",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: [
      "higgsfield remove background",
      "sam_3_video",
      "remove background",
    ],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: { apply_mask: true },
    priority: 87,
    sortOrder: 287,
  },
  {
    modelId: "higgsfield/llm_text",
    name: "LLM Generation (Higgsfield MCP)",
    description:
      "LLM Generation video generation through Higgsfield MCP provider-account credits.",
    modelType: "video",
    provider: "higgsfield",
    providerModelId: "llm_text",
    toolName: "generate_video",
    argumentShape: "higgsfield.generate_video",
    aliases: ["higgsfield llm generation", "llm_text", "llm generation"],
    creditCost: 0,
    aspectRatios: [],
    defaultParams: { user_prompt: "", system_prompt: "" },
    priority: 88,
    sortOrder: 288,
  },
];

export function buildHiggsfieldCatalogMediaModels(): McpMediaModelSeed[] {
  return HIGGSFIELD_CATALOG_MEDIA_MODELS;
}

const MCP_MEDIA_MODELS: McpMediaModelSeed[] = [
  ...HIGGSFIELD_CATALOG_MEDIA_MODELS,
  {
    modelId: "magnific-mcp/gpt-2",
    name: "GPT 2 (Magnific MCP)",
    description:
      "Magnific MCP image generation through the connected user's Magnific account.",
    modelType: "image",
    provider: "magnific",
    providerModelId: "gpt-2",
    toolName: "images_generate",
    argumentShape: "magnific.images_generate",
    aliases: ["magnific mcp", "gpt-2"],
    creditCost: 0,
    aspectRatios: ["auto", ...IMAGE_ASPECT_RATIOS, "2:1", "3:1", "21:9"],
    sizes: ["1k", "2k", "4k"],
    priority: 28,
    sortOrder: 228,
  },
  {
    modelId: "magnific-mcp/imagen-nano-banana-2-flash",
    name: "Nano Banana 2 (Magnific MCP)",
    description:
      "Nano Banana 2 / Gemini Flash image generation through Magnific MCP provider-account credits.",
    modelType: "image",
    provider: "magnific",
    providerModelId: "imagen-nano-banana-2-flash",
    toolName: "images_generate",
    argumentShape: "magnific.images_generate",
    aliases: [
      "magnific nano banana 2",
      "imagen-nano-banana-2-flash",
      "nano banana 2",
    ],
    creditCost: 0,
    aspectRatios: ["auto", ...GOOGLE_IMAGE_ASPECT_RATIOS],
    sizes: ["1k", "2k", "4k"],
    priority: 29,
    sortOrder: 229,
  },
  {
    modelId: "magnific-mcp/imagen-nano-banana-2",
    name: "Nano Banana Pro (Magnific MCP)",
    description:
      "Nano Banana Pro image generation through Magnific MCP provider-account credits.",
    modelType: "image",
    provider: "magnific",
    providerModelId: "imagen-nano-banana-2",
    toolName: "images_generate",
    argumentShape: "magnific.images_generate",
    aliases: [
      "magnific nano banana pro",
      "imagen-nano-banana-2",
      "nano banana pro",
    ],
    creditCost: 0,
    aspectRatios: ["auto", ...GOOGLE_IMAGE_ASPECT_RATIOS],
    sizes: ["1k", "2k", "4k"],
    priority: 30,
    sortOrder: 230,
  },
  {
    modelId: "magnific-mcp/bytedance-seedance-pro-2.0",
    name: "Seedance Pro 2.0 (Magnific MCP)",
    description:
      "Magnific MCP video generation through provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "bytedance-seedance-pro-2.0",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: ["magnific seedance pro", "bytedance-seedance-pro-2.0"],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8],
    priority: 31,
    sortOrder: 231,
  },
  {
    modelId: "magnific-mcp/kling-v3-pro",
    name: "Kling 3 Pro (Magnific MCP)",
    description:
      "Kling 3.0 Pro video generation through Magnific MCP provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "kling-v3-pro",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: ["magnific kling 3", "kling-v3-pro", "kling 3.0"],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8, 10],
    sizes: ["720p", "1080p"],
    priority: 32,
    sortOrder: 232,
  },
  {
    modelId: "magnific-mcp/kling-v3-omni-pro",
    name: "Kling 3 Omni Pro (Magnific MCP)",
    description:
      "Kling 3.0 Omni Pro video generation through Magnific MCP provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "kling-v3-omni-pro",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: ["magnific kling 3 omni", "kling-v3-omni-pro", "kling 3.0 omni"],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8, 10],
    sizes: ["720p", "1080p"],
    priority: 33,
    sortOrder: 233,
  },
  {
    modelId: "magnific-mcp/veo-3-1-text-to-video",
    name: "Veo 3.1 Pro (Magnific MCP)",
    description:
      "Google Veo 3.1 high-quality text-to-video through Magnific MCP provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "veo-3-1-text-to-video",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: ["magnific veo 3.1 pro", "veo-3-1-text-to-video", "veo 3.1"],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8],
    sizes: ["720p", "1080p"],
    priority: 34,
    sortOrder: 234,
  },
  {
    modelId: "magnific-mcp/veo-3-1-text-to-video-fast",
    name: "Veo 3.1 Lite/Fast (Magnific MCP)",
    description:
      "Google Veo 3.1 fast text-to-video through Magnific MCP provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "veo-3-1-text-to-video-fast",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: [
      "magnific veo 3.1 lite",
      "veo-3-1-text-to-video-fast",
      "veo 3.1 fast",
    ],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8],
    sizes: ["720p", "1080p"],
    priority: 35,
    sortOrder: 235,
  },
  {
    modelId: "magnific-mcp/wan-v2-7-text-to-video",
    name: "Wan 2.7 Text to Video (Magnific MCP)",
    description:
      "Wan 2.7 text-to-video through Magnific MCP provider-account credits.",
    modelType: "video",
    provider: "magnific",
    providerModelId: "wan-v2-7-text-to-video",
    toolName: "video_generate",
    argumentShape: "magnific.video_generate",
    aliases: ["magnific wan 2.7", "wan-v2-7-text-to-video", "wan 2.7"],
    creditCost: 0,
    aspectRatios: VIDEO_ASPECT_RATIOS,
    durations: [4, 6, 8],
    sizes: ["720p", "1080p"],
    priority: 36,
    sortOrder: 236,
  },
];

export function buildMcpMediaModelConfigJson(
  model: McpMediaModelSeed,
): Record<string, unknown> {
  return {
    transport: "mcp",
    provider: model.provider,
    providerModelId: model.providerModelId,
    generateType:
      model.modelType === "video" ? "image-to-video" : "reference-to-image",
    supportsReferenceImages: true,
    referenceInputs: {
      image: true,
      video: model.modelType === "video",
    },
    referenceImageLimit: model.referenceImageLimit ?? 5,
    ...(model.nativeAudioDialogue === true ? { hasAudio: true } : {}),
    ...(model.supportsNativeAudio === true ? { nativeAudio: true } : {}),
    mcp: {
      providerKey: model.provider,
      providerModelId: model.providerModelId,
      toolName: model.toolName,
      argumentShape: model.argumentShape,
      defaultParams: model.defaultParams ?? {},
    },
    inputFields: [
      ...(model.aspectRatios.length
        ? [
            {
              key: "aspect_ratio",
              label: "Aspect Ratio",
              type: "select",
              options: model.aspectRatios.map(value => ({
                value,
                label: value,
              })),
              default: model.aspectRatios.includes("1:1")
                ? "1:1"
                : model.aspectRatios[0],
            },
          ]
        : []),
      ...(model.modelType === "video" && model.durations?.length
        ? [
            {
              key: "duration",
              label: "Duration",
              type: "select",
              options: model.durations.map(value => ({
                value: String(value),
                label: `${value}s`,
              })),
              default: String(model.durations[0]),
            },
          ]
        : []),
      ...(model.sizes?.length
        ? [
            {
              key: "resolution",
              label: "Resolution",
              type: "select",
              options: model.sizes.map(value => ({ value, label: value })),
              default: model.sizes[0],
            },
          ]
        : []),
      {
        key: "reference_image_urls",
        label: "Reference Images",
        type: "image_urls",
        syncWith: "reference_images",
        maxItems: model.referenceImageLimit ?? 5,
        includeInPayload: false,
      },
    ],
    pricing: {
      formula: "provider_account",
      defaultCredits: 0,
      note: "Uses the connected provider account's credits; SmartSpecPro credits are not deducted.",
    },
    readiness: "mcp-verified",
    adminVisible: true,
  };
}

export async function seedMcpProviderMediaModels(
  options: { dryRun?: boolean } = {}
): Promise<void> {
  console.log("Seeding MCP provider media models...\n");
  for (const model of MCP_MEDIA_MODELS) {
    console.log(
      `  ${options.dryRun ? "dry-run " : ""}${model.modelId} -> ${model.provider}:${model.providerModelId}`
    );
  }
  if (options.dryRun) return;

  const sql = postgres(DATABASE_URL);
  try {
    for (const model of MCP_MEDIA_MODELS) {
      await sql`
        INSERT INTO media_models (
          "modelId", name, description, "modelType", provider,
          aliases, "creditCost", "aspectRatios", durations, sizes,
          priority, "sortOrder", "configJson", "isEnabled"
        ) VALUES (
          ${model.modelId},
          ${model.name},
          ${model.description},
          ${model.modelType},
          ${model.provider},
          ${sql.json(model.aliases)},
          ${model.creditCost},
          ${sql.json(model.aspectRatios)},
          ${sql.json(model.durations ?? [])},
          ${sql.json(model.sizes ?? [])},
          ${model.priority},
          ${model.sortOrder},
          ${sql.json(buildMcpMediaModelConfigJson(model))},
          true
        )
        ON CONFLICT ("modelId") DO UPDATE SET
          name = EXCLUDED.name,
          description = EXCLUDED.description,
          "modelType" = EXCLUDED."modelType",
          provider = EXCLUDED.provider,
          aliases = EXCLUDED.aliases,
          "aspectRatios" = EXCLUDED."aspectRatios",
          durations = EXCLUDED.durations,
          sizes = EXCLUDED.sizes,
          priority = EXCLUDED.priority,
          "sortOrder" = EXCLUDED."sortOrder",
          "configJson" = EXCLUDED."configJson",
          "isEnabled" = media_models."isEnabled"
      `;
    }
    for (const deprecated of DEPRECATED_HIGGSFIELD_MCP_MODELS) {
      await sql`
        UPDATE media_models
        SET
          "isEnabled" = false,
          "configJson" = COALESCE("configJson"::jsonb, '{}'::jsonb)
            || ${sql.json({
              deprecated: true,
              disabledReason: "higgsfield_catalog_refresh",
            })}::jsonb
            || jsonb_build_object(
              'mcpUnavailableReason', ${deprecated.reason}::text,
              'replacementModelId', ${deprecated.replacementModelId ?? null}::text
            ),
          "updatedAt" = now()
        WHERE "modelId" = ${deprecated.modelId}
      `;
    }
    console.log(
      `\nUpserted ${MCP_MEDIA_MODELS.length} MCP media model records.`
    );
    console.log(
      `Disabled ${DEPRECATED_HIGGSFIELD_MCP_MODELS.length} deprecated Higgsfield MCP model records.`
    );
  } finally {
    await sql.end();
  }
}

const isMainModule = process.argv[1]
  ? resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  : false;

if (isMainModule) {
  void seedMcpProviderMediaModels({
    dryRun: process.argv.includes("--dry-run"),
  });
}
