/**
 * {{pascalCase entity.name}} Types
 */

/**
 * {{pascalCase entity.name}} entity
 */
export interface {{pascalCase entity.name}} {
{{#each entity.fields}}
  {{this.name}}: {{toTypeScriptType this.type}};
{{/each}}
}

/**
 * Input for creating a {{entity.name}}
 */
export interface {{pascalCase entity.name}}CreateInput {
{{#each entity.fields}}
{{#unless isAutoGenerated}}
{{#unless isPrimaryKey}}
  {{this.name}}{{#unless (isRequired this.constraints)}}?{{/unless}}: {{toTypeScriptType this.type}};
{{/unless}}
{{/unless}}
{{/each}}
}

/**
 * Input for updating a {{entity.name}}
 */
export interface {{pascalCase entity.name}}UpdateInput {
{{#each entity.fields}}
{{#unless isAutoGenerated}}
{{#unless isPrimaryKey}}
  {{this.name}}?: {{toTypeScriptType this.type}};
{{/unless}}
{{/unless}}
{{/each}}
}

/**
 * Options for finding {{pluralize entity.name}}
 */
export interface {{pascalCase entity.name}}FindAllOptions {
  limit: number;
  offset: number;
  userId: string;
  // Add filters here based on your needs
  [key: string]: any;
}

/**
 * Result of finding {{pluralize entity.name}}
 */
export interface {{pascalCase entity.name}}FindAllResult {
  data: {{pascalCase entity.name}}[];
  meta: {
    total: number;
    limit: number;
    offset: number;
  };
}
