import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../../db", () => ({
  getDb: vi.fn().mockResolvedValue(null),
}));

vi.mock("../workpackPersistence", () => ({
  getWorkpackDetail: vi.fn(async (workpackId: string) => ({
    workpack: {
      id: workpackId,
      tenantId: "tenant-1",
      title: "Pack",
      description: "",
      goal: "Goal",
      domainPack: "support_ops",
      lifecycleState: "needs_review",
      autonomyMode: "supervised",
      promotionState: "unpromoted",
      currentVersionId: "wpv_1",
      caseSourceIds: [],
      policyProfile: {},
      runtimePreferenceHints: ["workflow"],
      createdAt: "2026-04-10T00:00:00.000Z",
      updatedAt: "2026-04-10T00:00:00.000Z",
    },
    version: {
      id: "wpv_1",
      workpackId,
      versionNumber: 1,
      playbook: {
        id: "playbook_1",
        workpackId,
        summary: "Summary",
        extractedFields: [],
        confidenceByField: {},
        actors: [],
        targetSystems: [],
        triggerConditions: [],
        exceptionModes: [],
        policyConstraints: [],
        dataSensitivity: [],
        connectorRequirements: [],
        evaluationCriteria: [],
        clarificationQueue: [],
        draftNotes: [],
        createdAt: "2026-04-10T00:00:00.000Z",
        updatedAt: "2026-04-10T00:00:00.000Z",
      },
      executionPlan: null,
      connectorMaps: [{ connectorFamily: "crm", validationStatus: "validated" }],
      connectorIntrospections: [],
      fixtureCatalog: [],
      compilerMetadata: {},
      publishedAt: "2026-04-10T00:00:00.000Z",
      createdAt: "2026-04-10T00:00:00.000Z",
    },
    caseSources: [],
    playbook: {
      id: "playbook_1",
      workpackId,
      summary: "Summary",
      extractedFields: [],
      confidenceByField: {},
      actors: [],
      targetSystems: [],
      triggerConditions: [],
      exceptionModes: [],
      policyConstraints: [],
      dataSensitivity: [],
      connectorRequirements: [],
      evaluationCriteria: [],
      clarificationQueue: [],
      draftNotes: [],
      createdAt: "2026-04-10T00:00:00.000Z",
      updatedAt: "2026-04-10T00:00:00.000Z",
    },
    runs: [{
      id: "wpr_1",
      workpackId,
      versionId: "wpv_1",
      trigger: "manual",
      status: "succeeded",
      plannedSteps: [],
      actualSteps: [{ runtimePath: "workflow" }],
      approvals: [],
      artifactRefs: [],
      connectorUsageSummary: [],
      notes: "",
      startedAt: "2026-04-10T00:00:00.000Z",
      endedAt: "2026-04-10T00:10:00.000Z",
    }],
    simulations: [],
    exceptions: [],
    benchmarks: [],
    promotionRecords: [],
    improvementProposals: [],
    telemetryEvents: [],
    metricSnapshots: [],
    incidents: [],
    schedules: [],
  })),
}));

import { listRoleTelemetrySnapshots } from "../roleTelemetryService";
import { resetRoleStore, saveRoleAgent, saveRoleContract, saveRoleMetricSnapshot, saveRoleRoutineRun } from "../rolePersistence";

describe("roleTelemetryService", () => {
  beforeEach(async () => {
    await resetRoleStore();
  });

  it("supports telemetry filtering and preserves connector/runtime slices on cached snapshots", async () => {
    await saveRoleAgent({
      id: "role_1",
      tenantId: "tenant-1",
      blueprintId: null,
      name: "Sales role",
      departmentLabel: "Sales",
      lifecycleState: "active",
      healthState: "healthy",
      currentAutonomyTier: "guided",
      activeContractId: "rc_1",
      bridgeTeamId: null,
      roomId: null,
      ownerUserId: 1,
      ownershipContext: {},
      tags: [],
      lastCheckpointAt: null,
      lastRoutineRunId: null,
      createdAt: "2026-04-10T00:00:00.000Z",
      updatedAt: "2026-04-10T00:00:00.000Z",
    });
    await saveRoleContract({
      id: "rc_1",
      tenantId: "tenant-1",
      roleId: "role_1",
      versionNumber: 1,
      status: "active",
      missionStatement: "Handle sales ops",
      kpiTargets: [],
      authorityEnvelope: {
        autonomyTier: "guided",
        connectorFamilies: ["crm"],
        sideEffectCeiling: "bounded_write",
        monthlyBudgetLimit: 100,
        regulatedActionLabels: [],
        requiresApprovalFor: [],
        visibilityDefaults: ["owner_full", "delegated_minimum", "redacted_summary"],
      },
      workpackBindingIds: [],
      visibilityMatrix: {},
      notes: "",
      activatedAt: "2026-04-10T00:00:00.000Z",
      supersededByContractId: null,
      createdAt: "2026-04-10T00:00:00.000Z",
    });
    await saveRoleRoutineRun({
      id: "rrun_1",
      tenantId: "tenant-1",
      roleId: "role_1",
      routineId: "routine_1",
      contractId: "rc_1",
      status: "succeeded",
      triggerSource: "manual",
      idempotencyKey: "tenant-1:rrun_1",
      selectedWorkpackFamily: "wp_crm",
      resolvedWorkpackVersionId: "wpv_1",
      linkedWorkpackRunIds: ["wpr_1"],
      checkpointId: null,
      recoveryState: "fresh",
      resolutionPolicy: "follow_latest_ready_in_family",
      previousResolvedVersionId: null,
      rollbackBaselineVersionId: null,
      partitionKey: null,
      blockerCodes: [],
      currentObjectiveSummary: "Run sales ops",
      approvalRequestIds: [],
      startedAt: "2026-04-10T00:00:00.000Z",
      endedAt: "2026-04-10T00:10:00.000Z",
      createdAt: "2026-04-10T00:00:00.000Z",
      updatedAt: "2026-04-10T00:10:00.000Z",
    });
    await saveRoleMetricSnapshot({
      id: "metric_1",
      tenantId: "tenant-1",
      roleId: "role_1",
      routineId: "routine_1",
      autonomyTier: "guided",
      healthState: "healthy",
      backlogDepth: 0,
      backlogAgeMinutes: 0,
      throughput: 1,
      interventionRate: 0,
      exceptionRate: 0,
      slaHitRate: 1,
      qualityScore: 1,
      replayPassRate: 1,
      improvementVelocity: 0,
      checkpointFreshnessMinutes: 5,
      checkpointFreshnessTier: "fresh",
      recoveryChurn: 0,
      budgetBurn: 0,
      blockerCodes: [],
      generatedAt: "2026-04-10T00:10:00.000Z",
    });

    const snapshots = await listRoleTelemetrySnapshots("tenant-1", {
      departmentLabel: "Sales",
      connectorFamily: "crm",
      runtimeFamily: "workflow",
    });

    expect(snapshots).toHaveLength(1);
    expect(snapshots[0]?.connectorFamilies).toContain("crm");
    expect(snapshots[0]?.runtimeFamilies).toContain("workflow");
  });
});
