export const SMARTAIHUB_COMPANION_NAME = "SmartAIHub Companion";
export const SMARTAIHUB_COMPANION_TOKEN_MESSAGE = "SMARTAIHUB_COMPANION_TOKEN";
export const LEGACY_MARKETPLACE_EXTENSION_TOKEN_MESSAGE = "SMARTAIHUB_MARKETPLACE_EXTENSION_TOKEN";

export function isSupportedCompanionTokenMessage(value: unknown): boolean {
  return value === SMARTAIHUB_COMPANION_TOKEN_MESSAGE
    || value === LEGACY_MARKETPLACE_EXTENSION_TOKEN_MESSAGE;
}
