"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HYPERFRAMES_FINAL_COMPOSITE_SHOT_MAX_SEC = exports.HYPERFRAMES_FINAL_COMPOSITE_MAX_SEC = exports.HYPERFRAMES_FINAL_RENDER_PROMPT_MAX_CHARS = void 0;
exports.HYPERFRAMES_FINAL_RENDER_PROMPT_MAX_CHARS = 12000;
exports.HYPERFRAMES_FINAL_COMPOSITE_MAX_SEC = 300;
exports.HYPERFRAMES_FINAL_COMPOSITE_SHOT_MAX_SEC = 30;
