/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/stone/stoneTheme.ts
 * Command: astryx theme build client/src/themes/stone/stoneTheme.ts
 * Generated: 2026-07-04T02:32:50.884Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/ProgressbarFill' {
  interface XDSProgressbarFillVariantMap {
    'accent': true;
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/FieldStatus' {
  interface XDSFieldStatusTypeMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/TextInput' {
  interface XDSTextInputStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/NumberInput' {
  interface XDSNumberInputStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/DateInput' {
  interface XDSDateInputStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/TimeInput' {
  interface XDSTimeInputStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/MultiSelector' {
  interface XDSMultiSelectorStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/Typeahead' {
  interface XDSTypeaheadStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/Tokenizer' {
  interface XDSTokenizerStatusMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}
