/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/stone/stoneTheme.ts
 * Command: astryx theme build client/src/themes/stone/stoneTheme.ts
 * Generated: 2026-07-04T02:32:50.873Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const stoneIconRegistry: IconRegistry;
export declare const stoneTheme: DefinedTheme;
