/**
 * AST Types for API Specification
 * Represents the parsed structure of an API spec
 */

/**
 * Field type for entity fields
 */
export type FieldType = 
  | 'string'
  | 'number'
  | 'integer'
  | 'boolean'
  | 'datetime'
  | 'date'
  | 'time'
  | 'uuid'
  | 'json'
  | 'array';

/**
 * Field constraint
 */
export interface FieldConstraint {
  type: 'required' | 'unique' | 'min' | 'max' | 'pattern' | 'default' | 'enum';
  value?: any;
}

/**
 * Entity field definition
 */
export interface Field {
  name: string;
  type: FieldType;
  constraints: FieldConstraint[];
  description?: string;
  isPrimaryKey?: boolean;
  isForeignKey?: boolean;
  foreignKeyTo?: string; // Entity name
  isAutoGenerated?: boolean;
}

/**
 * Entity relationship
 */
export interface Relationship {
  type: 'one-to-one' | 'one-to-many' | 'many-to-one' | 'many-to-many';
  entity: string; // Related entity name
  foreignKey?: string;
  description?: string;
}

/**
 * Entity index
 */
export interface Index {
  fields: string[];
  unique?: boolean;
  name?: string;
}

/**
 * Entity definition
 */
export interface Entity {
  name: string;
  fields: Field[];
  relationships: Relationship[];
  indexes: Index[];
  description?: string;
}

/**
 * HTTP method
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/**
 * Parameter location
 */
export type ParameterLocation = 'query' | 'path' | 'body' | 'header';

/**
 * Parameter definition
 */
export interface Parameter {
  name: string;
  location: ParameterLocation;
  type: FieldType;
  required: boolean;
  description?: string;
  default?: any;
  constraints?: FieldConstraint[];
}

/**
 * Response definition
 */
export interface Response {
  statusCode: number;
  description: string;
  schema?: any; // JSON schema or entity reference
}

/**
 * Error response
 */
export interface ErrorResponse {
  statusCode: number;
  code: string;
  message: string;
}

/**
 * Endpoint definition
 */
export interface Endpoint {
  method: HttpMethod;
  path: string;
  description: string;
  requiresAuth: boolean;
  authorizationRules?: string[];
  parameters: Parameter[];
  requestBody?: any; // JSON schema or entity reference
  responses: Response[];
  errors: ErrorResponse[];
  tags?: string[];
}

/**
 * Business rule
 */
export interface BusinessRule {
  type: 'validation' | 'authorization' | 'business-logic';
  description: string;
  appliesTo?: string[]; // Entity or endpoint names
}

/**
 * Rate limit configuration
 */
export interface RateLimit {
  requests: number;
  window: string; // e.g., "1 minute", "1 hour"
  scope: 'global' | 'per-user' | 'per-ip';
}

/**
 * API Specification (Root AST)
 */
export interface APISpec {
  name: string;
  version: string;
  description?: string;
  entities: Entity[];
  endpoints: Endpoint[];
  businessRules: BusinessRule[];
  rateLimit?: RateLimit;
  metadata?: Record<string, any>;
}

/**
 * Complexity analysis result
 */
export interface ComplexityAnalysis {
  overall: 'low' | 'medium' | 'high';
  templatePercentage: number; // 0-100
  aiPercentage: number; // 0-100
  endpoints: {
    [path: string]: {
      complexity: 'low' | 'medium' | 'high';
      useTemplate: boolean;
      useAI: boolean;
      reasons: string[];
    };
  };
}
