#!/bin/bash
# SmartSpec Sandbox - Create Workspace Script
#
# Usage:
#   ./create-workspace.sh <workspace-name> [repository-url] [image]
#
# Examples:
#   ./create-workspace.sh my-project
#   ./create-workspace.sh my-project https://github.com/user/repo
#   ./create-workspace.sh my-project https://github.com/user/repo nodejs

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================
# Parse Arguments
# ============================================
WORKSPACE_NAME="$1"
REPO_URL="$2"
IMAGE_TYPE="${3:-nodejs}"

if [ -z "$WORKSPACE_NAME" ]; then
    log_error "Usage: $0 <workspace-name> [repository-url] [image-type]"
    echo ""
    echo "Image types: nodejs, python, golang, rust, fullstack"
    exit 1
fi

# Validate workspace name
if [[ ! "$WORKSPACE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    log_error "Workspace name can only contain letters, numbers, hyphens, and underscores"
    exit 1
fi

# ============================================
# Setup Paths
# ============================================
SMARTSPEC_HOME="${HOME}/SmartSpec"
WORKSPACE_PATH="${SMARTSPEC_HOME}/workspaces/${WORKSPACE_NAME}"

if [ -d "$WORKSPACE_PATH" ]; then
    log_error "Workspace '${WORKSPACE_NAME}' already exists at ${WORKSPACE_PATH}"
    exit 1
fi

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║       SmartSpec Sandbox - Create Workspace               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

log_info "Creating workspace: ${WORKSPACE_NAME}"
log_info "Path: ${WORKSPACE_PATH}"
log_info "Image: smartspec/sandbox-${IMAGE_TYPE}:latest"

# ============================================
# Create Workspace Directory
# ============================================
log_info "Creating workspace directory..."

mkdir -p "${WORKSPACE_PATH}"
mkdir -p "${WORKSPACE_PATH}/.workspace"

# ============================================
# Clone or Initialize Repository
# ============================================
if [ -n "$REPO_URL" ]; then
    log_info "Cloning repository: ${REPO_URL}"
    git clone "$REPO_URL" "${WORKSPACE_PATH}/project"
else
    log_info "Initializing empty repository..."
    mkdir -p "${WORKSPACE_PATH}/project"
    cd "${WORKSPACE_PATH}/project"
    git init
    
    # Create initial files
    echo "# ${WORKSPACE_NAME}" > README.md
    echo "node_modules/" > .gitignore
    echo "__pycache__/" >> .gitignore
    echo ".env" >> .gitignore
    echo "dist/" >> .gitignore
    echo "build/" >> .gitignore
    
    git add .
    git commit -m "Initial commit"
fi

# ============================================
# Create Workspace Configuration
# ============================================
log_info "Creating workspace configuration..."

CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "${WORKSPACE_PATH}/.workspace/config.json" << EOF
{
  "version": "1.0",
  "workspace": {
    "name": "${WORKSPACE_NAME}",
    "path": "${WORKSPACE_PATH}",
    "repository": ${REPO_URL:+"\"$REPO_URL\""}${REPO_URL:-null},
    "created_at": "${CREATED_AT}"
  },
  "defaults": {
    "image": "smartspec/sandbox-${IMAGE_TYPE}:latest",
    "memory_limit": "2g",
    "cpu_limit": 2,
    "auto_start": true
  },
  "scripts": {
    "install": "npm install",
    "dev": "npm run dev",
    "build": "npm run build",
    "test": "npm test"
  },
  "port_mapping": {
    "web": 3000,
    "api": 8000,
    "debug": 9229
  }
}
EOF

# Create branches configuration
cat > "${WORKSPACE_PATH}/.workspace/branches.json" << EOF
{
  "project": "${WORKSPACE_NAME}",
  "repository": ${REPO_URL:+"\"$REPO_URL\""}${REPO_URL:-null},
  "branches": {
    "main": {
      "container_id": null,
      "container_name": null,
      "image": "smartspec/sandbox-${IMAGE_TYPE}:latest",
      "ports": [],
      "status": "none",
      "parent_branch": null,
      "created_at": "${CREATED_AT}",
      "last_active": "${CREATED_AT}"
    }
  }
}
EOF

# ============================================
# Create docker-compose for this workspace
# ============================================
log_info "Creating docker-compose configuration..."

cat > "${WORKSPACE_PATH}/docker-compose.yml" << EOF
# Docker Compose for workspace: ${WORKSPACE_NAME}
# Generated by SmartSpec Sandbox

version: '3.8'

services:
  ${WORKSPACE_NAME}:
    image: smartspec/sandbox-${IMAGE_TYPE}:latest
    container_name: smartspec-${WORKSPACE_NAME}-main
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      # Project files - PERSISTENT
      - ./project:/workspace/project:rw
      
      # Package caches - SHARED
      - smartspec-npm-cache:/home/sandbox/.npm
      - smartspec-pnpm-cache:/home/sandbox/.local/share/pnpm
      - smartspec-pip-cache:/home/sandbox/.cache/pip
      - smartspec-go-cache:/home/sandbox/go
      - smartspec-cargo-cache:/home/sandbox/.cargo
    ports:
      - "3000:3000"
      - "8000:8000"
      - "9229:9229"
    working_dir: /workspace/project
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
      - WORKSPACE_NAME=${WORKSPACE_NAME}
      - BRANCH_NAME=main
    networks:
      - smartspec-network

volumes:
  smartspec-npm-cache:
    external: true
  smartspec-pnpm-cache:
    external: true
  smartspec-pip-cache:
    external: true
  smartspec-go-cache:
    external: true
  smartspec-cargo-cache:
    external: true

networks:
  smartspec-network:
    external: true
EOF

# ============================================
# Update Global Registry
# ============================================
log_info "Updating workspace registry..."

REGISTRY_FILE="${SMARTSPEC_HOME}/config/workspaces.json"

if [ -f "$REGISTRY_FILE" ]; then
    # Add to existing registry using jq if available, otherwise use simple append
    if command -v jq &> /dev/null; then
        jq --arg name "$WORKSPACE_NAME" --arg path "$WORKSPACE_PATH" \
           '. + {($name): $path}' "$REGISTRY_FILE" > "${REGISTRY_FILE}.tmp" && \
           mv "${REGISTRY_FILE}.tmp" "$REGISTRY_FILE"
    else
        # Simple JSON manipulation without jq
        sed -i 's/}$//' "$REGISTRY_FILE"
        if [ "$(cat $REGISTRY_FILE | tr -d '[:space:]')" != "{" ]; then
            echo "," >> "$REGISTRY_FILE"
        fi
        echo "  \"${WORKSPACE_NAME}\": \"${WORKSPACE_PATH}\"" >> "$REGISTRY_FILE"
        echo "}" >> "$REGISTRY_FILE"
    fi
fi

# ============================================
# Summary
# ============================================
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              Workspace Created Successfully!             ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

log_success "Workspace: ${WORKSPACE_NAME}"
log_success "Path: ${WORKSPACE_PATH}"
log_success "Image: smartspec/sandbox-${IMAGE_TYPE}:latest"
echo ""

log_info "To start the workspace container:"
echo "  cd ${WORKSPACE_PATH}"
echo "  docker-compose up -d"
echo ""

log_info "To enter the container:"
echo "  docker exec -it smartspec-${WORKSPACE_NAME}-main bash"
echo ""

log_info "To create a new branch with its own container:"
echo "  ./create-branch.sh ${WORKSPACE_NAME} feature/my-feature"
echo ""
