import { TRPCError } from "@trpc/server";
import { z } from "zod";

import { protectedProcedure, router } from "../_core/trpc";
import { assertBillingActionAuthorized } from "../services/billing/authorization";
import {
  classifyInvoiceStream,
  getActiveTaxPolicy,
  previewInvoiceNumber,
  reserveNextInvoiceNumber,
} from "../services/billing/invoiceDomain";
import { listInvoiceDocuments, resolveInvoiceDocumentAccess } from "../services/billing/documentAccess";
import { replacePaidInvoice, syncInvoiceHeader } from "../services/billing/documentOperations";
import { renderInvoiceDocument } from "../services/billing/documentRendering";
import { assertBillingFeatureEnabled } from "../services/billing/featureFlags";
import {
  applyMissingCreditsForInvoice,
  applyMissingSubscriptionRenewalForInvoice,
  cancelInvoiceForAdmin,
  cancelStalePaymentAttempt,
  createSupportRecoveryCase,
  manualMarkInvoicePaid,
  regenerateInvoicePaymentAttempt,
  reopenInvoiceForAdmin,
  requestInvoiceReconciliation,
  resolveSupportRecoveryEvidenceAccess,
  reverseWrongDowngrade,
  uploadSupportRecoveryEvidence,
} from "../services/billing/recovery";
import {
  listInvoiceNotificationDispatches,
  sendInvoiceNotification,
} from "../services/billing/notifications";
import { createOrGetInvoiceForBillingCycle } from "../services/billing/renewalService";
import {
  fallbackInvoiceToManualCollection,
  forceRetryRenewalAttempt,
  listRenewalAttemptsForSubscription,
  pauseRenewalDunning,
  resumeRenewalDunning,
} from "../services/billing/autoRenew";
import {
  getAdminVisibleInvoice,
  getSellerProfileForTenant,
  listAdminInvoices,
  listInvoiceAuditLogsForAdmin,
  listInvoicePaymentsForAdmin,
  listInvoiceReconciliationRunsForAdmin,
  listInvoiceWebhookEventsForAdmin,
  listSellerProfileRevisionsForTenant,
  listSupportRecoveryCases,
  listTaxPoliciesForTenant,
  upsertSellerProfileForTenant,
  upsertTaxPolicyForTenant,
} from "../services/billing/profiles";
import {
  disableAutoRenewForSubscriptionAdmin,
  getSubscriptionPaymentSettingsForAdmin,
  listPaymentMethodsForAdmin,
  revokePaymentMethodForAdmin,
} from "../services/billing/paymentMethods";
import { assertBillingStepUpIfRequired } from "../services/billing/stepUp";
import { getBillingPhase2Metrics } from "../services/billing/phase2Metrics";
import {
  getBeamProviderAdminSettings,
  testBeamProviderAdminSettings,
  updateBeamProviderAdminSettings,
} from "../services/billing/providerConfig";
import {
  getBillingRuntimeSettingsAdmin,
  updateBillingRuntimeSettings,
} from "../services/billing/runtimeConfig";
import { resolveTenantIdVarchar } from "../services/tenantContext";

const tenantIdSchema = z
  .union([z.string(), z.number()])
  .transform((value) => String(value).trim())
  .pipe(z.string().min(1))
  .optional()
  .nullable();

const nullableTrimmedString = z.string().trim().max(512).optional().nullable();

const sellerProfileSchema = z.object({
  tenantId: tenantIdSchema,
  entityNameTh: nullableTrimmedString,
  entityNameEn: nullableTrimmedString,
  taxId: nullableTrimmedString,
  phone: nullableTrimmedString,
  email: z.string().trim().email().optional().nullable().or(z.literal("").transform(() => null)),
  addressLine1: nullableTrimmedString,
  addressLine2: nullableTrimmedString,
  subdistrict: nullableTrimmedString,
  district: nullableTrimmedString,
  province: nullableTrimmedString,
  postalCode: nullableTrimmedString,
  country: nullableTrimmedString,
  signerName: nullableTrimmedString,
  signerTitle: nullableTrimmedString,
  branchType: nullableTrimmedString,
  footerNoteTh: z.string().trim().max(2000).optional().nullable(),
  footerNoteEn: z.string().trim().max(2000).optional().nullable(),
  autoGeneratedDocumentNoteTh: z.string().trim().max(2000).optional().nullable(),
  autoGeneratedDocumentNoteEn: z.string().trim().max(2000).optional().nullable(),
  logoUrl: nullableTrimmedString,
});

const taxPolicySchema = z.object({
  tenantId: tenantIdSchema,
  stream: z.enum(["domestic", "international"]),
  taxName: z.string().trim().min(1).max(128),
  taxRatePercent: z.string().trim().regex(/^\d+(\.\d{1,4})?$/),
  isEnabled: z.boolean(),
  effectiveFrom: z.date(),
  effectiveTo: z.date().optional().nullable(),
  roundingPolicy: z.string().trim().max(64).optional().nullable(),
});

const beamProviderSettingsSchema = z.object({
  apiBaseUrl: z.string().trim().max(1024).optional(),
  apiKey: z.string().trim().max(2048).optional(),
  chargesPath: z.string().trim().max(256).optional(),
  paymentLinksPath: z.string().trim().max(256).optional(),
  chargeStatusPathTemplate: z.string().trim().max(256).optional(),
  paymentLinkStatusPathTemplate: z.string().trim().max(256).optional(),
  cancelPathSuffix: z.string().trim().max(128).optional(),
  webhookSecretCurrent: z.string().trim().max(2048).optional(),
  webhookSecretPrevious: z.string().trim().max(2048).optional(),
  paymentMethodSetupPath: z.string().trim().max(256).optional(),
  paymentMethodSetupHostedUrlTemplate: z.string().trim().max(2048).optional(),
  paymentMethodSetupReturnUrl: z.string().trim().max(2048).optional(),
  paymentMethodSetupCallbackSecretCurrent: z.string().trim().max(2048).optional(),
  paymentMethodSetupCallbackSecretPrevious: z.string().trim().max(2048).optional(),
});

const billingRuntimeSettingsSchema = z.object({
  BILLING_ACTIVE_PROVIDER: z.enum(["stripe", "beam"]).optional(),
  BILLING_STRIPE_ENABLED: z.boolean().optional(),
  BILLING_BEAM_ENABLED: z.boolean().optional(),
  PAYMENT_RECONCILIATION_ENABLED: z.boolean().optional(),
  FINAL_RECONCILIATION_BEFORE_DOWNGRADE: z.boolean().optional(),
  ADMIN_MANUAL_MARK_PAID_ENABLED: z.boolean().optional(),
  ADMIN_DOWNGRADE_REVERSAL_ENABLED: z.boolean().optional(),
  SUPPORT_RECOVERY_CASES_ENABLED: z.boolean().optional(),
  DOCUMENT_RECOVERY_ENABLED: z.boolean().optional(),
  INVOICE_HEADER_SYNC_ENABLED: z.boolean().optional(),
  PAID_INVOICE_REISSUE_ENABLED: z.boolean().optional(),
  AUTO_DOWNGRADE_AFTER_7_DAYS: z.boolean().optional(),
  BEAM_PAYMENT_LINK_FALLBACK: z.boolean().optional(),
  BILLING_PHASE2_SAVED_CARDS_ENABLED: z.boolean().optional(),
  BILLING_PHASE2_AUTO_RENEW_ENABLED: z.boolean().optional(),
  BILLING_PHASE2_DUNNING_ENABLED: z.boolean().optional(),
  BILLING_PHASE2_CARD_SETUP_ENABLED: z.boolean().optional(),
  BILLING_PHASE2_FORCE_MANUAL_FALLBACK_ENABLED: z.boolean().optional(),
  BILLING_EMAIL_NOTIFICATIONS_ENABLED: z.boolean().optional(),
  BILLING_PHASE2_REQUIRE_STEP_UP: z.boolean().optional(),
  BILLING_PHASE2_ALLOWED_COHORTS: z.string().trim().max(1000).optional(),
  BILLING_PHASE2_DEFAULT_COHORT: z.string().trim().max(128).optional(),
  BILLING_PHASE2_SETUP_CALLBACK_TOLERANCE_SECONDS: z.string().trim().max(16).optional(),
  BILLING_WEBHOOK_TIMESTAMP_TOLERANCE_SECONDS: z.string().trim().max(16).optional(),
  BILLING_PAYMENT_METHOD_SETUP_EXPIRY_MINUTES: z.string().trim().max(16).optional(),
  BILLING_PHASE2_STEP_UP_WINDOW_MINUTES: z.string().trim().max(16).optional(),
  BILLING_EVIDENCE_RETENTION_DAYS: z.string().trim().max(16).optional(),
  BILLING_OVERDUE_DAYS: z.string().trim().max(16).optional(),
  BILLING_SUBSCRIPTION_RENEWAL_DUE_DAYS: z.string().trim().max(16).optional(),
  BILLING_TOPUP_DUE_DAYS: z.string().trim().max(16).optional(),
  BILLING_NOTIFICATION_REMINDER_FIRST_THRESHOLD_DAYS: z.string().trim().max(16).optional(),
  BILLING_NOTIFICATION_REMINDER_FINAL_THRESHOLD_DAYS: z.string().trim().max(16).optional(),
  BILLING_NOTIFICATION_COOLDOWN_REMINDER_HOURS: z.string().trim().max(16).optional(),
  BILLING_NOTIFICATION_COOLDOWN_SUCCESS_HOURS: z.string().trim().max(16).optional(),
  BILLING_NOTIFICATION_COOLDOWN_DEFAULT_HOURS: z.string().trim().max(16).optional(),
  BILLING_SUBSCRIPTION_CUTOVER_READY: z.boolean().optional(),
  BILLING_PUBLIC_URL: z.string().trim().max(2048).optional(),
  BILLING_PHASE2_STEP_UP_SECRET: z.string().trim().max(2048).optional(),
});

function actorFromContext(ctx: {
  user: { id: number; role?: string | null; currentTenantId?: unknown; registeredDomain?: string | null };
}) {
  return {
    id: ctx.user.id,
    role: ctx.user.role,
    currentTenantId: ctx.user.currentTenantId,
    registeredDomain: ctx.user.registeredDomain,
  };
}

export const adminBillingRouter = router({
  getSellerProfile: protectedProcedure
    .input(z.object({ tenantId: tenantIdSchema }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_seller_profile", { tenantId });
      return getSellerProfileForTenant(tenantId);
    }),

  upsertSellerProfile: protectedProcedure
    .input(sellerProfileSchema)
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_seller_profile", { tenantId });
      return upsertSellerProfileForTenant({
        tenantId,
        actorUserId: ctx.user.id,
        input: { ...input, tenantId },
      });
    }),

  listTaxPolicies: protectedProcedure
    .input(z.object({ tenantId: tenantIdSchema }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return listTaxPoliciesForTenant(tenantId);
    }),

  listSellerProfileRevisions: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_seller_profile", { tenantId });
      return listSellerProfileRevisionsForTenant({
        tenantId,
        limit: input.limit,
      });
    }),

  upsertTaxPolicy: protectedProcedure
    .input(taxPolicySchema)
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return upsertTaxPolicyForTenant({
        tenantId,
        actorUserId: ctx.user.id,
        input: {
          ...input,
          tenantId,
        },
      });
    }),

  classifyInvoiceStreamPreview: protectedProcedure
    .input(z.object({ country: z.string().trim().optional().nullable() }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return {
        invoiceStream: classifyInvoiceStream({ country: input.country ?? null }),
      };
    }),

  previewInvoiceNumber: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      stream: z.enum(["domestic", "international"]),
      year: z.number().int().min(2000).max(3000).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return {
        invoiceNumber: await previewInvoiceNumber({
          tenantId,
          stream: input.stream,
          year: input.year,
        }),
      };
    }),

  reserveInvoiceNumber: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      stream: z.enum(["domestic", "international"]),
      year: z.number().int().min(2000).max(3000).optional(),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return reserveNextInvoiceNumber({
        tenantId,
        stream: input.stream,
        year: input.year,
        actorUserId: ctx.user.id,
      });
    }),

  getActiveTaxPolicyPreview: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      stream: z.enum(["domestic", "international"]),
      issuedAt: z.date().optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return getActiveTaxPolicy({
        tenantId,
        stream: input.stream,
        issuedAt: input.issuedAt ?? new Date(),
      });
    }),

  getInvoice: protectedProcedure
    .input(z.object({ invoiceId: z.number().int().positive() }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      const invoice = await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      if (!invoice) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Invoice not found" });
      }
      return invoice;
    }),

  listInvoices: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      query: z.string().trim().max(128).optional().nullable(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      return listAdminInvoices({
        tenantId,
        query: input.query ?? null,
        limit: input.limit,
      });
    }),

  listPaymentMethods: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      userId: z.number().int().positive().optional().nullable(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_payment_method", { tenantId });
      return listPaymentMethodsForAdmin({
        tenantId,
        userId: input.userId ?? null,
      });
    }),

  getPhase2Metrics: protectedProcedure
    .input(z.object({ tenantId: tenantIdSchema.optional().nullable() }).optional())
    .query(async ({ ctx }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      return getBillingPhase2Metrics({ tenantId });
    }),

  getSubscriptionPaymentSettings: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      subscriptionId: z.number().int().positive(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_payment_method", { tenantId });
      return getSubscriptionPaymentSettingsForAdmin({
        tenantId,
        subscriptionId: input.subscriptionId,
      });
    }),

  getBeamProviderSettings: protectedProcedure
    .query(async ({ ctx }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return getBeamProviderAdminSettings();
    }),

  updateBeamProviderSettings: protectedProcedure
    .input(beamProviderSettingsSchema)
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return updateBeamProviderAdminSettings(input, ctx.user.id);
    }),

  testBeamProviderSettings: protectedProcedure
    .query(async ({ ctx }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return testBeamProviderAdminSettings();
    }),

  getBillingRuntimeSettings: protectedProcedure
    .query(async ({ ctx }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return getBillingRuntimeSettingsAdmin();
    }),

  updateBillingRuntimeSettings: protectedProcedure
    .input(billingRuntimeSettingsSchema)
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return updateBillingRuntimeSettings(input, ctx.user.id);
    }),

  listRenewalAttempts: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      subscriptionId: z.number().int().positive(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      const settings = await getSubscriptionPaymentSettingsForAdmin({
        tenantId,
        subscriptionId: input.subscriptionId,
      });
      if (!settings) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Subscription not found" });
      }
      return listRenewalAttemptsForSubscription({
        subscriptionId: input.subscriptionId,
        limit: input.limit,
      });
    }),

  listRecoveryCases: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      invoiceId: z.number().int().positive().optional().nullable(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "create_support_recovery_case", { tenantId });
      return listSupportRecoveryCases({
        tenantId,
        invoiceId: input.invoiceId ?? null,
        limit: input.limit,
      });
    }),

  listInvoiceDocuments: protectedProcedure
    .input(z.object({ invoiceId: z.number().int().positive() }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "download_invoice_document", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoiceDocuments(input.invoiceId);
    }),

  getInvoiceDocumentAccess: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      documentId: z.number().int().positive(),
      ttlSeconds: z.number().int().min(60).max(86400).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "download_invoice_document", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      const access = await resolveInvoiceDocumentAccess({
        invoiceId: input.invoiceId,
        documentId: input.documentId,
        ttlSeconds: input.ttlSeconds,
        actorUserId: ctx.user.id,
        actorType: "admin",
      });
      if (!access) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Document not found" });
      }
      return access;
    }),

  listNotificationDispatches: protectedProcedure
    .input(z.object({ invoiceId: z.number().int().positive() }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoiceNotificationDispatches(input.invoiceId);
    }),

  listInvoicePayments: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      invoiceId: z.number().int().positive(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_decline_metadata", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoicePaymentsForAdmin({
        tenantId,
        invoiceId: input.invoiceId,
      });
    }),

  listInvoiceAuditLogs: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      invoiceId: z.number().int().positive(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoiceAuditLogsForAdmin({
        tenantId,
        invoiceId: input.invoiceId,
        limit: input.limit,
      });
    }),

  listInvoiceReconciliationRuns: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      invoiceId: z.number().int().positive(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "request_reconciliation", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoiceReconciliationRunsForAdmin({
        tenantId,
        invoiceId: input.invoiceId,
        limit: input.limit,
      });
    }),

  listInvoiceWebhookEvents: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      invoiceId: z.number().int().positive(),
      limit: z.number().int().min(1).max(200).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_decline_metadata", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return listInvoiceWebhookEventsForAdmin({
        tenantId,
        invoiceId: input.invoiceId,
        limit: input.limit,
      });
    }),

  syncHeader: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      scope: z.enum(["seller", "buyer", "both"]).default("both"),
      reason: z.string().trim().max(2000).optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("INVOICE_HEADER_SYNC_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "sync_invoice_header", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return syncInvoiceHeader({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        scope: input.scope,
        reason: input.reason ?? null,
      });
    }),

  replacePaidInvoice: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("PAID_INVOICE_REISSUE_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "replace_paid_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return replacePaidInvoice({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  sendInvoiceNotification: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      notificationType: z.enum([
        "invoice_issued",
        "qr_ready",
        "payment_success",
        "invoice_due_reminder",
        "invoice_overdue_downgraded",
        "invoice_reissued",
      ]),
      variant: z.string().trim().max(128).optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("SUPPORT_RECOVERY_CASES_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return sendInvoiceNotification({
        invoiceId: input.invoiceId,
        notificationType: input.notificationType,
        actorUserId: ctx.user.id,
        variant: input.variant ?? null,
      });
    }),

  createSupportRecoveryCase: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      paymentId: z.number().int().positive().optional().nullable(),
      issueType: z.enum([
        "payment_not_applied",
        "wrong_downgrade",
        "amount_mismatch",
        "missing_document",
        "duplicate_charge_review",
        "other",
      ]),
      resolutionNote: z.string().trim().max(2000).optional().nullable(),
      evidenceJson: z.record(z.any()).optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("SUPPORT_RECOVERY_CASES_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "create_support_recovery_case", { tenantId });
      const invoice = await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      if (!invoice) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Invoice not found" });
      }
      return createSupportRecoveryCase({
        tenantId,
        userId: invoice.userId,
        invoiceId: invoice.id,
        paymentId: input.paymentId ?? null,
        actorUserId: ctx.user.id,
        issueType: input.issueType,
        resolutionNote: input.resolutionNote ?? null,
        evidenceJson: input.evidenceJson ?? null,
      });
    }),

  uploadRecoveryEvidence: protectedProcedure
    .input(z.object({
      recoveryCaseId: z.number().int().positive(),
      fileName: z.string().trim().min(1).max(255),
      contentType: z.string().trim().min(1).max(255),
      base64Content: z.string().min(1).max(15_000_000),
      note: z.string().trim().max(1000).optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("PAYMENT_RECONCILIATION_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "create_support_recovery_case", { tenantId });
      return uploadSupportRecoveryEvidence({
        recoveryCaseId: input.recoveryCaseId,
        actorUserId: ctx.user.id,
        fileName: input.fileName,
        contentType: input.contentType,
        base64Content: input.base64Content,
        note: input.note ?? null,
      });
    }),

  getRecoveryEvidenceAccess: protectedProcedure
    .input(z.object({
      recoveryCaseId: z.number().int().positive(),
      attachmentIndex: z.number().int().min(0),
      ttlSeconds: z.number().int().min(60).max(86400).optional(),
    }))
    .query(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "view_recovery_evidence", { tenantId });
      return resolveSupportRecoveryEvidenceAccess({
        recoveryCaseId: input.recoveryCaseId,
        attachmentIndex: input.attachmentIndex,
        actorUserId: ctx.user.id,
        ttlSeconds: input.ttlSeconds,
      });
    }),

  requestReconciliation: protectedProcedure
    .input(z.object({ invoiceId: z.number().int().positive() }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("ADMIN_MANUAL_MARK_PAID_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "request_reconciliation", { tenantId });
      const invoice = await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      if (!invoice) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Invoice not found" });
      }
      return requestInvoiceReconciliation({
        invoiceId: invoice.id,
        actorUserId: ctx.user.id,
      });
    }),

  manualMarkPaid: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
      evidenceJson: z.record(z.any()).optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      await assertBillingFeatureEnabled("ADMIN_DOWNGRADE_REVERSAL_ENABLED");
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "manual_mark_paid", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return manualMarkInvoicePaid({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
        evidenceJson: input.evidenceJson ?? null,
      });
    }),

  reverseWrongDowngrade: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "reverse_wrong_downgrade", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return reverseWrongDowngrade({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  revokePaymentMethod: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      paymentMethodId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "revoke_payment_method", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "revoke_payment_method", { tenantId });
      return revokePaymentMethodForAdmin({
        tenantId,
        paymentMethodId: input.paymentMethodId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  cancelInvoice: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "cancel_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return cancelInvoiceForAdmin({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  reopenInvoice: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "reopen_invoice", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return reopenInvoiceForAdmin({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  cancelStalePaymentAttempt: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "cancel_stale_payment_attempt", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return cancelStalePaymentAttempt({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  regeneratePaymentAttempt: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "regenerate_payment_attempt", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return regenerateInvoicePaymentAttempt({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  applyMissingCredits: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "apply_missing_credits", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return applyMissingCreditsForInvoice({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  applyMissingSubscriptionRenewal: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "apply_missing_subscription_renewal", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return applyMissingSubscriptionRenewalForInvoice({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  createRenewalInvoice: protectedProcedure
    .input(z.object({
      subscriptionId: z.number().int().positive(),
      tenantId: tenantIdSchema,
      cycleStart: z.date().optional().nullable(),
      cycleEnd: z.date().optional().nullable(),
      basePriceOverride: z.number().positive().optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "edit_tax_and_numbering", { tenantId });
      return createOrGetInvoiceForBillingCycle({
        subscriptionId: input.subscriptionId,
        actorUserId: ctx.user.id,
        tenantId,
        cycleStart: input.cycleStart ?? null,
        cycleEnd: input.cycleEnd ?? null,
        basePriceOverride: input.basePriceOverride ?? null,
      });
    }),

  forceDisableAutoRenew: protectedProcedure
    .input(z.object({
      tenantId: tenantIdSchema,
      subscriptionId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = input.tenantId ?? resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "manage_renewal_attempt", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      return disableAutoRenewForSubscriptionAdmin({
        subscriptionId: input.subscriptionId,
        tenantId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  pauseRenewalDunning: protectedProcedure
    .input(z.object({
      renewalAttemptId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "manage_renewal_attempt", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      return pauseRenewalDunning({
        renewalAttemptId: input.renewalAttemptId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  resumeRenewalDunning: protectedProcedure
    .input(z.object({
      renewalAttemptId: z.number().int().positive(),
      nextRetryAt: z.date().optional().nullable(),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "manage_renewal_attempt", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      return resumeRenewalDunning({
        renewalAttemptId: input.renewalAttemptId,
        actorUserId: ctx.user.id,
        nextRetryAt: input.nextRetryAt ?? null,
      });
    }),

  fallbackInvoiceToManualCollection: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingFeatureEnabled("BILLING_PHASE2_FORCE_MANUAL_FALLBACK_ENABLED");
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "manage_renewal_attempt", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      return fallbackInvoiceToManualCollection({
        invoiceId: input.invoiceId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  forceRetryRenewalAttempt: protectedProcedure
    .input(z.object({
      renewalAttemptId: z.number().int().positive(),
      reason: z.string().trim().min(3).max(2000),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      await assertBillingStepUpIfRequired({ req: ctx.req, action: "manage_renewal_attempt", actorUserId: ctx.user.id });
      assertBillingActionAuthorized(actorFromContext(ctx), "manage_renewal_attempt", { tenantId });
      return forceRetryRenewalAttempt({
        renewalAttemptId: input.renewalAttemptId,
        actorUserId: ctx.user.id,
        reason: input.reason,
      });
    }),

  regenerateInvoiceDocument: protectedProcedure
    .input(z.object({
      invoiceId: z.number().int().positive(),
      language: z.enum(["th", "en", "bilingual"]),
      reason: z.enum(["sync_header", "language_variant", "reissue_render", "manual_regeneration"]),
    }))
    .mutation(async ({ ctx, input }) => {
      const tenantId = resolveTenantIdVarchar(ctx.tenantId, ctx.user.currentTenantId);
      assertBillingActionAuthorized(actorFromContext(ctx), "download_invoice_document", { tenantId });
      const invoice = await getAdminVisibleInvoice({ invoiceId: input.invoiceId, tenantId });
      if (!invoice) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Invoice not found" });
      }
      return renderInvoiceDocument({
        invoiceId: invoice.id,
        language: input.language,
        reason: input.reason,
        renderedByType: "admin",
        renderedById: ctx.user.id,
      });
    }),
});
