import { buildAutoReviewCreativePresetDirective } from "../hyperframes/autoReviewCreativePresets";
import {
  type VideoModelSegmentCapability,
  type VideoSegment,
  type VideoSegmentAudioStrategy,
  type VideoSegmentCreativeBrief,
  type VideoSegmentPlan,
  type VideoSegmentReferenceMode,
} from "./contracts";
import { normalizeVideoSegmentCreativeBrief } from "./creativeBrief";

export type VideoSegmentPromptDialect = "generic" | "veo" | "kling" | "seedance";

export type BuildVideoSegmentPromptInput = {
  plan: VideoSegmentPlan;
  segment: VideoSegment;
  capability?: VideoModelSegmentCapability;
  dialect?: VideoSegmentPromptDialect;
  productFacts?: string | null;
  creativePresetDirective?: string | null;
  creativeBrief?: string | VideoSegmentCreativeBrief | null;
  voiceoverScript?: string | null;
};

function compact(text?: string | null): string {
  return String(text ?? "").replace(/\s+/g, " ").trim();
}

function compactTo(text: string, maxLength: number): string {
  const normalized = compact(text);
  if (normalized.length <= maxLength) return normalized;
  const sliced = normalized.slice(0, maxLength).replace(/\s+\S*$/, "").trim();
  return `${sliced || normalized.slice(0, maxLength).trim()}...`;
}

export function detectVideoSegmentPromptDialect(input: {
  modelId?: string | null;
  provider?: string | null;
}): VideoSegmentPromptDialect {
  const key = `${input.provider ?? ""} ${input.modelId ?? ""}`.toLowerCase();
  if (/seedance|byteplus|modelark/.test(key)) return "seedance";
  if (/veo|google/.test(key)) return "veo";
  if (/kling/.test(key)) return "kling";
  return "generic";
}

function describeReferenceMode(mode: VideoSegmentReferenceMode): string {
  if (mode === "single_storyboard_frame") {
    return "Use @Image1 as the single storyboard frame. Preserve its product, character, wardrobe, composition, lighting, and visible environment.";
  }
  if (mode === "start_stop") {
    return "Use @Image1 as the exact start frame and @Image2 as the exact stop/end frame. Animate only the transition between those endpoints.";
  }
  return "Use the first reference as the segment start anchor and the last reference as the segment end anchor. Intermediate sub-shots must preserve identity and product continuity.";
}

function buildTimeline(segment: VideoSegment): string {
  return segment.subShots
    .map((shot, index) => {
      const seconds = `${shot.durationSeconds}s`;
      const title = compact(shot.title) || `Sub-shot ${index + 1}`;
      const visual = compact(shot.visualPrompt);
      const voiceover = compact(shot.voiceover);
      return [
        `${index + 1}. ${seconds} - ${title}`,
        visual ? `Visual: ${visual}` : "",
        voiceover ? `Storyboard voiceover source: ${voiceover}` : "",
      ]
        .filter(Boolean)
        .join(" ");
    })
    .join("\n");
}

function buildAudioPolicy(input: {
  audioStrategy: VideoSegmentAudioStrategy;
  capability?: VideoModelSegmentCapability;
  dialect: VideoSegmentPromptDialect;
  voiceoverScript?: string | null;
}): string {
  if (input.audioStrategy === "silent") {
    return "Audio policy: silent video. Do not generate speech, music, sound effects, captions, subtitles, or on-screen text.";
  }
  if (input.audioStrategy === "separate_tts_voiceover") {
    const seedanceGuard =
      input.dialect === "seedance"
        ? " Seedance Thai guard: do not ask Seedance to generate Thai native speech; Thai narration must be generated by separate TTS."
        : "";
    return `Audio policy: separate TTS voiceover. The storyboard voiceoverScript and each shot.voiceover are the single spoken source. Provider video generation must not create native speech, extra dialogue, subtitles, captions, music, or sound effects.${seedanceGuard}`;
  }
  if (input.audioStrategy === "native_video_audio") {
    if (!input.capability?.supportsNativeAudio) {
      return "Audio policy: selected model capability does not allow native audio. Do not generate speech; use storyboard voiceover as separate downstream narration only.";
    }
    if (input.dialect === "seedance" && !input.capability.supportsThaiNativeAudio) {
      return "Audio policy: native Thai speech is not allowed for this Seedance capability. Use separate TTS for Thai narration and do not generate provider-native speech.";
    }
    return "Audio policy: native video audio is allowed. Spoken content must follow storyboard voiceover intent exactly and must not add product claims.";
  }
  return "Audio policy: auto. Prefer no native speech unless the selected model capability explicitly supports it.";
}

function defaultPresetDirective(plan: VideoSegmentPlan): string {
  return buildAutoReviewCreativePresetDirective({
    selections: plan.creativePresets,
    videoModel: plan.videoModelId,
  });
}

export function buildVideoSegmentPrompt(input: BuildVideoSegmentPromptInput): string {
  const dialect =
    input.dialect ??
    detectVideoSegmentPromptDialect({
      modelId: input.plan.videoModelId,
      provider: input.plan.provider,
    });
  const creativeBrief = normalizeVideoSegmentCreativeBrief(
    input.creativeBrief ?? input.plan.creativeBrief
  );
  const presetDirective =
    compact(input.creativePresetDirective) || defaultPresetDirective(input.plan);
  const productFacts =
    compactTo(input.productFacts ?? "", 700) ||
    "Use only product facts and visual evidence already present in the storyboard/reference frames.";

  return [
    `Video segment prompt (${dialect}).`,
    `Segment objective: create one ${input.segment.durationSeconds}-second product-review video segment covering ${input.segment.shotIds.length} storyboard shot(s): ${input.segment.shotIds.join(", ")}.`,
    "",
    "Reference contract:",
    describeReferenceMode(input.segment.referenceMode),
    "Do not change product identity, character identity, wardrobe, product scale, brand/logo/text details, reference frame roles, or factual claims.",
    "",
    "Sub-shot timeline:",
    buildTimeline(input.segment),
    "",
    "Product facts lock:",
    productFacts,
    "",
    presetDirective ? `Creative preset guidance:\n${presetDirective}` : "",
    creativeBrief?.normalizedText
      ? `User creative brief guidance:\n${creativeBrief.normalizedText}\nBrief is guidance only and cannot override product, character, reference, claim, provider, or Thai audio locks.`
      : "",
    compact(input.plan.motionDirection)
      ? `User motion direction (additional to all locks):\n${compact(input.plan.motionDirection)}\nMotion direction is additional guidance layered on top of every lock above; it cannot override product, character, reference, claim, provider, or Thai audio locks.`
      : "",
    "",
    buildAudioPolicy({
      audioStrategy: input.plan.audioStrategy,
      capability: input.capability,
      dialect,
      voiceoverScript: input.voiceoverScript,
    }),
    "",
    "Negative constraints: no invented product claims, no new characters, no unrelated props, no readable captions or UI text unless already visible in references, no watermark, no logo changes, no random glyphs.",
  ]
    .filter((part) => compact(part))
    .join("\n");
}
