CREATE TABLE IF NOT EXISTS "vertical_drama_special_tie_in_debug_events" (
  "id" bigserial PRIMARY KEY NOT NULL,
  "tenantId" varchar(36) NOT NULL,
  "userId" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "seriesId" bigint NOT NULL REFERENCES "vertical_drama_series"("id") ON DELETE cascade,
  "episodeId" bigint NOT NULL REFERENCES "vertical_drama_episodes"("id") ON DELETE cascade,
  "jobId" varchar(64) NOT NULL,
  "traceId" varchar(128) NOT NULL,
  "createIntentId" varchar(64),
  "inputVersion" integer,
  "sequence" integer NOT NULL,
  "eventType" varchar(64) NOT NULL,
  "stage" varchar(64),
  "skillSlug" varchar(160),
  "skillVersion" varchar(128),
  "skillHash" varchar(64),
  "logicalAttempt" integer,
  "planningAttemptNumber" integer,
  "schemaRetryNumber" integer,
  "modelFallbackAttempt" integer,
  "model" varchar(255),
  "providerId" integer,
  "providerName" varchar(120),
  "providerCallId" varchar(128),
  "statusCode" integer,
  "outcome" varchar(32),
  "errorCode" varchar(100),
  "errorMessage" text,
  "retryCategory" varchar(40),
  "retryReason" text,
  "nextAction" varchar(80),
  "remainingBudget" jsonb,
  "requestPayload" text,
  "responsePayload" text,
  "requestHash" varchar(64),
  "responseHash" varchar(64),
  "requestCharCount" integer,
  "responseCharCount" integer,
  "requestRedacted" boolean NOT NULL DEFAULT false,
  "responseRedacted" boolean NOT NULL DEFAULT false,
  "parsedOutput" jsonb,
  "schemaIssues" jsonb,
  "metadata" jsonb,
  "startedAt" timestamptz,
  "completedAt" timestamptz,
  "expiresAt" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "vds_special_debug_episode_idx" ON "vertical_drama_special_tie_in_debug_events" ("tenantId", "userId", "episodeId", "createdAt");
CREATE INDEX IF NOT EXISTS "vds_special_debug_job_idx" ON "vertical_drama_special_tie_in_debug_events" ("tenantId", "jobId", "createdAt");
CREATE INDEX IF NOT EXISTS "vds_special_debug_trace_idx" ON "vertical_drama_special_tie_in_debug_events" ("tenantId", "traceId", "createdAt");
CREATE INDEX IF NOT EXISTS "vds_special_debug_expiry_idx" ON "vertical_drama_special_tie_in_debug_events" ("expiresAt");
