-- Feature 186 follow-up: complete the canonical error projection and make
-- lifecycle evidence deletion fail closed. This migration is additive and
-- rerunnable; it does not rewrite status or delete legacy rows.

ALTER TABLE "worker_jobs"
  ADD COLUMN IF NOT EXISTS "errorCode" varchar(100),
  ADD COLUMN IF NOT EXISTS "errorMessage" text;--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "worker_jobs_status_lease_expiry_idx"
  ON "worker_jobs" ("status", "leaseExpiresAt")
  WHERE "leaseExpiresAt" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "worker_jobs_tenant_status_created_idx"
  ON "worker_jobs" ("tenantId", "status", "createdAt", "id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "worker_job_dispatches_queue_ref_idx"
  ON "worker_job_dispatches" ("referenceNamespace", "queueJobId")
  WHERE "queueJobId" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "worker_job_dispatches_celery_ref_idx"
  ON "worker_job_dispatches" ("referenceNamespace", "celeryTaskId")
  WHERE "celeryTaskId" IS NOT NULL;--> statement-breakpoint

-- The lifecycle ledger and publication/settlement evidence must not disappear
-- through a parent delete. Existing deployments may have constraint names
-- generated by different Drizzle versions, so locate the FK by relation.
DO $$
DECLARE
  child_table text;
  constraint_name text;
  delete_type "char";
  target_constraint text;
BEGIN
  FOREACH child_table IN ARRAY ARRAY[
    'worker_job_events',
    'worker_job_attempts',
    'worker_job_dispatches',
    'worker_job_outbox',
    'worker_job_schedule_occurrences',
    'worker_job_settlements',
    'worker_job_actions',
    'worker_job_callbacks'
  ] LOOP
    target_constraint := 'feature_186_' || child_table || '_worker_job_fk_restrict';
    SELECT c.conname, c.confdeltype
      INTO constraint_name, delete_type
    FROM pg_constraint c
    JOIN pg_class child ON child.oid = c.conrelid
    JOIN pg_class parent ON parent.oid = c.confrelid
    WHERE child.relname = child_table
      AND parent.relname = 'worker_jobs'
      AND c.contype = 'f'
      AND EXISTS (
        SELECT 1
        FROM pg_attribute a
        WHERE a.attrelid = c.conrelid
          AND a.attnum = ANY(c.conkey)
          AND a.attname = 'workerJobId'
      )
    LIMIT 1;

    IF constraint_name IS NOT NULL AND delete_type <> 'r' THEN
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', child_table, constraint_name);
      constraint_name := NULL;
    END IF;

    IF constraint_name IS NULL THEN
      EXECUTE format(
        'ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY ("workerJobId") REFERENCES "worker_jobs"("id") ON DELETE RESTRICT',
        child_table,
        target_constraint
      );
    END IF;
  END LOOP;
END $$;
