from .generic import GenericSlipParser
from .generic_bank import GenericBankParser
from .generic_wallet import GenericWalletParser
from .generic_gov_app import GenericGovAppParser
from .ktb import KTBParser
from .bay import BAYParser
from .scb import SCBParser
from .ttb import TTBParser
from .truemoney import TrueMoneyParser
from .paotang import PaotangParser