/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/y2k/y2kTheme.ts
 * Command: astryx theme build client/src/themes/y2k/y2kTheme.ts
 * Generated: 2026-07-04T02:32:51.421Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const y2kIconRegistry: IconRegistry;
export declare const y2kTheme: DefinedTheme;
