/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/matcha/matchaTheme.ts
 * Command: astryx theme build client/src/themes/matcha/matchaTheme.ts
 * Generated: 2026-07-04T02:32:50.344Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const matchaIconRegistry: IconRegistry;
export declare const matchaTheme: DefinedTheme;
