/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/matcha/matchaTheme.ts
 * Command: astryx theme build client/src/themes/matcha/matchaTheme.ts
 * Generated: 2026-07-04T02:32:50.347Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
