import { and, desc, eq, ilike, inArray, isNull, or, sql } from "drizzle-orm";

import {
  billingProfiles,
  invoiceAuditLogs,
  invoiceLineItems,
  invoices,
  paymentAttempts,
  paymentSlips,
  payments,
  reconciliationRuns,
  sellerProfiles,
  sellerProfileRevisions,
  supportRecoveryCases,
  taxPolicies,
  users,
  webhookEvents,
  type InsertBillingProfile,
  type InsertSellerProfile,
  type InsertSellerProfileRevision,
  type InsertTaxPolicy,
} from "../../../drizzle/schema";
import { getDb } from "../../db";

let billingProfilesTenantColumnCache: boolean | null = null;

export interface BillingProfileInput {
  tenantId?: string | null;
  legalNameTh?: string | null;
  legalNameEn?: string | null;
  taxId?: string | null;
  phone?: string | null;
  email?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  subdistrict?: string | null;
  district?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  contactName?: string | null;
  invoiceNote?: string | null;
}

export interface SellerProfileInput {
  tenantId?: string | null;
  entityNameTh?: string | null;
  entityNameEn?: string | null;
  taxId?: string | null;
  phone?: string | null;
  email?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  subdistrict?: string | null;
  district?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  signerName?: string | null;
  signerTitle?: string | null;
  branchType?: string | null;
  footerNoteTh?: string | null;
  footerNoteEn?: string | null;
  autoGeneratedDocumentNoteTh?: string | null;
  autoGeneratedDocumentNoteEn?: string | null;
  logoUrl?: string | null;
}

export interface TaxPolicyInput {
  tenantId?: string | null;
  stream: "domestic" | "international";
  taxName: string;
  taxRatePercent: string;
  isEnabled: boolean;
  effectiveFrom: Date;
  effectiveTo?: Date | null;
  roundingPolicy?: string | null;
}

function normalizeNullableString(value: string | null | undefined): string | null {
  if (value == null) return null;
  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

function extractSqlRows(result: unknown): Array<Record<string, any>> {
  if (Array.isArray(result)) {
    return result as Array<Record<string, any>>;
  }
  if (
    result
    && typeof result === "object"
    && Array.isArray((result as { rows?: unknown }).rows)
  ) {
    return (result as { rows: Array<Record<string, any>> }).rows;
  }
  return [];
}

function sanitizeSensitiveJson(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sanitizeSensitiveJson);
  }

  if (!value || typeof value !== "object") {
    return value;
  }

  const entries = Object.entries(value as Record<string, unknown>).map(([key, nestedValue]) => {
    const lowered = key.toLowerCase();
    if (
      lowered.includes("secret")
      || lowered.includes("signature")
      || lowered.includes("token")
      || lowered.includes("authorization")
      || lowered.includes("api_key")
      || lowered.includes("apikey")
      || lowered === "taxid"
      || lowered === "tax_id"
      || lowered.includes("email")
      || lowered.includes("phone")
      || lowered.includes("address")
      || lowered.includes("postal")
      || lowered.includes("district")
      || lowered.includes("province")
      || lowered.includes("country")
      || lowered.includes("contact")
      || lowered.includes("legalname")
      || lowered.includes("entityname")
      || lowered.includes("signername")
    ) {
      return [key, "[redacted]"];
    }

    return [key, sanitizeSensitiveJson(nestedValue)];
  });

  return Object.fromEntries(entries);
}

function buildFieldDiff(previousValue: Record<string, any> | null, nextValue: Record<string, any> | null) {
  const previous = previousValue ?? {};
  const next = nextValue ?? {};
  const keys = new Set([...Object.keys(previous), ...Object.keys(next)]);
  const diff: Record<string, { before: unknown; after: unknown }> = {};
  for (const key of keys) {
    const before = previous[key];
    const after = next[key];
    if (JSON.stringify(before) !== JSON.stringify(after)) {
      diff[key] = { before, after };
    }
  }
  return diff;
}

async function billingProfilesHasTenantColumn() {
  if (billingProfilesTenantColumnCache != null) {
    return billingProfilesTenantColumnCache;
  }

  try {
    const db = getDb();
    const result = await db.execute(sql`
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'billing_profiles'
        and column_name = 'tenantId'
      limit 1
    `);
    billingProfilesTenantColumnCache = extractSqlRows(result).length > 0;
  } catch {
    billingProfilesTenantColumnCache = false;
  }

  return billingProfilesTenantColumnCache;
}

export async function getBillingProfileForUser(userId: number) {
  const db = getDb();
  try {
    const result = await db.execute(sql`select * from "billing_profiles" where "userId" = ${userId} limit 1`);
    const row = extractSqlRows(result)[0];
    if (!row) return null;

    return {
      id: row.id ?? null,
      tenantId: row.tenantId ?? row.tenant_id ?? null,
      userId: row.userId ?? row.user_id ?? userId,
      legalNameTh: row.legalNameTh ?? row.legal_name_th ?? null,
      legalNameEn: row.legalNameEn ?? row.legal_name_en ?? null,
      taxId: row.taxId ?? row.tax_id ?? null,
      phone: row.phone ?? null,
      email: row.email ?? null,
      addressLine1: row.addressLine1 ?? row.address_line_1 ?? null,
      addressLine2: row.addressLine2 ?? row.address_line_2 ?? null,
      subdistrict: row.subdistrict ?? null,
      district: row.district ?? null,
      province: row.province ?? null,
      postalCode: row.postalCode ?? row.postal_code ?? null,
      country: row.country ?? null,
      contactName: row.contactName ?? row.contact_name ?? null,
      invoiceNote: row.invoiceNote ?? row.invoice_note ?? null,
      updatedBy: row.updatedBy ?? row.updated_by ?? null,
      createdAt: row.createdAt ?? row.created_at ?? null,
      updatedAt: row.updatedAt ?? row.updated_at ?? null,
    };
  } catch {
    return null;
  }
}

export async function upsertBillingProfileForUser(params: {
  userId: number;
  actorUserId: number;
  input: BillingProfileInput;
}) {
  const db = getDb();
  const hasTenantColumn = await billingProfilesHasTenantColumn();
  const payloadBase = {
    userId: params.userId,
    legalNameTh: normalizeNullableString(params.input.legalNameTh),
    legalNameEn: normalizeNullableString(params.input.legalNameEn),
    taxId: normalizeNullableString(params.input.taxId),
    phone: normalizeNullableString(params.input.phone),
    email: normalizeNullableString(params.input.email),
    addressLine1: normalizeNullableString(params.input.addressLine1),
    addressLine2: normalizeNullableString(params.input.addressLine2),
    subdistrict: normalizeNullableString(params.input.subdistrict),
    district: normalizeNullableString(params.input.district),
    province: normalizeNullableString(params.input.province),
    postalCode: normalizeNullableString(params.input.postalCode),
    country: normalizeNullableString(params.input.country),
    contactName: normalizeNullableString(params.input.contactName),
    invoiceNote: normalizeNullableString(params.input.invoiceNote),
    updatedBy: params.actorUserId,
    updatedAt: new Date(),
  };
  const payload: InsertBillingProfile = {
    ...payloadBase,
    ...(hasTenantColumn ? { tenantId: params.input.tenantId ?? null } : {}),
  };

  const existing = await getBillingProfileForUser(params.userId);
  if (existing) {
    const [updated] = await db
      .update(billingProfiles)
      .set(payload)
      .where(eq(billingProfiles.id, existing.id))
      .returning();
    return updated;
  }

  const [created] = await db.insert(billingProfiles).values(payload).returning();
  return created;
}

export async function getSellerProfileForTenant(tenantId: string | null) {
  const db = getDb();
  try {
    const result = tenantId
      ? await db.execute(sql`select * from "seller_profiles" where "tenantId" = ${tenantId} limit 1`)
      : await db.execute(sql`select * from "seller_profiles" where "tenantId" is null limit 1`);
    const row = extractSqlRows(result)[0];
    if (!row) return null;

    return {
      id: row.id ?? null,
      tenantId: row.tenantId ?? row.tenant_id ?? tenantId ?? null,
      entityNameTh: row.entityNameTh ?? row.entity_name_th ?? null,
      entityNameEn: row.entityNameEn ?? row.entity_name_en ?? null,
      taxId: row.taxId ?? row.tax_id ?? null,
      phone: row.phone ?? null,
      email: row.email ?? null,
      addressLine1: row.addressLine1 ?? row.address_line_1 ?? null,
      addressLine2: row.addressLine2 ?? row.address_line_2 ?? null,
      subdistrict: row.subdistrict ?? null,
      district: row.district ?? null,
      province: row.province ?? null,
      postalCode: row.postalCode ?? row.postal_code ?? null,
      country: row.country ?? null,
      signerName: row.signerName ?? row.signer_name ?? null,
      signerTitle: row.signerTitle ?? row.signer_title ?? null,
      branchType: row.branchType ?? row.branch_type ?? null,
      footerNoteTh: row.footerNoteTh ?? row.footer_note_th ?? null,
      footerNoteEn: row.footerNoteEn ?? row.footer_note_en ?? null,
      autoGeneratedDocumentNoteTh:
        row.autoGeneratedDocumentNoteTh ?? row.auto_generated_document_note_th ?? null,
      autoGeneratedDocumentNoteEn:
        row.autoGeneratedDocumentNoteEn ?? row.auto_generated_document_note_en ?? null,
      logoUrl: row.logoUrl ?? row.logo_url ?? null,
      revision: row.revision ?? 1,
      updatedBy: row.updatedBy ?? row.updated_by ?? null,
      createdAt: row.createdAt ?? row.created_at ?? null,
      updatedAt: row.updatedAt ?? row.updated_at ?? null,
    };
  } catch {
    return null;
  }
}

export async function upsertSellerProfileForTenant(params: {
  tenantId: string | null;
  actorUserId: number;
  input: SellerProfileInput;
}) {
  const db = getDb();
  const existing = await getSellerProfileForTenant(params.tenantId);
  const payload: InsertSellerProfile = {
    tenantId: params.tenantId,
    entityNameTh: normalizeNullableString(params.input.entityNameTh),
    entityNameEn: normalizeNullableString(params.input.entityNameEn),
    taxId: normalizeNullableString(params.input.taxId),
    phone: normalizeNullableString(params.input.phone),
    email: normalizeNullableString(params.input.email),
    addressLine1: normalizeNullableString(params.input.addressLine1),
    addressLine2: normalizeNullableString(params.input.addressLine2),
    subdistrict: normalizeNullableString(params.input.subdistrict),
    district: normalizeNullableString(params.input.district),
    province: normalizeNullableString(params.input.province),
    postalCode: normalizeNullableString(params.input.postalCode),
    country: normalizeNullableString(params.input.country),
    signerName: normalizeNullableString(params.input.signerName),
    signerTitle: normalizeNullableString(params.input.signerTitle),
    branchType: normalizeNullableString(params.input.branchType),
    footerNoteTh: normalizeNullableString(params.input.footerNoteTh),
    footerNoteEn: normalizeNullableString(params.input.footerNoteEn),
    autoGeneratedDocumentNoteTh: normalizeNullableString(params.input.autoGeneratedDocumentNoteTh),
    autoGeneratedDocumentNoteEn: normalizeNullableString(params.input.autoGeneratedDocumentNoteEn),
    logoUrl: normalizeNullableString(params.input.logoUrl),
    updatedBy: params.actorUserId,
    updatedAt: new Date(),
  };

  if (existing) {
    const revision = (existing.revision ?? 0) + 1;
    const [updated] = await db
      .update(sellerProfiles)
      .set({
        ...payload,
        revision,
      })
      .where(eq(sellerProfiles.id, existing.id))
      .returning();

    const revisionPayload: InsertSellerProfileRevision = {
      sellerProfileId: updated.id,
      tenantId: params.tenantId,
      revision,
      snapshotJson: updated as Record<string, any>,
      diffJson: buildFieldDiff(existing as Record<string, any>, updated as Record<string, any>),
      updatedBy: params.actorUserId,
    };
    await db.insert(sellerProfileRevisions).values(revisionPayload);
    return updated;
  }

  const [created] = await db.insert(sellerProfiles).values(payload).returning();
  await db.insert(sellerProfileRevisions).values({
    sellerProfileId: created.id,
    tenantId: params.tenantId,
    revision: created.revision ?? 1,
    snapshotJson: created as Record<string, any>,
    diffJson: buildFieldDiff(null, created as Record<string, any>),
    updatedBy: params.actorUserId,
  });
  return created;
}

export async function listSellerProfileRevisionsForTenant(params: {
  tenantId: string | null;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 50, 1), 200);
  return db
    .select()
    .from(sellerProfileRevisions)
    .where(params.tenantId ? eq(sellerProfileRevisions.tenantId, params.tenantId) : isNull(sellerProfileRevisions.tenantId))
    .orderBy(desc(sellerProfileRevisions.createdAt))
    .limit(limit);
}

export async function listTaxPoliciesForTenant(tenantId: string | null) {
  const db = getDb();
  try {
    const result = tenantId
      ? await db.execute(sql`
          select *
          from "tax_policies"
          where "tenantId" = ${tenantId} or "tenantId" is null
          order by "effectiveFrom" desc
        `)
      : await db.execute(sql`
          select *
          from "tax_policies"
          where "tenantId" is null
          order by "effectiveFrom" desc
        `);

    return extractSqlRows(result).map((row: Record<string, any>) => ({
      id: row.id ?? null,
      tenantId: row.tenantId ?? row.tenant_id ?? tenantId ?? null,
      stream: row.stream ?? "domestic",
      taxName: row.taxName ?? row.tax_name ?? "VAT",
      taxRatePercent: String(row.taxRatePercent ?? row.tax_rate_percent ?? "0"),
      isEnabled: row.isEnabled ?? row.is_enabled ?? true,
      effectiveFrom: row.effectiveFrom ?? row.effective_from ?? null,
      effectiveTo: row.effectiveTo ?? row.effective_to ?? null,
      roundingPolicy: row.roundingPolicy ?? row.rounding_policy ?? "half_up_2dp",
      createdBy: row.createdBy ?? row.created_by ?? null,
      createdAt: row.createdAt ?? row.created_at ?? null,
      updatedAt: row.updatedAt ?? row.updated_at ?? null,
    }));
  } catch {
    return [];
  }
}

export async function upsertTaxPolicyForTenant(params: {
  tenantId: string | null;
  actorUserId: number;
  input: TaxPolicyInput;
}) {
  const db = getDb();
  const payload: InsertTaxPolicy = {
    tenantId: params.tenantId,
    stream: params.input.stream,
    taxName: params.input.taxName.trim(),
    taxRatePercent: params.input.taxRatePercent,
    isEnabled: params.input.isEnabled,
    effectiveFrom: params.input.effectiveFrom,
    effectiveTo: params.input.effectiveTo ?? null,
    roundingPolicy: normalizeNullableString(params.input.roundingPolicy) ?? "half_up_2dp",
    createdBy: params.actorUserId,
    updatedAt: new Date(),
  };

  const [created] = await db.insert(taxPolicies).values(payload).returning();
  return created;
}

export async function listInvoicesForUser(userId: number) {
  const db = getDb();
  return db
    .select()
    .from(invoices)
    .where(eq(invoices.userId, userId))
    .orderBy(desc(invoices.createdAt));
}

export async function getInvoiceForUser(params: { invoiceId: number; userId: number }) {
  const db = getDb();
  const [invoice] = await db
    .select()
    .from(invoices)
    .where(and(eq(invoices.id, params.invoiceId), eq(invoices.userId, params.userId)))
    .limit(1);
  if (!invoice) {
    return null;
  }

  const [payment] = await db
    .select()
    .from(payments)
    .where(eq(payments.invoiceId, invoice.id))
    .orderBy(desc(payments.createdAt))
    .limit(1);

  return {
    ...invoice,
    activePayment: payment
      ? {
        id: payment.id,
        status: payment.status,
        paymentChannel: payment.paymentChannel,
        amount: payment.amount,
        currency: payment.currency,
        promptpayAmountThb: payment.promptpayAmountThb ?? null,
        randomSatang: payment.randomSatang ?? null,
        sourceAmountUsd: payment.sourceAmountUsd ?? null,
        fxRate: payment.fxRate ?? null,
        fxRateDate: payment.fxRateDate ?? null,
        fxFetchedAt: payment.fxFetchedAt ?? null,
        fxSellSpreadBps: payment.fxSellSpreadBps ?? null,
        fxRiskBufferBps: payment.fxRiskBufferBps ?? null,
        fxEffectiveRate: payment.fxEffectiveRate ?? null,
        promptpayRecipientSnapshotJson: payment.promptpayRecipientSnapshotJson ?? null,
        providerPaymentType: payment.providerPaymentType,
        providerPaymentId: payment.providerPaymentId ?? null,
        providerReferenceId: payment.providerReferenceId ?? null,
        expiresAt: payment.expiresAt ?? null,
        paymentUrl:
          typeof payment.rawResponseJson?.paymentUrl === "string"
            ? payment.rawResponseJson.paymentUrl
            : null,
        qrCodeUrl:
          typeof payment.rawResponseJson?.qrCodeUrl === "string"
            ? payment.rawResponseJson.qrCodeUrl
            : null,
        qrPayload:
          typeof payment.rawResponseJson?.qrPayload === "string"
            ? payment.rawResponseJson.qrPayload
            : null,
      }
      : null,
  };
}

export async function getAdminVisibleInvoice(params: { invoiceId: number; tenantId: string | null }) {
  const db = getDb();
  const whereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);
  const [invoice] = await db
    .select()
    .from(invoices)
    .where(whereClause)
    .limit(1);
  return invoice ?? null;
}

export async function getAdminInvoiceAuditDetails(params: { invoiceId: number; tenantId: string | null }) {
  const db = getDb();
  const invoiceWhereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);

  const [row] = await db
    .select({
      invoice: invoices,
      customer: {
        id: users.id,
        name: users.name,
        email: users.email,
      },
    })
    .from(invoices)
    .innerJoin(users, eq(users.id, invoices.userId))
    .where(invoiceWhereClause)
    .limit(1);

  if (!row) return null;

  const [lineItems, paymentRows, auditRows] = await Promise.all([
    db
      .select()
      .from(invoiceLineItems)
      .where(eq(invoiceLineItems.invoiceId, row.invoice.id))
      .orderBy(invoiceLineItems.id),
    db
      .select()
      .from(payments)
      .where(eq(payments.invoiceId, row.invoice.id))
      .orderBy(desc(payments.createdAt)),
    db
      .select()
      .from(invoiceAuditLogs)
      .where(eq(invoiceAuditLogs.invoiceId, row.invoice.id))
      .orderBy(desc(invoiceAuditLogs.createdAt)),
  ]);

  const paymentIds = paymentRows.map((payment) => payment.id);
  const [slipRows, attemptRows] = paymentIds.length > 0
    ? await Promise.all([
      db
        .select()
        .from(paymentSlips)
        .where(inArray(paymentSlips.paymentId, paymentIds))
        .orderBy(desc(paymentSlips.uploadedAt)),
      db
        .select()
        .from(paymentAttempts)
        .where(inArray(paymentAttempts.paymentId, paymentIds))
        .orderBy(desc(paymentAttempts.createdAt)),
    ])
    : [[], []];

  const actorIds = Array.from(new Set([
    ...auditRows.map((log) => log.actorId),
    ...slipRows.map((slip) => slip.reviewedBy),
  ].filter((id): id is number => typeof id === "number")));
  const actorRows = actorIds.length > 0
    ? await db
      .select({ id: users.id, name: users.name, email: users.email })
      .from(users)
      .where(inArray(users.id, actorIds))
    : [];
  const actorById = new Map(actorRows.map((actor) => [actor.id, actor]));

  return {
    invoice: row.invoice,
    customer: row.customer,
    lineItems,
    payments: paymentRows.map((payment) => ({
      ...payment,
      rawResponseJson: sanitizeSensitiveJson(payment.rawResponseJson),
      attempts: attemptRows
        .filter((attempt) => attempt.paymentId === payment.id)
        .map((attempt) => ({
          ...attempt,
          providerPayloadJson: sanitizeSensitiveJson(attempt.providerPayloadJson),
        })),
      slips: slipRows
        .filter((slip) => slip.paymentId === payment.id)
        .map((slip) => ({
          id: slip.id,
          paymentId: slip.paymentId,
          invoiceId: slip.invoiceId,
          userId: slip.userId,
          tenantId: slip.tenantId,
          originalFileName: slip.originalFileName,
          mimeType: slip.mimeType,
          fileSizeBytes: slip.fileSizeBytes,
          status: slip.status,
          customerNote: slip.customerNote,
          rejectionReason: slip.rejectionReason,
          uploadedAt: slip.uploadedAt,
          reviewedAt: slip.reviewedAt,
          reviewedBy: slip.reviewedBy,
          reviewer: slip.reviewedBy ? actorById.get(slip.reviewedBy) ?? null : null,
          createdAt: slip.createdAt,
          updatedAt: slip.updatedAt,
        })),
    })),
    auditLogs: auditRows.map((log) => ({
      ...log,
      beforeJson: sanitizeSensitiveJson(log.beforeJson),
      afterJson: sanitizeSensitiveJson(log.afterJson),
      actor: log.actorId ? actorById.get(log.actorId) ?? null : null,
    })),
  };
}

export async function listAdminInvoices(params: {
  tenantId: string | null;
  query?: string | null;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 50, 1), 200);
  const search = params.query?.trim() || null;
  const scopedTenantClause = params.tenantId ? eq(invoices.tenantId, params.tenantId) : undefined;

  if (!search) {
    if (!scopedTenantClause) {
      return db
        .select()
        .from(invoices)
        .orderBy(desc(invoices.createdAt))
        .limit(limit);
    }
    return db
      .select()
      .from(invoices)
      .where(scopedTenantClause)
      .orderBy(desc(invoices.createdAt))
      .limit(limit);
  }

  const numericSearch = Number(search);
  const paymentSearchClauses = [
    ilike(payments.providerPaymentId, `%${search}%`),
    ilike(payments.providerReferenceId, `%${search}%`),
    Number.isInteger(numericSearch) ? eq(payments.id, numericSearch) : undefined,
  ].filter(Boolean) as any[];
  const paymentMatches = paymentSearchClauses.length > 0
    ? await db
      .select({ invoiceId: payments.invoiceId })
      .from(payments)
      .where(or(...paymentSearchClauses))
      .limit(limit)
    : [];

  const invoiceIdMatches = paymentMatches.map((row) => row.invoiceId);
  const invoiceSearchClauses = [
    ilike(invoices.invoiceNumber, `%${search}%`),
    ilike(invoices.orderId, `%${search}%`),
    Number.isInteger(numericSearch) ? eq(invoices.userId, numericSearch) : undefined,
    invoiceIdMatches.length > 0 ? inArray(invoices.id, invoiceIdMatches) : undefined,
  ].filter(Boolean) as any[];
  const searchClause = invoiceSearchClauses.length > 0 ? or(...invoiceSearchClauses) : undefined;

  const whereClause = scopedTenantClause && searchClause ? and(scopedTenantClause, searchClause) : scopedTenantClause ?? searchClause;

  return db
    .select()
    .from(invoices)
    .where(whereClause)
    .orderBy(desc(invoices.createdAt))
    .limit(limit);
}

export async function listSupportRecoveryCases(params: {
  tenantId: string | null;
  invoiceId?: number | null;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 50, 1), 200);
  const scopedTenantClause = params.tenantId
    ? eq(supportRecoveryCases.tenantId, params.tenantId)
    : undefined;
  const invoiceClause = params.invoiceId
    ? eq(supportRecoveryCases.invoiceId, params.invoiceId)
    : undefined;
  const whereClause = scopedTenantClause && invoiceClause
    ? and(scopedTenantClause, invoiceClause)
    : scopedTenantClause ?? invoiceClause;

  if (!whereClause) {
    return db
      .select()
      .from(supportRecoveryCases)
      .orderBy(desc(supportRecoveryCases.createdAt))
      .limit(limit);
  }

  return db
    .select()
    .from(supportRecoveryCases)
    .where(whereClause)
    .orderBy(desc(supportRecoveryCases.createdAt))
    .limit(limit);
}

export async function listSupportRecoveryCasesForUser(params: {
  userId: number;
  invoiceId?: number | null;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 50, 1), 200);
  const whereClause = params.invoiceId
    ? and(
        eq(supportRecoveryCases.invoiceId, params.invoiceId),
        eq(invoices.userId, params.userId),
      )
    : eq(invoices.userId, params.userId);

  return db
    .select({
      id: supportRecoveryCases.id,
      tenantId: supportRecoveryCases.tenantId,
      userId: supportRecoveryCases.userId,
      invoiceId: supportRecoveryCases.invoiceId,
      paymentId: supportRecoveryCases.paymentId,
      status: supportRecoveryCases.status,
      issueType: supportRecoveryCases.issueType,
      customerReportedAt: supportRecoveryCases.customerReportedAt,
      assignedAdminId: supportRecoveryCases.assignedAdminId,
      resolutionType: supportRecoveryCases.resolutionType,
      resolutionNote: supportRecoveryCases.resolutionNote,
      evidenceJson: supportRecoveryCases.evidenceJson,
      resolvedAt: supportRecoveryCases.resolvedAt,
      createdAt: supportRecoveryCases.createdAt,
      updatedAt: supportRecoveryCases.updatedAt,
    })
    .from(supportRecoveryCases)
    .innerJoin(invoices, eq(invoices.id, supportRecoveryCases.invoiceId))
    .where(whereClause)
    .orderBy(desc(supportRecoveryCases.createdAt))
    .limit(limit);
}

export async function listInvoicePaymentsForAdmin(params: {
  tenantId: string | null;
  invoiceId: number;
}) {
  const db = getDb();
  const invoiceWhereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);

  const [invoice] = await db
    .select({ id: invoices.id })
    .from(invoices)
    .where(invoiceWhereClause)
    .limit(1);

  if (!invoice) {
    return [];
  }

  const rows = await db
    .select()
    .from(payments)
    .where(eq(payments.invoiceId, invoice.id))
    .orderBy(desc(payments.createdAt));

  return rows.map((payment) => ({
    ...payment,
    rawResponseJson: sanitizeSensitiveJson(payment.rawResponseJson),
  }));
}

export async function listInvoiceAuditLogsForAdmin(params: {
  tenantId: string | null;
  invoiceId: number;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 100, 1), 200);
  const invoiceWhereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);

  const [invoice] = await db
    .select({ id: invoices.id })
    .from(invoices)
    .where(invoiceWhereClause)
    .limit(1);

  if (!invoice) {
    return [];
  }

  const rows = await db
    .select()
    .from(invoiceAuditLogs)
    .where(eq(invoiceAuditLogs.invoiceId, invoice.id))
    .orderBy(desc(invoiceAuditLogs.createdAt))
    .limit(limit);

  return rows.map((row) => ({
    ...row,
    beforeJson: sanitizeSensitiveJson(row.beforeJson),
    afterJson: sanitizeSensitiveJson(row.afterJson),
  }));
}

export async function listInvoiceReconciliationRunsForAdmin(params: {
  tenantId: string | null;
  invoiceId: number;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 100, 1), 200);
  const invoiceWhereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);

  const [invoice] = await db
    .select({ id: invoices.id })
    .from(invoices)
    .where(invoiceWhereClause)
    .limit(1);

  if (!invoice) {
    return [];
  }

  const invoicePaymentRows = await db
    .select({ id: payments.id })
    .from(payments)
    .where(eq(payments.invoiceId, invoice.id));

  const paymentIds = invoicePaymentRows.map((row) => row.id);
  const entityClauses = [
    and(eq(reconciliationRuns.entityType, "invoice"), eq(reconciliationRuns.entityId, invoice.id)),
    ...paymentIds.map((paymentId) => and(eq(reconciliationRuns.entityType, "payment"), eq(reconciliationRuns.entityId, paymentId))),
  ];

  const rows = await db
    .select()
    .from(reconciliationRuns)
    .where(or(...entityClauses))
    .orderBy(desc(reconciliationRuns.createdAt))
    .limit(limit);

  return rows.map((row) => ({
    ...row,
    beforeJson: sanitizeSensitiveJson(row.beforeJson),
    afterJson: sanitizeSensitiveJson(row.afterJson),
  }));
}

export async function listInvoiceWebhookEventsForAdmin(params: {
  tenantId: string | null;
  invoiceId: number;
  limit?: number;
}) {
  const db = getDb();
  const limit = Math.min(Math.max(params.limit ?? 100, 1), 200);
  const invoiceWhereClause = params.tenantId
    ? and(eq(invoices.id, params.invoiceId), eq(invoices.tenantId, params.tenantId))
    : eq(invoices.id, params.invoiceId);

  const [invoice] = await db
    .select({ id: invoices.id })
    .from(invoices)
    .where(invoiceWhereClause)
    .limit(1);

  if (!invoice) {
    return [];
  }

  const directEvents = await db
    .select()
    .from(webhookEvents)
    .where(eq(webhookEvents.invoiceId, invoice.id))
    .orderBy(desc(webhookEvents.createdAt))
    .limit(limit);

  if (directEvents.length > 0) {
    return directEvents
      .map((event) => ({
        ...event,
        payloadJson: sanitizeSensitiveJson(event.payloadJson),
      }));
  }

  const relatedPayments = await db
    .select({
      providerPaymentId: payments.providerPaymentId,
      providerReferenceId: payments.providerReferenceId,
      providerEventLastSeenId: payments.providerEventLastSeenId,
    })
    .from(payments)
    .where(eq(payments.invoiceId, invoice.id));

  const needles = new Set<string>();
  for (const payment of relatedPayments) {
    if (payment.providerPaymentId) needles.add(payment.providerPaymentId);
    if (payment.providerReferenceId) needles.add(payment.providerReferenceId);
    if (payment.providerEventLastSeenId) needles.add(payment.providerEventLastSeenId);
  }

  const recentEvents = await db
    .select()
    .from(webhookEvents)
    .orderBy(desc(webhookEvents.createdAt))
    .limit(Math.max(limit * 3, 120));

  return recentEvents
    .filter((event) => {
      if (needles.size === 0) {
        return false;
      }
      const haystack = JSON.stringify(event.payloadJson ?? {});
      for (const needle of needles) {
        if (haystack.includes(needle)) {
          return true;
        }
      }
      return false;
    })
    .slice(0, limit)
    .map((event) => ({
      ...event,
      payloadJson: sanitizeSensitiveJson(event.payloadJson),
    }));
}
