/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/butter/butterTheme.ts
 * Command: astryx theme build client/src/themes/butter/butterTheme.ts
 * Generated: 2026-07-04T02:32:48.862Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const butterIconRegistry: IconRegistry;
export declare const butterTheme: DefinedTheme;
