from __future__ import annotations
from typing import Any, Protocol
from .models import AssetEvidence, CostEstimate, GenerationAuthorization

class CoreGateway(Protocol):
    async def get_project_snapshot(self, tenant_id:str, project_id:str)->dict[str,Any]: ...
    async def get_asset_evidence(self, tenant_id:str, project_id:str, asset_id:str)->AssetEvidence: ...
    async def get_provider_profile(self, profile_id:str)->dict[str,Any]: ...
    async def search_verified_research(self, tenant_id:str, project_id:str, query:str, max_results:int=5)->list[dict[str,Any]]: ...
    async def estimate_generation_cost(self, tenant_id:str, project_id:str, provider_plan:dict[str,Any])->CostEstimate: ...
    async def authorize_generation_submission(self, tenant_id:str, project_id:str, run_id:str, provider_plan:dict[str,Any], provider_plan_sha256:str, cost:CostEstimate)->GenerationAuthorization: ...
    async def get_approval_status(self, tenant_id:str, project_id:str, run_id:str, gate:str)->str: ...
    async def persist_stage_output(self, tenant_id:str, project_id:str, run_id:str, stage:str, payload:dict[str,Any], metadata:dict[str,Any])->None: ...
    async def record_agent_usage(self, tenant_id:str, project_id:str, run_id:str, stage:str, usage:dict[str,Any])->None: ...
    async def get_run_checkpoint(self, tenant_id:str, project_id:str, run_id:str)->dict[str,Any] | None: ...
    async def persist_run_checkpoint(self, tenant_id:str, project_id:str, run_id:str, checkpoint:dict[str,Any])->None: ...

class SessionStore(Protocol):
    async def get_items(self, key:str, limit:int|None=None)->list[dict[str,Any]]: ...
    async def add_items(self, key:str, items:list[dict[str,Any]])->None: ...
    async def pop_item(self, key:str)->dict[str,Any]|None: ...
    async def clear(self, key:str)->None: ...
