import {describe,expect,it} from "vitest";
import {validateDependencyGraph} from "../src";
import {entriesFor,parsedManifest,structureFor} from "./helpers/spec261";

describe("dependency graph contract",()=>{
 const build=(components:readonly Record<string,unknown>[])=>structureFor({...parsedManifest(),components},entriesFor("",[{path:"a.yaml",kind:"file",bytes:new Uint8Array()},{path:"b.yaml",kind:"file",bytes:new Uint8Array()}]));
 it("orders dependencies before dependants and is stable across declaration order",()=>{const a=[{id:"a",type:"assistant",source:"a.yaml",dependsOn:["b"]},{id:"b",type:"skill",source:"b.yaml"}];const first=validateDependencyGraph(build(a));const second=validateDependencyGraph(build([...a].reverse()));expect(first.order).toEqual(["b","a"]);expect(second.order).toEqual(first.order);});
 it("returns a canonical closed cycle and rejects duplicate edges",()=>{const result=validateDependencyGraph(build([{id:"a",type:"assistant",source:"a.yaml",dependsOn:["b","b"]},{id:"b",type:"assistant",source:"b.yaml",dependsOn:["a"]}]));expect(result.cycles[0]).toEqual(["a","b","a"]);expect(result.diagnostics.some((d)=>d.code==="DEPENDENCY_DUPLICATE")).toBe(true);});
 it("keeps optional safe external resolution contextual and bounds edges",()=>{const optional=validateDependencyGraph(build([{id:"a",type:"assistant",source:"a.yaml",dependsOn:[{capability:"cloud.search",required:false,omissionSafe:true}]}]));expect(optional.contextual).toHaveLength(1);expect(optional.diagnostics).toHaveLength(0);const capped=validateDependencyGraph(build([{id:"a",type:"assistant",source:"a.yaml",dependsOn:["b","b"]},{id:"b",type:"skill",source:"b.yaml"}]),{graphEdges:1});expect(capped.diagnostics[0]?.code).toBe("DEPENDENCY_LIMIT_EXCEEDED");});
 it("rejects invalid ranges and mutable production references unless content-pinned",()=>{const invalid=validateDependencyGraph(build([{id:"a",type:"assistant",source:"a.yaml",dependsOn:[{component:"b",versionRange:"not-semver"}]},{id:"b",type:"skill",source:"b.yaml"}]));expect(invalid.diagnostics.some((d)=>d.code==="DEPENDENCY_VERSION_INVALID")).toBe(true);const production={...parsedManifest(),publication:{channel:"production"},components:[{id:"a",type:"assistant",source:"a.yaml",version:"latest"}]};const graph=validateDependencyGraph(structureFor(production,entriesFor("",[{path:"a.yaml",kind:"file",bytes:new Uint8Array()}])));expect(graph.diagnostics.some((d)=>d.code==="DEPENDENCY_MUTABLE_REFERENCE")).toBe(true);});
 it("returns an invalid prerequisite result for malformed public input",()=>{expect(validateDependencyGraph(null as never).prerequisiteValid).toBe(false);});
});
