import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { canonicalizePackagePath, normalizePackageInventory, validatePackageStructure, validateDependencyGraph, scanPackageSecrets, computePackageDigest, classifyDigestExclusion, parseSpaasManifest, validateSpaasPackage } from "../src";
import type { ManifestSupportContext, PackageEntry } from "../src/model";
import { entriesFor } from "./helpers/spec261";

const support:ManifestSupportContext={supportedApiVersions:["spaas.smartaihub.app/v1"],supportedSchemaVersions:["1.0"],supportedRequiredFeatures:["spaas.events.delivery-semantics/v1"],supportedOptionalFeatures:[],extensions:[{namespace:"io.modelcontextprotocol/tasks",versions:["2026-07-28"],criticalities:["optional"]}]};
const fixture=readFileSync(new URL("./fixtures/manifest-valid.yaml",import.meta.url),"utf8");
const entries:PackageEntry[]=[{path:"app.manifest.yaml",kind:"file",bytes:new TextEncoder().encode(fixture)},{path:"assistants/construction.yaml",kind:"file",bytes:new TextEncoder().encode("safe: true\n")}];

describe("Spec 261 Phase A validators",()=>{
 it("normalizes safe paths and rejects traversal",()=>{expect(canonicalizePackagePath("ui/index.html").ok).toBe(true);expect(canonicalizePackagePath("../secret").ok).toBe(false);});
 it("builds deterministic inventory and validates references",()=>{const result=normalizePackageInventory([...entries].reverse());expect(result.ok).toBe(true);if(result.ok){expect(result.inventory.entries[0]?.path).toBe("app.manifest.yaml");const parsed=parseSpaasManifest(fixture,support);expect(parsed.ok).toBe(true);if(parsed.ok)expect(validatePackageStructure(parsed.manifest,result.inventory).ok).toBe(true);}});
 it("finds credential material without returning it",()=>{const result=normalizePackageInventory([{path:"src/config.txt",kind:"file",bytes:new TextEncoder().encode("api_key=abcdefghijklmnopqrstuvwxyz123456")}]);expect(result.ok).toBe(true);if(result.ok){const scan=scanPackageSecrets(result.inventory);expect(scan.clean).toBe(false);expect(JSON.stringify(scan)).not.toContain("abcdefghijklmnopqrstuvwxyz");}});
 it("computes stable digest and composes fixed stages",()=>{const inv=normalizePackageInventory(entries);const parsed=parseSpaasManifest(fixture,support);expect(inv.ok&&parsed.ok).toBe(true);if(inv.ok&&parsed.ok){const digest=computePackageDigest({manifest:parsed.manifest,inventory:inv.inventory});expect(digest.ok).toBe(true);const report=validateSpaasPackage({manifest:fixture,support,entries,profile:"offline-package"});expect(report.stages.map(x=>x.stage)).toEqual(["V1","V2","V3","V4","V5","V6","V7","V8"]);expect(["valid","invalid","needs_context"]).toContain(report.status);}});
 it("finds dependency cycles deterministically",()=>{const parsed=parseSpaasManifest(fixture,support);const inv=normalizePackageInventory(entriesFor("",[{path:"a.yaml",kind:"file",bytes:new Uint8Array()},{path:"b.yaml",kind:"file",bytes:new Uint8Array()}]));expect(parsed.ok&&inv.ok).toBe(true);if(parsed.ok&&inv.ok){const manifest={...parsed.manifest,components:[{id:"a",type:"agent",source:"a.yaml",dependsOn:["b"]},{id:"b",type:"agent",source:"b.yaml",dependsOn:["a"]}]};const structure=validatePackageStructure(manifest,inv.inventory);expect(validateDependencyGraph(structure).diagnostics[0]?.code).toBe("DEPENDENCY_CYCLE");}});
 it("binds digest provenance to the exact authoritative manifest bytes",()=>{const altered=fixture.replace("Construction AI","Different AI");const report=validateSpaasPackage({manifest:fixture,support,entries:[{...entries[0]!,bytes:new TextEncoder().encode(altered)},entries[1]!],profile:"offline-package"});expect(report.status).toBe("invalid");expect(report.diagnostics.some((d)=>d.location==="/app.manifest.yaml")).toBe(true);});
 it("enforces configured logical path ceilings",()=>{expect(normalizePackageInventory([{path:"a/b",kind:"file",bytes:new Uint8Array()}],{pathDepth:1}).ok).toBe(false);});
 it("classifies recognized binary data without decoding and fails closed on ambiguous bytes",()=>{const binary=normalizePackageInventory([{path:"assets/data.bin",kind:"file",bytes:new Uint8Array([0x89,0x50,0x4e,0x47,0xff])}]);const ambiguous=normalizePackageInventory([{path:"assets/text.txt",kind:"file",bytes:new Uint8Array([0xff,0xfe])}]);expect(binary.ok&&ambiguous.ok).toBe(true);if(binary.ok&&ambiguous.ok){expect(scanPackageSecrets(binary.inventory).complete).toBe(true);expect(scanPackageSecrets(ambiguous.inventory).complete).toBe(false);}});
 it("parses documented skill edges and classifies unresolved external dependencies",()=>{const parsed=parseSpaasManifest(fixture,support);const inv=normalizePackageInventory(entriesFor("",[{path:"a.yaml",kind:"file",bytes:new Uint8Array()}]));expect(parsed.ok&&inv.ok).toBe(true);if(parsed.ok&&inv.ok){const manifest={...parsed.manifest,components:[{id:"a",type:"assistant",source:"a.yaml",dependsOn:["skill:parse-boq"]}]};const structure=validatePackageStructure(manifest,inv.inventory);expect(validateDependencyGraph(structure).externalRequired.length).toBe(1);}});
 it("enforces bytewise path rejection and fixed digest exclusions",()=>{for(const path of ["/etc/passwd","C:/secret","\\\\host\\share","a\\b","a//b"])expect(canonicalizePackagePath(path).ok).toBe(false);expect(classifyDigestExclusion(".git/config")).toBe("vcs_metadata");expect(classifyDigestExclusion("provenance/signatures/a.json")).toBe("self_referential_attestation_envelope");expect(classifyDigestExclusion("provenance/sbom.json")).toBeUndefined();});
 it("rejects external evidence that is not bound to the current digest",()=>{const manifest=fixture.replace("components:","runtime:\n  placement:\n    required: true\ncomponents:");const packaged=[{...entries[0]!,bytes:new TextEncoder().encode(manifest)},entries[1]!];const wrong={stage:"V5" as const,checkId:"runtime-placement" as const,outcome:"passed" as const,schemaVersion:"spaas-evidence-v1" as const,digest:"spaas-package-v1:sha256:"+"0".repeat(64),manifestIdentity:"app_construction",manifestVersion:"1.0.0",profile:"release" as const,reasonCode:"RUNTIME_OK",evidenceId:"ev-1",observedAt:"2026-10-05T00:00:00Z",expiresAt:"2026-10-06T00:00:00Z"};const report=validateSpaasPackage({manifest,support,entries:packaged,profile:"release",externalEvidence:[wrong],validationTime:"2026-10-05T01:00:00Z"});expect(report.status).toBe("invalid");expect(report.diagnostics.some((d)=>d.stage==="V5"&&d.code==="VALIDATION_EVIDENCE_MISMATCH")).toBe(true);});
});
