import {describe,expect,it} from "vitest";
import {normalizePackageInventory,scanPackageSecrets} from "../src";
import {entriesFor,parsedManifest,structureFor} from "./helpers/spec261";

describe("bounded redacted secret scan",()=>{
 it("flags sensitive paths and common private-key suffixes",()=>{const inventory=normalizePackageInventory([{path:"secrets/client.pem",kind:"file",bytes:new Uint8Array()},{path:".env.local",kind:"file",bytes:new Uint8Array()}]);expect(inventory.ok).toBe(true);if(inventory.ok){const result=scanPackageSecrets(inventory.inventory);expect(result.findings.map((f)=>f.path)).toEqual([".env.local","secrets/client.pem"]);}});
 it("does not decode binary data and fails closed on ambiguous invalid UTF-8",()=>{const inventory=normalizePackageInventory([{path:"image.png",kind:"file",bytes:new Uint8Array([0x89,0x50,0x4e,0x47,0xff])},{path:"text.txt",kind:"file",bytes:new Uint8Array([0xff,0xfe])}]);expect(inventory.ok).toBe(true);if(inventory.ok){const result=scanPackageSecrets(inventory.inventory);expect(result.complete).toBe(false);expect(result.diagnostics.some((d)=>d.location==="text.txt")).toBe(true);}});
 it("scans valid UTF-8 text even when it contains NUL bytes",()=>{const value="abcdefghijklmnopqrstuvwxyz123456",inventory=normalizePackageInventory([{path:"config.txt",kind:"file",bytes:new TextEncoder().encode(`\0api_key=${value}`)}]);expect(inventory.ok).toBe(true);if(inventory.ok){const result=scanPackageSecrets(inventory.inventory);expect(result.clean).toBe(false);expect(result.findings[0]?.ruleId).toBe("SECRET_CREDENTIAL_ASSIGNMENT");}});
 it("redacts matching values and does not mutate inventory bytes",()=>{const secret="abcdefghijklmnopqrstuvwxyz123456";const inventory=normalizePackageInventory([{path:"src/config.txt",kind:"file",bytes:new TextEncoder().encode(`api_key=${secret}`)}]);expect(inventory.ok).toBe(true);if(inventory.ok){const before=inventory.inventory.entries[0]!.bytes;const result=scanPackageSecrets(inventory.inventory);expect(JSON.stringify(result)).not.toContain(secret);expect(inventory.inventory.entries[0]!.bytes).toEqual(before);}});
 it("preserves safe declared references but reports credential-shaped values at reference locations",()=>{const manifest={...parsedManifest(),requires:{secrets:[{bindingRef:"secret://vault/application/token"}]}};const safe=scanPackageSecrets(structureFor(manifest,entriesFor()));expect(safe.findings).toHaveLength(0);const unsafe={...manifest,requires:{secrets:[{bindingRef:"sk-abcdefghijklmnopqrstuvwxyz123456"}]}};const result=scanPackageSecrets(structureFor(unsafe,entriesFor()));expect(result.findings[0]?.location).toContain("bindingRef");expect(JSON.stringify(result)).not.toContain("sk-abcdefghijklmnopqrstuvwxyz123456");});
 it("fails closed for an invalid caller scan budget",()=>{const inventory=normalizePackageInventory([]);expect(inventory.ok).toBe(true);if(inventory.ok){const result=scanPackageSecrets(inventory.inventory,0);expect(result.complete).toBe(false);expect(result.diagnostics[0]?.code).toBe("SECRET_SCAN_LIMIT_EXCEEDED");}});
 it("returns a stable failure for malformed public input",()=>{expect(scanPackageSecrets(null as never).diagnostics[0]?.code).toBe("SECRET_SCAN_INPUT_INVALID");});
 it("rejects malformed inventory-shaped public input without throwing",()=>{expect(scanPackageSecrets({} as never).diagnostics[0]?.code).toBe("SECRET_SCAN_INPUT_INVALID");expect(scanPackageSecrets({inventory:null} as never).diagnostics[0]?.code).toBe("SECRET_SCAN_INPUT_INVALID");});
});
