import {describe,expect,it} from "vitest";
import {validateSpaasPackage} from "../src";
import {entriesFor,manifestText,support} from "./helpers/spec261";

describe("V1-V8 report composition",()=>{
 it("marks undeclared later stages not applicable and nonmandatory",()=>{const report=validateSpaasPackage({manifest:manifestText,support,entries:entriesFor(),profile:"release"});expect(report.status).toBe("valid");expect(report.stages.map((stage)=>stage.stage)).toEqual(["V1","V2","V3","V4","V5","V6","V7","V8"]);for(const stage of report.stages.slice(4))expect(stage).toMatchObject({status:"not_evaluated",mandatory:false,reason:"NOT_APPLICABLE"});});
 it("requires evidence only for manifest-applicable selected stages",()=>{const manifest=manifestText.replace("components:","runtime:\n  placement:\n    required: true\npublication:\n  publish: true\ncomponents:");const report=validateSpaasPackage({manifest,support,entries:entriesFor(manifest),profile:"marketplace",validationTime:"2026-10-05T01:00:00Z"});expect(report.status).toBe("needs_context");expect(report.stages[4]).toMatchObject({stage:"V5",status:"not_evaluated",mandatory:true});expect(report.stages[7]).toMatchObject({stage:"V8",status:"not_evaluated",mandatory:true});});
 it("serializes identically when package-entry enumeration changes",()=>{const entries=entriesFor();const first=validateSpaasPackage({manifest:manifestText,support,entries,profile:"offline-package"});const second=validateSpaasPackage({manifest:manifestText,support,entries:[...entries].reverse(),profile:"offline-package"});expect(JSON.stringify(second)).toBe(JSON.stringify(first));});
 it("classifies local dependency graph defects as a V2 package failure",()=>{const manifest=manifestText.replace("dependsOn: []","dependsOn: [missing-component]");const report=validateSpaasPackage({manifest,support,entries:entriesFor(manifest),profile:"offline-package"});expect(report.status).toBe("invalid");expect(report.stages[1]?.status).toBe("failed");expect(report.stages[1]?.diagnostics.some((item)=>item.code==="DEPENDENCY_UNRESOLVED")).toBe(true);});
 it("keeps negative evidence summaries structurally typed and ordered",()=>{const manifest=manifestText.replace("components:","runtime:\n  required: true\ncomponents:");const entries=entriesFor(manifest);const time="2026-10-05T01:00:00Z";const prepared=validateSpaasPackage({manifest,support,entries,profile:"release",validationTime:time});const item={stage:"V5" as const,checkId:"runtime-placement" as const,outcome:"failed" as const,schemaVersion:"spaas-evidence-v1" as const,digest:prepared.digest!.value,manifestIdentity:"app_construction",manifestVersion:"1.0.0",profile:"release" as const,reasonCode:"RUNTIME_UNAVAILABLE",evidenceId:"runtime-check-1",observedAt:time,expiresAt:"2026-10-06T01:00:00Z"};const report=validateSpaasPackage({manifest,support,entries,profile:"release",externalEvidence:[item],validationTime:time});expect(report.status).toBe("invalid");expect(report.stages[4]).toMatchObject({status:"failed",evidenceIds:["runtime-check-1"]});expect(typeof report.stages[4]?.reason).not.toBe("object");});
 it("fails closed for malformed runtime validation input",()=>{const report=validateSpaasPackage(null as never);expect(report.status).toBe("invalid");expect(report.stages).toHaveLength(8);expect(report.stages[0]?.status).toBe("failed");});
 it("keeps version-range policy defects in V3 and makes them invalidate offline reports",()=>{const manifest=manifestText.replace("dependsOn: []","dependsOn:\n      - capability: remote.storage\n        versionRange: invalid");const report=validateSpaasPackage({manifest,support,entries:entriesFor(manifest),profile:"offline-package"});expect(report.stages[1]?.status).toBe("passed");expect(report.stages[2]).toMatchObject({status:"failed",mandatory:true});expect(report.status).toBe("invalid");});
 it("does not downgrade a selected profile for failed non-mandatory evidence",()=>{const evidence={stage:"V8",checkId:"marketplace-policy",outcome:"passed",schemaVersion:"unsupported",digest:"bad",manifestIdentity:"app_construction",manifestVersion:"1.0.0",profile:"release",reasonCode:"OK",evidenceId:"evidence-1",observedAt:"2026-10-05T01:00:00Z",expiresAt:"2026-10-06T01:00:00Z"};const report=validateSpaasPackage({manifest:manifestText,support,entries:entriesFor(),profile:"release",externalEvidence:[evidence as never],validationTime:"2026-10-05T02:00:00Z"});expect(report.stages[7]).toMatchObject({status:"failed",mandatory:false});expect(report.status).toBe("valid");});
});
