export const PRESENTATION_ITEM_TYPE = "presentation";

export const PRESENTATION_EDITOR_ROUTE_BASE = "/presentation-editor";

export const PRESENTATION_LIMITS = {
  maxSlidesPerDeck: 200,
  maxAssetsPerDeck: 500,
  softDeckSizeBytes: 75 * 1024 * 1024,
  hardDeckSizeBytes: 100 * 1024 * 1024,
  maxElementsPerSlide: 250,
  maxSlideContentBytes: 256 * 1024,
} as const;

export const PRESENTATION_ERROR_CODE_VALUES = [
  "PRESENTATION_FEATURE_DISABLED",
  "PRESENTATION_ITEM_TYPE_MISMATCH",
  "PRESENTATION_UNSUPPORTED_ITEM_TYPE",
  "PRESENTATION_NOT_FOUND",
  "PRESENTATION_VERSION_CONFLICT",
  "PRESENTATION_CONVERSION_IN_PROGRESS",
  "PRESENTATION_PERMISSION_DENIED",
  "PRESENTATION_LIFECYCLE_RESTRICTED",
  "PRESENTATION_SLIDE_LIMIT_EXCEEDED",
  "PRESENTATION_ASSET_LIMIT_EXCEEDED",
  "PRESENTATION_DECK_SIZE_LIMIT_EXCEEDED",
  "PRESENTATION_VALIDATION_FAILED",
  "PRESENTATION_EXPORT_THROTTLED",
  "PRESENTATION_RENDER_SCHEMA_MISMATCH",
  "PRESENTATION_AI_GENERATION_FAILED",
  "PRESENTATION_AI_INSUFFICIENT_CREDITS",
  "PRESENTATION_AI_INVALID_RESPONSE",
] as const;

export type PresentationErrorCode = typeof PRESENTATION_ERROR_CODE_VALUES[number];

export const PRESENTATION_ERROR_CODE: Record<string, PresentationErrorCode> = {
  FEATURE_DISABLED: "PRESENTATION_FEATURE_DISABLED",
  ITEM_TYPE_MISMATCH: "PRESENTATION_ITEM_TYPE_MISMATCH",
  UNSUPPORTED_ITEM_TYPE: "PRESENTATION_UNSUPPORTED_ITEM_TYPE",
  NOT_FOUND: "PRESENTATION_NOT_FOUND",
  VERSION_CONFLICT: "PRESENTATION_VERSION_CONFLICT",
  CONVERSION_IN_PROGRESS: "PRESENTATION_CONVERSION_IN_PROGRESS",
  PERMISSION_DENIED: "PRESENTATION_PERMISSION_DENIED",
  LIFECYCLE_RESTRICTED: "PRESENTATION_LIFECYCLE_RESTRICTED",
  SLIDE_LIMIT_EXCEEDED: "PRESENTATION_SLIDE_LIMIT_EXCEEDED",
  ASSET_LIMIT_EXCEEDED: "PRESENTATION_ASSET_LIMIT_EXCEEDED",
  DECK_SIZE_LIMIT_EXCEEDED: "PRESENTATION_DECK_SIZE_LIMIT_EXCEEDED",
  VALIDATION_FAILED: "PRESENTATION_VALIDATION_FAILED",
  EXPORT_THROTTLED: "PRESENTATION_EXPORT_THROTTLED",
  RENDER_SCHEMA_MISMATCH: "PRESENTATION_RENDER_SCHEMA_MISMATCH",
  AI_GENERATION_FAILED: "PRESENTATION_AI_GENERATION_FAILED",
  AI_INSUFFICIENT_CREDITS: "PRESENTATION_AI_INSUFFICIENT_CREDITS",
  AI_INVALID_RESPONSE: "PRESENTATION_AI_INVALID_RESPONSE",
};

export const PRESENTATION_CONFLICT_SCHEMA_VERSION = "presentation_conflict_v1";
export const PRESENTATION_COMPATIBILITY_SCHEMA_VERSION = "presentation_compatibility_v1";
export const PRESENTATION_CONVERSION_SCHEMA_VERSION = "presentation_conversion_v1";
export const PRESENTATION_RENDER_SCHEMA_VERSION = "presentation_render_v1";
export const PRESENTATION_WARNING_CONTRACT_VERSION = "presentation_warning_contract_v1";
export const PRESENTATION_SLIDESHOW_SCHEMA_VERSION = "presentation_slideshow_v1";
export const PRESENTATION_EXPORT_SCHEMA_VERSION = "presentation_export_v1";

export const PRESENTATION_FEATURE_FLAG_ENV = "PRESENTATION_EDITOR_ENABLED";
export const PRESENTATION_EXPORT_WRITE_FLAG_ENV = "PRESENTATION_EXPORTS_ENABLED";
export const PRESENTATION_AI_GENERATION_FLAG_ENV = "PRESENTATION_AI_GENERATION_ENABLED";

export function isPresentationFeatureEnabled(): boolean {
  const raw = (process.env[PRESENTATION_FEATURE_FLAG_ENV] || "").trim().toLowerCase();
  if (!raw) {
    return true;
  }

  return !["0", "false", "off", "no", "disabled"].includes(raw);
}

export function isPresentationExportWriteEnabled(): boolean {
  const raw = (process.env[PRESENTATION_EXPORT_WRITE_FLAG_ENV] || "").trim().toLowerCase();
  if (!raw) {
    return true;
  }

  return !["0", "false", "off", "no", "disabled"].includes(raw);
}

export function isPresentationAIGenerationEnabled(): boolean {
  const raw = (process.env[PRESENTATION_AI_GENERATION_FLAG_ENV] || "")
    .trim()
    .toLowerCase();
  if (!raw) {
    return false; // default OFF — AI generation must be explicitly enabled
  }
  return ["1", "true", "on", "yes", "enabled"].includes(raw);
}
