/**
 * Vertical Drama Series — Character stock asset contracts + state machine (spec §7.1, §7.3, section-05).
 *
 * Durable per-series character reference stock. Each asset link points at a
 * canonical `media_assets` row (never a provider URL) and carries an approval /
 * QC lifecycle. Pure field-only contracts + tiny state helpers — safe to import
 * from the browser bundle (no server/db imports).
 */

import type { VerticalDramaPipelineStage } from "./contracts";

/** Lifecycle state of a single character-stock asset (spec §7.1 asset ledger). */
export type VerticalDramaCharacterAssetState =
  | "draft"
  | "generated"
  | "imported"
  | "approved"
  | "rejected"
  | "stale";

export const VERTICAL_DRAMA_CHARACTER_ASSET_STATES: readonly VerticalDramaCharacterAssetState[] = [
  "draft",
  "generated",
  "imported",
  "approved",
  "rejected",
  "stale",
] as const;

/** How the asset entered the stock — generated by a model or imported by the user. */
export type VerticalDramaCharacterAssetSource = "generated" | "imported";

/** Role the reference plays in the character bible. */
export type VerticalDramaCharacterAssetRole =
  | "primary_reference"
  | "expression"
  | "wardrobe"
  | "pose"
  | "product"
  | "other";

/**
 * A durable character-stock asset link. `mediaAssetId` is the tenant-scoped
 * canonical asset id; browser-facing projections never carry provider URLs.
 */
export type VerticalDramaCharacterAsset = {
  assetLinkId: string;
  seriesId: string;
  characterId: string;
  characterKey?: string;
  mediaAssetId?: string;
  assetType: "character_reference" | "product_reference" | string;
  role?: VerticalDramaCharacterAssetRole | string;
  state: VerticalDramaCharacterAssetState;
  approved: boolean;
  containsHumanFace?: boolean;
  qcStatus: "pending" | "passed" | "failed" | "needs_repair";
  checksumSha256?: string;
  source: VerticalDramaCharacterAssetSource;
  rejectionReason?: string;
  createdAt: string;
  updatedAt: string;
};

/** The per-series character-asset manifest projection (spec §7.3 §03 artifact). */
export type VerticalDramaCharacterAssetManifest = {
  seriesId: string;
  assets: VerticalDramaCharacterAsset[];
  approvedCount: number;
  pendingCount: number;
  staleCount: number;
  updatedAt: string;
};

/**
 * Allowed state transitions. Approval requires an explicit user action; a
 * generated/imported asset can never jump straight past review. `stale` is
 * reachable from any settled state and is re-workable back into the pipeline.
 */
export const VERTICAL_DRAMA_CHARACTER_ASSET_STATE_TRANSITIONS: Record<
  VerticalDramaCharacterAssetState,
  VerticalDramaCharacterAssetState[]
> = {
  draft: ["generated", "imported", "rejected"],
  generated: ["approved", "rejected", "stale"],
  imported: ["approved", "rejected", "stale"],
  approved: ["stale", "rejected"],
  rejected: ["draft", "generated", "imported"],
  stale: ["generated", "imported", "approved", "rejected"],
};

/** Whether `from -> to` is a legal character-asset state transition. */
export function canTransitionCharacterAssetState(
  from: VerticalDramaCharacterAssetState,
  to: VerticalDramaCharacterAssetState,
): boolean {
  if (from === to) return true;
  return (VERTICAL_DRAMA_CHARACTER_ASSET_STATE_TRANSITIONS[from] ?? []).includes(to);
}

/**
 * Apply a state transition, returning the next state or throwing on an illegal
 * transition. Callers persist the result; this never mutates in place.
 */
export function transitionCharacterAssetState(
  from: VerticalDramaCharacterAssetState,
  to: VerticalDramaCharacterAssetState,
): VerticalDramaCharacterAssetState {
  if (!canTransitionCharacterAssetState(from, to)) {
    throw new Error(`illegal_character_asset_transition: ${from} -> ${to}`);
  }
  return to;
}

/** Coarse downstream stage labels a character-reference change invalidates. */
export type VerticalDramaCharacterRefStaleTarget = "storyboard" | "start_frame" | "motion_prompt";

/** Coarse stage labels that go stale when a character reference changes (section-05 test). */
export const VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_TARGETS: readonly VerticalDramaCharacterRefStaleTarget[] =
  ["storyboard", "start_frame", "motion_prompt"] as const;

/** Pipeline stages invalidated (marked stale) by an approved character-reference change (spec §11.5). */
export const VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_STAGES: readonly VerticalDramaPipelineStage[] = [
  "storyboard_shotgrid",
  "start_frame_render_plan",
  "render_or_import_start_frames",
  "approve_start_frames",
  "video_motion_prompt_pack",
] as const;

/**
 * Given a character-reference change, return the downstream stages that must be
 * marked stale. Storyboard, start-frame, and motion-prompt stages are always
 * invalidated because they consume the (now-changed) character identity.
 */
export function stagesInvalidatedByCharacterRefChange(): {
  coarse: VerticalDramaCharacterRefStaleTarget[];
  pipelineStages: VerticalDramaPipelineStage[];
} {
  return {
    coarse: [...VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_TARGETS],
    pipelineStages: [...VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_STAGES],
  };
}

/** Whether the asset is usable as an approved reference for downstream stages. */
export function isCharacterAssetUsable(asset: Pick<VerticalDramaCharacterAsset, "state" | "approved">): boolean {
  return asset.approved === true && asset.state === "approved";
}
