/**
 * Vertical Drama Series — Character stock asset contracts + state machine (spec §7.1, §7.3, section-05).
 *
 * Durable per-series character reference stock. Each asset link points at a
 * canonical `media_assets` row (never a provider URL) and carries an approval /
 * QC lifecycle. Pure field-only contracts + tiny state helpers — safe to import
 * from the browser bundle (no server/db imports).
 */

import type { VerticalDramaPipelineStage } from "./contracts";
import type { CharacterCastingAgeProfile } from "./characterCastingAge";

/** Lifecycle state of a single character-stock asset (spec §7.1 asset ledger). */
export type VerticalDramaCharacterAssetState =
  | "draft"
  | "generated"
  | "imported"
  | "approved"
  | "rejected"
  | "stale";

export const VERTICAL_DRAMA_CHARACTER_ASSET_STATES: readonly VerticalDramaCharacterAssetState[] = [
  "draft",
  "generated",
  "imported",
  "approved",
  "rejected",
  "stale",
] as const;

/** How the asset entered the stock — generated by a model or imported by the user. */
export type VerticalDramaCharacterAssetSource = "generated" | "imported";

/** Role the reference plays in the character bible. */
export type VerticalDramaCharacterAssetRole =
  | "primary_reference"
  | "primary_portrait"
  | "casting_reference"
  | "portrait_candidate"
  | "angle_front"
  | "angle_left_three_quarter"
  | "angle_right_three_quarter"
  | "expression"
  | "wardrobe"
  | "pose"
  | "product"
  | "other";

/** Canonical v1 identity-angle pack slots (Feature 137 P2). */
export const VERTICAL_DRAMA_CHARACTER_ANGLE_ROLES = [
  "angle_front",
  "angle_left_three_quarter",
  "angle_right_three_quarter",
] as const;

export type VerticalDramaCharacterAngleRole =
  (typeof VERTICAL_DRAMA_CHARACTER_ANGLE_ROLES)[number];

export const VERTICAL_DRAMA_CHARACTER_ANGLE_DIRECTIVES: Record<
  VerticalDramaCharacterAngleRole,
  string
> = {
  angle_front:
    "front-facing head-and-shoulders portrait, eyes toward camera, neutral expression",
  angle_left_three_quarter:
    "left three-quarter facial angle, keep the character's left side visible, eyes toward camera",
  angle_right_three_quarter:
    "right three-quarter facial angle, keep the character's right side visible, eyes toward camera",
};

export type VerticalDramaPortraitCandidateStatus =
  | "previewed"
  | "submitting"
  | "queued"
  | "completed"
  | "failed"
  | "selected"
  | "superseded";

/** Browser-safe lifecycle metadata for an unselected first-portrait candidate. */
export type VerticalDramaPortraitCandidateProjection = {
  batchId: string;
  candidateId: string;
  index: number;
  count: number;
  status: VerticalDramaPortraitCandidateStatus;
  taskId?: string;
  selectedAt?: string;
  /**
   * Present only when `status === "failed"`. A clear, user-facing message —
   * the classified Thai policy message when the provider rejection matched
   * `isCharacterLockPolicyFailureMessage` (`characterLock.ts`), otherwise the
   * raw provider/timeout error. Populated by both a client-triggered
   * `settlePortraitCandidate` failed-branch AND the background
   * `reconcileStaleMcpMediaTasks` sweep (`mcpMediaAdapter.ts`) so a rejection
   * surfaces even after the tab that submitted it is gone (2026-07-16
   * stuck-candidate fix, Set A gap 5/6/7).
   */
  errorMessage?: string;
  /** True when `errorMessage` reflects a provider content-policy rejection (vs. a generic/timeout failure). */
  policyRejected?: boolean;
  /** True when this candidate was generated from optional casting references. */
  referenceGuided?: boolean;
  /** Server-derived apparent-age contract shared by every candidate in the batch. */
  castingAgeProfile?: Pick<
    CharacterCastingAgeProfile,
    "min" | "max" | "label" | "source" | "confidence" | "rationale" | "isMinor"
  >;
};

/**
 * A durable character-stock asset link. `mediaAssetId` is the tenant-scoped
 * canonical asset id; browser-facing projections never carry provider URLs.
 *
 * Scoped exception: `thumbnailUrl` is a read-only, derived-at-read-time
 * projection of the linked `media_assets.originalUrl` (via a LEFT JOIN in
 * `verticalDramaCharacterStock.ts#listRows`), included solely so the roster
 * card grid can render a thumbnail. It is never persisted on this contract
 * and is not a general-purpose provider-URL field — do not widen its scope.
 */
export type VerticalDramaCharacterAsset = {
  assetLinkId: string;
  seriesId: string;
  characterId: string;
  characterKey?: string;
  mediaAssetId?: string;
  assetType: "character_reference" | "product_reference" | string;
  role?: VerticalDramaCharacterAssetRole | string;
  state: VerticalDramaCharacterAssetState;
  approved: boolean;
  containsHumanFace?: boolean;
  qcStatus: "pending" | "passed" | "failed" | "needs_repair";
  checksumSha256?: string;
  source: VerticalDramaCharacterAssetSource;
  rejectionReason?: string;
  createdAt: string;
  updatedAt: string;
  thumbnailUrl?: string;
  portraitCandidate?: VerticalDramaPortraitCandidateProjection;
};

/** The per-series character-asset manifest projection (spec §7.3 §03 artifact). */
export type VerticalDramaCharacterAssetManifest = {
  seriesId: string;
  assets: VerticalDramaCharacterAsset[];
  approvedCount: number;
  pendingCount: number;
  staleCount: number;
  updatedAt: string;
};

/**
 * Allowed state transitions. Approval requires an explicit user action; a
 * generated/imported asset can never jump straight past review. `stale` is
 * reachable from any settled state and is re-workable back into the pipeline.
 */
export const VERTICAL_DRAMA_CHARACTER_ASSET_STATE_TRANSITIONS: Record<
  VerticalDramaCharacterAssetState,
  VerticalDramaCharacterAssetState[]
> = {
  draft: ["generated", "imported", "rejected"],
  generated: ["approved", "rejected", "stale"],
  imported: ["approved", "rejected", "stale"],
  approved: ["stale", "rejected"],
  rejected: ["draft", "generated", "imported"],
  stale: ["generated", "imported", "approved", "rejected"],
};

/** Whether `from -> to` is a legal character-asset state transition. */
export function canTransitionCharacterAssetState(
  from: VerticalDramaCharacterAssetState,
  to: VerticalDramaCharacterAssetState,
): boolean {
  if (from === to) return true;
  return (VERTICAL_DRAMA_CHARACTER_ASSET_STATE_TRANSITIONS[from] ?? []).includes(to);
}

/**
 * Apply a state transition, returning the next state or throwing on an illegal
 * transition. Callers persist the result; this never mutates in place.
 */
export function transitionCharacterAssetState(
  from: VerticalDramaCharacterAssetState,
  to: VerticalDramaCharacterAssetState,
): VerticalDramaCharacterAssetState {
  if (!canTransitionCharacterAssetState(from, to)) {
    throw new Error(`illegal_character_asset_transition: ${from} -> ${to}`);
  }
  return to;
}

/** Coarse downstream stage labels a character-reference change invalidates. */
export type VerticalDramaCharacterRefStaleTarget = "storyboard" | "start_frame" | "motion_prompt";

/** Coarse stage labels that go stale when a character reference changes (section-05 test). */
export const VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_TARGETS: readonly VerticalDramaCharacterRefStaleTarget[] =
  ["storyboard", "start_frame", "motion_prompt"] as const;

/** Pipeline stages invalidated (marked stale) by an approved character-reference change (spec §11.5). */
export const VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_STAGES: readonly VerticalDramaPipelineStage[] = [
  "storyboard_shotgrid",
  "start_frame_render_plan",
  "render_or_import_start_frames",
  "approve_start_frames",
  "video_motion_prompt_pack",
] as const;

/**
 * Given a character-reference change, return the downstream stages that must be
 * marked stale. Storyboard, start-frame, and motion-prompt stages are always
 * invalidated because they consume the (now-changed) character identity.
 */
export function stagesInvalidatedByCharacterRefChange(): {
  coarse: VerticalDramaCharacterRefStaleTarget[];
  pipelineStages: VerticalDramaPipelineStage[];
} {
  return {
    coarse: [...VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_TARGETS],
    pipelineStages: [...VERTICAL_DRAMA_CHARACTER_REF_CHANGE_STALE_STAGES],
  };
}

/** Whether the asset is usable as an approved reference for downstream stages. */
export function isCharacterAssetUsable(asset: Pick<VerticalDramaCharacterAsset, "state" | "approved">): boolean {
  return asset.approved === true && asset.state === "approved";
}

/**
 * Character-roster completeness signal (`vd-stuck-generation-and-lost-characters`
 * plan, Set B, added 2026-07-16) — flags a roster row that still needs manual
 * follow-up before it's production-ready. Independent reasons (a row can carry
 * more than one at once):
 *  - `"auto_registered_from_story"` — the row was INSERTed by
 *    `ensureRosterCharactersFromStory` (a dialogue speaker / shot character the
 *    deep-draft LLM introduced organically), never touched by the wizard or a
 *    manual create flow. Carries no DNA/portrait by construction.
 *  - `"missing_portrait"` — no `primary_portrait` character-asset in an
 *    approved/generated/imported state is on file yet (same selection rule
 *    the roster card thumbnail uses — see
 *    `VerticalDramaCharacterStockPanel.tsx`'s `resolveCharacterCardPortraitAsset`).
 *  - `"missing_dna"` — the validated canonical identity at
 *    `verticalDramaCharacters.data.visualBible.designDna` is absent or
 *    malformed. A story description alone is not Character DNA; it is only
 *    input context for the first prompt preview.
 * `characterRowToDto` computes this server-side; the client only reads it.
 */
export type VdCharacterNeedsSetupReason =
  | "auto_registered_from_story"
  | "missing_portrait"
  | "missing_dna";

export const VD_CHARACTER_NEEDS_SETUP_REASONS: readonly VdCharacterNeedsSetupReason[] = [
  "auto_registered_from_story",
  "missing_portrait",
  "missing_dna",
] as const;
