/**
 * Image-prompt model-family taxonomy for Vertical Drama start-frame shot
 * image prompts (`planning/vd-start-frame-prompt-modes/plan.md`).
 *
 * Classifies the sub-episode's currently-selected IMAGE model into the
 * prompt-shaping family that decides which of the two per-shot start-frame
 * prompt skills runs by default (`gpt` -> `policy_safe_rewrite`, everything
 * else -> `cinematic_narrative`), and carries the small stamp TypeScript
 * persists once a mode has produced a frame's prompt (the skills own all
 * creative guidance — this module only ever classifies a model id/name and
 * remembers which mode/family wrote a given prompt).
 *
 * Mirrors the shipped `videoPromptModelFamily.ts` 1:1 in structure/style —
 * imported from BOTH the server (generation-time fact block + persisted
 * `promptMode` stamping) and (later) the client (mode control + engine
 * badge), so it must stay dependency-free and side-effect-free. Deliberately
 * a SEPARATE module from `videoPromptModelFamily.ts` — image and video
 * models are selected independently per episode and can belong to
 * completely different families at the same time.
 */

export type ImagePromptModelFamily = "gpt" | "other";

export const IMAGE_PROMPT_MODEL_FAMILIES: readonly ImagePromptModelFamily[] = [
  "gpt",
  "other",
] as const;

/**
 * The two per-shot start-frame prompt skills the mode switch selects
 * between (`planning/vd-start-frame-prompt-modes/plan.md` — the pre-existing
 * `vertical-drama-shot-start-frame-prompt` skill stays the legacy engine for
 * every OTHER caller, e.g. `generateShotReferenceFramePrompt`'s supplementary
 * reference frames, and is not part of this union).
 */
export type VdImagePromptMode = "policy_safe_rewrite" | "cinematic_narrative";

export const VD_IMAGE_PROMPT_MODES: readonly VdImagePromptMode[] = [
  "policy_safe_rewrite",
  "cinematic_narrative",
] as const;

/**
 * Single source of truth for which skill folder each mode loads — used by
 * both the service's skill loaders and the real-file gate test, so the two
 * can never silently drift apart (taught-not-wired failure class).
 */
export const VD_IMAGE_PROMPT_MODE_SKILL_FOLDERS: Record<VdImagePromptMode, string> = {
  policy_safe_rewrite: "vertical-drama-shot-synopsis-image-prompt",
  cinematic_narrative: "vertical-drama-cinematic-narrative-image-prompt",
};

/**
 * Default-mode rule (`planning/vd-start-frame-prompt-modes/plan.md` decision
 * 5): `gpt` family defaults to the lean, minimal-invention rewrite mode (the
 * family that follows plain prose closely); every other family defaults to
 * the vision-grounded cinematic-narrative mode. A per-sub-episode explicit
 * choice always overrides this — see `VerticalDramaStartFramePlan.imagePromptMode`.
 */
export function resolveDefaultImagePromptMode(
  family: ImagePromptModelFamily,
): VdImagePromptMode {
  return family === "gpt" ? "policy_safe_rewrite" : "cinematic_narrative";
}

export interface ImagePromptModelFamilySource {
  modelId?: string | null;
  name?: string | null;
  provider?: string | null;
  configJson?: Record<string, unknown> | null;
}

/**
 * Metadata stamped onto a `startFramePlan.frames[]` entry when its image
 * prompt is (re)generated by one of the two new modes (never stamped for a
 * legacy-skill-authored frame) — mirrors `VideoPromptModelTarget`'s shape.
 * `imageModelId` is omitted (rather than an empty string) when the episode
 * has no selected image model yet at generation time.
 */
export interface VdImagePromptModeStamp {
  mode: VdImagePromptMode;
  /** Whether `mode` came from an explicit per-sub-episode user choice or the auto-resolved family default. */
  resolvedFrom: "user" | "auto";
  imageModelFamily: ImagePromptModelFamily;
  imageModelId?: string;
  /** ISO timestamp of generation. */
  generatedAt: string;
}

// Letter-only boundaries so version-suffixed/path-prefixed ids still match
// ("gpt-image-1.5-all", "higgsfield/gpt_image_2") while letter-embedded
// fragments ("forgotten-image") do not.
const GPT_IMAGE_TOKEN = /(^|[^a-z])gpt[-_]image([^a-z]|$)/i;
const GPT_4O_IMAGE_TOKEN = /(^|[^a-z])gpt-4o[-_]?image([^a-z]|$)/i;
const DALL_E_TOKEN = /(^|[^a-z])dall-?e([^a-z]|$)/i;

const configJsonHints = (configJson?: Record<string, unknown> | null): string => {
  if (!configJson || typeof configJson !== "object") return "";
  const hints: string[] = [];
  for (const key of ["kieModelId", "externalModelId", "providerModelId"]) {
    const value = (configJson as Record<string, unknown>)[key];
    if (typeof value === "string") hints.push(value);
  }
  return hints.join(" ");
};

/**
 * Resolve which prompt-shaping family a start-frame IMAGE model belongs to.
 * `gpt` matches `gpt-image`/`gpt_image`, `gpt-4o...image`, or `dall-e` in the
 * model's id, name, provider, or `configJson` id-like hints
 * (`kieModelId`/`externalModelId`/`providerModelId`); anything unrecognized
 * is `other`. Pure string matching — never throws — so callers can run it
 * unconditionally without a try/catch of their own (though the router still
 * wraps its OWN model-lookup step, since resolving which model row to pass
 * in here can fail independently — see that call site's doc comment).
 */
export function resolveImagePromptTargetFamily(
  source: ImagePromptModelFamilySource | null | undefined,
): ImagePromptModelFamily {
  if (!source) return "other";
  const idAndName = [source.modelId ?? "", source.name ?? "", configJsonHints(source.configJson)]
    .join(" ")
    .trim();
  const provider = (source.provider ?? "").trim();
  const haystack = `${idAndName} ${provider}`;
  if (
    GPT_IMAGE_TOKEN.test(haystack) ||
    GPT_4O_IMAGE_TOKEN.test(haystack) ||
    DALL_E_TOKEN.test(haystack)
  ) {
    return "gpt";
  }
  return "other";
}
