/**
 * Vertical Drama Series — Location stock asset contracts + state machine
 * (`planning/polished-toasting-gadget.md` Phase 2).
 *
 * Durable per-series location reference stock — mirrors `characterAssets.ts`
 * in shape, deliberately kept as an INDEPENDENT type/state system (does not
 * import or reuse `VerticalDramaCharacterAssetState` or any other character
 * type) so the character and location asset pipelines stay decoupled. Each
 * asset link points at a canonical `media_assets` row (never a provider URL)
 * and carries an approval / QC lifecycle. Pure field-only contracts + tiny
 * state helpers — safe to import from the browser bundle (no server/db
 * imports).
 */

import type { VerticalDramaPipelineStage } from "./contracts";

/** Lifecycle state of a single location-stock asset. */
export type VerticalDramaLocationAssetState =
  | "draft"
  | "generated"
  | "imported"
  | "approved"
  | "rejected"
  | "stale";

export const VERTICAL_DRAMA_LOCATION_ASSET_STATES: readonly VerticalDramaLocationAssetState[] =
  ["draft", "generated", "imported", "approved", "rejected", "stale"] as const;

/** How the asset entered the stock — generated by a model or imported by the user. */
export type VerticalDramaLocationAssetSource = "generated" | "imported";

/** Role the reference plays in the location bible. Phase 2 only ever authors `establishing_plate`. */
export type VerticalDramaLocationAssetRole = "establishing_plate" | "other";

/**
 * A durable location-stock asset link. `mediaAssetId` is the tenant-scoped
 * canonical asset id; browser-facing projections never carry provider URLs.
 *
 * Scoped exception: `thumbnailUrl` is a read-only, derived-at-read-time
 * projection of the linked `media_assets.originalUrl` (mirrors the same
 * scoped exception documented on `VerticalDramaCharacterAsset`), included
 * solely so a location card can render a thumbnail. It is never persisted on
 * this contract and is not a general-purpose provider-URL field.
 */
export type VerticalDramaLocationAsset = {
  assetLinkId: string;
  seriesId: string;
  locationId: string;
  locationKey?: string;
  mediaAssetId?: string;
  assetType: "location_reference" | string;
  role?: VerticalDramaLocationAssetRole | string;
  state: VerticalDramaLocationAssetState;
  approved: boolean;
  qcStatus: "pending" | "passed" | "failed" | "needs_repair";
  checksumSha256?: string;
  source: VerticalDramaLocationAssetSource;
  rejectionReason?: string;
  createdAt: string;
  updatedAt: string;
  thumbnailUrl?: string;
};

/** The per-series location-asset manifest projection. */
export type VerticalDramaLocationAssetManifest = {
  seriesId: string;
  assets: VerticalDramaLocationAsset[];
  approvedCount: number;
  pendingCount: number;
  staleCount: number;
  updatedAt: string;
};

/**
 * Allowed state transitions — same shape as
 * `VERTICAL_DRAMA_CHARACTER_ASSET_STATE_TRANSITIONS`, independently declared
 * so the two systems can diverge later without cross-impact. Approval
 * requires an explicit user action; a generated/imported asset can never
 * jump straight past review. `stale` is reachable from any settled state and
 * is re-workable back into the pipeline.
 */
export const VERTICAL_DRAMA_LOCATION_ASSET_STATE_TRANSITIONS: Record<
  VerticalDramaLocationAssetState,
  VerticalDramaLocationAssetState[]
> = {
  draft: ["generated", "imported", "rejected"],
  generated: ["approved", "rejected", "stale"],
  imported: ["approved", "rejected", "stale"],
  approved: ["stale", "rejected"],
  rejected: ["draft", "generated", "imported"],
  stale: ["generated", "imported", "approved", "rejected"],
};

/** Whether `from -> to` is a legal location-asset state transition. */
export function canTransitionLocationAssetState(
  from: VerticalDramaLocationAssetState,
  to: VerticalDramaLocationAssetState
): boolean {
  if (from === to) return true;
  return (VERTICAL_DRAMA_LOCATION_ASSET_STATE_TRANSITIONS[from] ?? []).includes(
    to
  );
}

/**
 * Apply a state transition, returning the next state or throwing on an
 * illegal transition. Callers persist the result; this never mutates in
 * place.
 */
export function transitionLocationAssetState(
  from: VerticalDramaLocationAssetState,
  to: VerticalDramaLocationAssetState
): VerticalDramaLocationAssetState {
  if (!canTransitionLocationAssetState(from, to)) {
    throw new Error(`illegal_location_asset_transition: ${from} -> ${to}`);
  }
  return to;
}

/** Coarse downstream stage labels a location-reference change invalidates. */
export type VerticalDramaLocationRefStaleTarget =
  | "storyboard"
  | "start_frame"
  | "motion_prompt";

/** Coarse stage labels that go stale when a location reference changes. */
export const VERTICAL_DRAMA_LOCATION_REF_CHANGE_STALE_TARGETS: readonly VerticalDramaLocationRefStaleTarget[] =
  ["storyboard", "start_frame", "motion_prompt"] as const;

/** Pipeline stages invalidated (marked stale) by an approved location-reference change. */
export const VERTICAL_DRAMA_LOCATION_REF_CHANGE_STALE_STAGES: readonly VerticalDramaPipelineStage[] =
  [
    "storyboard_shotgrid",
    "start_frame_render_plan",
    "render_or_import_start_frames",
    "approve_start_frames",
    "video_motion_prompt_pack",
  ] as const;

/**
 * Given a location-reference change, return the downstream stages that must
 * be marked stale. Storyboard, start-frame, and motion-prompt stages are
 * always invalidated because they consume the (now-changed) location
 * identity.
 */
export function stagesInvalidatedByLocationRefChange(): {
  coarse: VerticalDramaLocationRefStaleTarget[];
  pipelineStages: VerticalDramaPipelineStage[];
} {
  return {
    coarse: [...VERTICAL_DRAMA_LOCATION_REF_CHANGE_STALE_TARGETS],
    pipelineStages: [...VERTICAL_DRAMA_LOCATION_REF_CHANGE_STALE_STAGES],
  };
}

/** Whether the asset is usable as an approved reference for downstream stages. */
export function isLocationAssetUsable(
  asset: Pick<VerticalDramaLocationAsset, "state" | "approved">
): boolean {
  return asset.approved === true && asset.state === "approved";
}
