/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: client/src/themes/chocolate/chocolateTheme.ts
 * Command: astryx theme build client/src/themes/chocolate/chocolateTheme.ts
 * Generated: 2026-07-04T02:32:49.319Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const chocolateIconRegistry: IconRegistry;
export declare const chocolateTheme: DefinedTheme;
